---
title: MANE NOBISCUM DOMINE
subtitle: |
    | APOSTOLIC LETTER
    | ***MANE NOBISCUM DOMINE***
    | OF THE HOLY FATHER
    | **JOHN PAUL II**
    | TO THE BISHOPS, CLERGY AND FAITHFUL
    | FOR THE YEAR OF THE EUCHARIST
---

 


 

# INTRODUCTION

1\. "Stay with us, Lord, for it is almost evening" (cf. *Lk* 24:29).
This was the insistent invitation that the two disciples journeying to
Emmaus on the evening of the day of the resurrection addressed to the
Wayfarer who had accompanied them on their journey. Weighed down with
sadness, they never imagined that this stranger was none other than
their Master, risen from the dead. Yet they felt their hearts burning
within them (cf. v. 32) as he spoke to them and "explained" the
Scriptures. The light of the Word unlocked the hardness of their hearts
and "opened their eyes" (cf. v. 31). Amid the shadows of the passing day
and the darkness that clouded their spirit, the Wayfarer brought a ray
of light which rekindled their hope and led their hearts to yearn for
the fullness of light. "Stay with us", they pleaded. And he agreed. Soon
afterwards, Jesus\' face would disappear, yet the Master would "stay"
with them, hidden in the "breaking of the bread" which had opened their
eyes to recognize him.

2\. The *image of the disciples on the way to Emmaus* can serve as a
fitting guide for a Year when the Church will be particularly engaged in
living out the mystery of the Holy Eucharist. Amid our questions and
difficulties, and even our bitter disappointments, the divine Wayfarer
continues to walk at our side, opening to us the Scriptures and leading
us to a deeper understanding of the mysteries of God. When we meet him
fully, we will pass from the light of the Word to the light streaming
from the "Bread of life", the supreme fulfilment of his promise to "be
with us always, to the end of the age" (cf. *Mt* 28:20).

3\. The "breaking of bread"---as the Eucharist was called in earliest
times---has always been at the centre of the Church\'s life. Through it
Christ makes present within time the mystery of his death and
resurrection. In it he is received in person as the "living bread come
down from heaven" (*Jn* 6:51), and with him we receive the pledge of
eternal life and a foretaste of the eternal banquet of the heavenly
Jerusalem. Following the teaching of the Fathers, the Ecumenical
Councils and my own Predecessors, I have frequently urged the Church to
reflect upon the Eucharist, most recently in the Encyclical *[Ecclesia
de Eucharistia](http://www.vatican.va/edocs/ENG0821/_INDEX.HTM)*. Here I
do not intend to repeat this teaching, which I trust will be more deeply
studied and understood. At the same time I thought it helpful for this
purpose *to dedicate an entire Year to this wonderful sacrament*.

4\. As is known, the *Year of the Eucharist* will be celebrated from
October 2004 to October 2005. The idea for this celebration came from
two events which will serve to mark its beginning and end: the
*International Eucharistic Congress,* which will take place from 10-17
October 2004 in Guadalajara, Mexico, and the *Ordinary Assembly of the
Synod of Bishops*, which will be held in the Vatican from 2-29 October
2005 on the theme: "The Eucharist: Source and Summit of the Life and
Mission of the Church". I was also guided by another consideration: this
year\'s [*World Youth Day* will take place in Cologne from 16-21 August
2005](http://www.vatican.va/gmg/documents/gmg_2005_en.html). I would
like the young people to gather around the Eucharist as the vital source
which nourishes their faith and enthusiasm. A Eucharistic initiative of
this kind had been on my mind for some time: it is a natural development
of the pastoral impulse which I wanted to give to the Church,
particularly during the years of preparation for the Jubilee and in the
years that followed it.

5\. In the present Apostolic Letter, I wish to reaffirm this pastoral
continuity and to help everyone to grasp its spiritual significance. As
for the particular form which the *Year of the Eucharist* will take, I
am counting on the personal involvement of the Pastors of the particular
Churches, whose devotion to this great Mystery will not fail to suggest
suitable approaches. My Brother Bishops will certainly understand that
this initiative, coming as it does so soon after the celebration of the
*Year of the Rosary*, is meant to take place on a deeply spiritual
level, so that it will in no way interfere with the pastoral programmes
of the individual Churches. Rather, it can shed light upon those
programmes, anchoring them, so to speak, in the very Mystery which
nourishes the spiritual life of the faithful and the initiatives of each
local Church. I am not asking the individual Churches to alter their
pastoral programmes, but to emphasize the Eucharistic dimension which is
part of the whole Christian life. For my part, I would like in this
Letter to offer *some basic guidelines*; and I am confident that the
People of God, at every level, will welcome my proposal with enthusiasm
and fervent love.

 
{{< pagebreak >}}

# I -- IN THE WAKE OF THE COUNCIL AND THE GREAT JUBILEE

*Looking towards Christ*

6\. Ten years ago, in *[Tertio Millennio
Adveniente](/content/john-paul-ii/en/apost_letters/documents/hf_jp-ii_apl_10111994_tertio-millennio-adveniente.html)*
(10 November 1994), I had the joy of proposing to the Church a programme
of preparation for the *Great Jubilee of the Year 2000.* It seemed to me
that this historic moment presented itself as a great grace. I realized,
of course, that a simple chronological event, however evocative, could
not by itself bring about great changes. Unfortunately the Millennium
began with events which were in tragic continuity with the past, and
often with its worst aspects. A scenario emerged which, despite certain
positive elements, is marred by acts of violence and bloodshed which
cause continued concern. Even so, in inviting the Church to celebrate
the Jubilee of the two-thousandth anniversary of the Incarnation, I was
convinced---and I still am, more than ever!---that this celebration
would be of benefit to humanity in the "long term".

Jesus Christ stands at the centre not just of the history of the Church,
but also the history of humanity. In him, all things are drawn together
(cf. *Eph* 1:10; *Col* 1:15-20). How could we forget the enthusiasm with
which the Second Vatican Council, quoting Pope Paul VI, proclaimed that
Christ is "the goal of human history, the focal point of the desires of
history and civilization, the centre of mankind, the joy of all hearts,
and the fulfilment of all aspirations"?[^1] The Council\'s teaching gave
added depth to our understanding of the nature of the Church, and gave
believers a clearer insight not only into the mysteries of faith but
also into earthly realities, seen in the light of Christ. In the
Incarnate Word, both the mystery of God and the mystery of man are
revealed.[^2] In him, humanity finds redemption and fulfilment.

7\. In the Encyclical *[Redemptor
Hominis](http://www.vatican.va/edocs/ENG0218/_INDEX.HTM)*, at the
beginning of my Pontificate, I developed this idea, and I have
frequently returned to it on other occasions. The Jubilee was a fitting
time to invite believers once again to consider this fundamental truth.
The preparation for the great event was fully Trinitarian and
Christocentric. Within this plan, there clearly had to be a place for
the Eucharist. At the start of this Year of the Eucharist, I repeat the
words which I wrote in *[Tertio Millennio
Adveniente](/content/john-paul-ii/en/apost_letters/documents/hf_jp-ii_apl_10111994_tertio-millennio-adveniente.html):*
"The Year 2000 will be intensely Eucharistic; in the *Sacrament of the
Eucharist* the Saviour, who took flesh in Mary\'s womb twenty centuries
ago, continues to offer himself to humanity as the source of divine
life".[^3] The International Eucharistic Congress, held that year in
Rome, also helped to focus attention on this aspect of the Great
Jubilee. It is also worth recalling that my Apostolic Letter *[Dies
Domini](/content/john-paul-ii/en/apost_letters/documents/hf_jp-ii_apl_05071998_dies-domini.html)*,
written in preparation for the Jubilee, invited believers to meditate on
Sunday as the day of the Risen Lord and the special day of the Church.
At that time I urged everyone to rediscover the celebration of the
Eucharist as the heart of Sunday.[^4]

*Contemplating with Mary the face of Christ*

8\. The fruits of the Great Jubilee were collected in the Apostolic
Letter *[Novo Millennio
Ineunte](/content/john-paul-ii/en/apost_letters/documents/hf_jp-ii_apl_20010106_novo-millennio-ineunte.html)*.
In this programmatic document, I suggested an ever greater pastoral
engagement based on the contemplation of the face of Christ, as part of
an ecclesial pedagogy aimed at "the high standard" of holiness and
carried out especially through the art of prayer.[^5] How could such a
programme be complete without a commitment to the liturgy and in
particular to the *cultivation of Eucharistic life?* As I said at the
time: "In the twentieth century, especially since the Council, there has
been a great development in the way the Christian community celebrates
the Sacraments, especially the Eucharist. It is necessary to continue in
this direction, and to stress particularly *the Sunday Eucharist* and
*Sunday* itself, experienced as a special day of faith, the day of the
Risen Lord and of the gift of the Spirit, the true weekly Easter".[^6] In
this context of a training in prayer, I recommended the celebration of
the *Liturgy of the Hours*, by which the Church sanctifies the different
hours of the day and the passage of time through the liturgical year.

9\. Subsequently, with the proclamation of the Year of the Rosary and
the publication of the Apostolic Letter *[Rosarium Virginis
Mariae](/content/john-paul-ii/en/apost_letters/documents/hf_jp-ii_apl_20021016_rosarium-virginis-mariae.html)*,
I returned to the theme of contemplating the face of Christ, now *from a
Marian perspective*, by encouraging once more the recitation of the
Rosary. This traditional prayer, so highly recommended by the
Magisterium and so dear to the People of God, has a markedly biblical
and evangelical character, focused on the name and the face of Jesus as
contemplated in the mysteries and by the repetition of the "Hail Mary".
In its flow of repetitions, it represents *a kind of pedagogy of love*,
aimed at evoking within our hearts the same love that Mary bore for her
Son. For this reason, developing a centuries-old tradition by the
addition of the mysteries of light, I sought to make this privileged
form of contemplation an even more complete "compendium of the
Gospel".[^7] And how could the mysteries of light not culminate in the
Holy Eucharist?

*From the Year of the Rosary to the Year of the Eucharist*

10\. In the midst of the *Year of the Rosary*, I issued the Encyclical
Letter *[Ecclesia de
Eucharistia](http://www.vatican.va/edocs/ENG0821/_INDEX.HTM),* with the
intention of shedding light on the mystery of the Eucharist in its
inseparable and vital relation to the Church. I urged all the faithful
to celebrate the Eucharistic sacrifice with due reverence, offering to
Jesus present in the Eucharist, both within and outside Mass, the
worship demanded by so great a Mystery. Above all, I suggested once
again the need for a Eucharistic spirituality and pointed to Mary,
"woman of the Eucharist",[^8] as its model.

The *Year of the Eucharist* takes place against *a background which has
been enriched by the passage of the years*, while remaining ever rooted
in the theme of Christ and the contemplation of his face. In a certain
sense, it is meant to be a year of synthesis, *the high-point of a
journey in progress*. Much could be said about how to celebrate this
year. I would simply offer some reflections intended to help us all to
experience it in a deeper and more fruitful way.

 
 
{{< pagebreak >}}



# II -- THE EUCHARIST, A MYSTERY OF LIGHT

"*He interpreted to them in all the Scriptures the things concerning
himself*" (*Lk* 24:27)

11\. The account of the Risen Jesus appearing to the two disciples on
the road to Emmaus helps us to focus on a primary aspect of the
Eucharistic mystery, one which should always be present in the devotion
of the People of God: *The Eucharist is a mystery of light!* What does
this mean, and what are its implications for Christian life and
spirituality?

Jesus described himself as the "light of the world" (*Jn* 8:12), and
this quality clearly appears at those moments in his life, like the
Transfiguration and the Resurrection, in which his divine glory shines
forth brightly. Yet in the Eucharist the glory of Christ remains veiled.
The Eucharist is pre-eminently a *mysterium fidei*. Through the mystery
of his complete hiddenness, Christ becomes a mystery of light, thanks to
which believers are led into the depths of the divine life. By a happy
intuition, Rublëv\'s celebrated icon of the Trinity clearly places the
Eucharist at the centre of the life of the Trinity.

12\. The Eucharist is light above all because at every Mass the liturgy
of the Word of God precedes the liturgy of the Eucharist in the unity of
the two "tables", the table of the Word and the table of the Bread. This
continuity is expressed in the Eucharistic discourse of Saint John\'s
Gospel, where Jesus begins his teaching by speaking of the mystery of
his person and then goes on to draw out its Eucharistic dimension: "My
flesh is food indeed, and my blood is drink indeed" (*Jn* 6:55). We know
that this was troubling for most of his listeners, which led Peter to
express the faith of the other Apostles and of the Church throughout
history: "Lord, to whom can we go? You have the words of eternal life"
(*Jn* 6:68). In the account of the disciples on the road to Emmaus,
Christ himself intervenes to show, "beginning with Moses and all the
prophets", how "all the Scriptures" point to the mystery of his person
(cf. *Lk* 24:27). His words make the hearts of the disciples "burn"
within them, drawing them out of the darkness of sorrow and despair, and
awakening in them a desire to remain with him: "Stay with us, Lord" (cf.
v. 29).

13\. The Fathers of the Second Vatican Council, in the Constitution
*[Sacrosanctum
Concilium](http://www.vatican.va/archive/hist_councils/ii_vatican_council/documents/vat-ii_const_19631204_sacrosanctum-concilium_en.html)*,
sought to make "the table of the word" offer the treasures of Scripture
more fully to the faithful.[^9] Consequently they allowed the biblical
readings of the liturgy to be proclaimed in a language understood by
all. It is Christ himself who speaks when the Holy Scriptures are read
in the Church.[^10] The Council Fathers also urged the celebrant to treat
the homily as part of the liturgy, aimed at explaining the word of God
and drawing out its meaning for the Christian life.[^11] Forty years
after the Council, the *Year of the Eucharist* can serve as an important
opportunity for Christian communities *to evaluate their progress in
this area*. It is not enough that the biblical passages are read in the
vernacular, if they are not also proclaimed with the care, preparation,
devout attention and meditative silence that enable the word of God to
touch people\'s minds and hearts.

"*They recognized him in the breaking of bread*" (cf. *Lk* 24:35)

14\. It is significant that the two disciples on the road to Emmaus,
duly prepared by our Lord\'s words, recognized him at table through the
simple gesture of the "breaking of bread". When minds are enlightened
and hearts are enkindled, signs begin to "speak". The Eucharist unfolds
in a dynamic context of signs containing a rich and luminous message.
Through these signs the mystery in some way opens up before the eyes of
the believer.

As I emphasized in my Encyclical *[Ecclesia de
Eucharistia](http://www.vatican.va/edocs/ENG0821/_INDEX.HTM)*, it is
important that no dimension of this sacrament should be neglected. We
are constantly tempted to reduce the Eucharist to our own dimensions,
while in reality *it is we who must open ourselves up to the dimensions
of the Mystery*. "The Eucharist is too great a gift to tolerate
ambiguity and depreciation".[^12]

15\. There is no doubt that the most evident dimension of the Eucharist
is that it is a *meal*. The Eucharist was born, on the evening of Holy
Thursday, in the setting of the Passover meal. *Being a meal* is part of
its very structure. "Take, eat\... Then he took a cup and\... gave it to
them, saying: Drink from it, all of you" (*Mt* 26:26, 27). As such, it
expresses the fellowship which God wishes to establish with us and which
we ourselves must build with one another.

Yet it must not be forgotten that the Eucharistic meal also has a
profoundly and primarily *sacrificial* meaning.[^13] In the Eucharist,
Christ makes present to us anew *the sacrifice offered once for all on
Golgotha*. Present in the Eucharist as the Risen Lord, he nonetheless
bears the marks of his passion, of which every Mass is a "memorial", as
the Liturgy reminds us in the acclamation following the consecration:
"We announce your death, Lord, we proclaim your resurrection\...". At
the same time, while the Eucharist makes present what occurred in the
past, it also *impels us towards the future, when Christ will come
again* at the end of history. This "eschatological" aspect makes the
Sacrament of the Eucharist an event which draws us into itself and fills
our Christian journey with hope.

*"I am with you always\...*" (*Mt* 28:20)

16\. All these dimensions of the Eucharist come together in one aspect
which more than any other makes a demand on our faith: *the mystery of
the "real" presence*. With the entire tradition of the Church, we
believe that Jesus is truly present under the Eucharistic species. This
presence---as Pope Paul VI rightly explained---is called "real" not in
an exclusive way, as if to suggest that other forms of Christ\'s
presence are not real, but *par excellence*, because Christ thereby
becomes substantially present, whole and entire, in the reality of his
body and blood.[^14] Faith demands that we approach the Eucharist fully
aware that we are approaching Christ himself. It is precisely his
presence which gives the other aspects of the Eucharist --- as meal, as
memorial of the Paschal Mystery, as eschatological anticipation --- a
significance which goes far beyond mere symbol- ism. The Eucharist is a
mystery of presence, the perfect fulfilment of Jesus\' promise to remain
with us until the end of the world.

*Celebrating, worshiping, contemplating*

17\. The Eucharist is a great mystery! And it is one which above all
must be *well celebrated*. Holy Mass needs to be set at the centre of
the Christian life and celebrated in a dignified manner by every
community, in accordance with established norms, with the participation
of the assembly, with the presence of ministers who carry out their
assigned tasks, and with a serious concern that singing and *liturgical
music* be suitably "sacred". One specific project of this *Year of the
Eucharist* might be for each parish community to study the General
Instruction of the Roman Missal. The best way to enter into the mystery
of salvation made present in the sacred "signs" remains that of
following faithfully the unfolding of the liturgical year. Pastors
should be committed to that *"mystagogical" catechesis* so dear to the
Fathers of the Church, by which the faithful are helped to understand
the meaning of the liturgy\'s words and actions, to pass from its signs
to the mystery which they contain, and to enter into that mystery in
every aspect of their lives.

18\. There is a particular need to cultivate *a lively awareness of
Christ\'s real presence*, both in the celebration of Mass and in the
worship of the Eucharist outside Mass. Care should be taken to show that
awareness through tone of voice, gestures, posture and bearing. In this
regard, liturgical law recalls---and I myself have recently
reaffirmed[^15]---the importance of moments of silence both in the
celebration of Mass and in Eucharistic adoration. The way that the
ministers and the faithful treat the Eucharist should be marked by
profound respect.[^16] The presence of Jesus in the tabernacle must be a
kind of *magnetic pole* attracting an ever greater number of souls
enamoured of him, ready to wait patiently to hear his voice and, as it
were, to sense the beating of his heart. "O taste and see that the Lord
is good!" (*Ps* 34:8).

During this year *Eucharistic adoration outside Mass* should become a
particular commitment for individual parish and religious communities.
Let us take the time to kneel before Jesus present in the Eucharist, in
order to make reparation by our faith and love for the acts of
carelessness and neglect, and even the insults which our Saviour must
endure in many parts of the world. Let us deepen through adoration our
personal and communal contemplation, drawing upon aids to prayer
inspired by the word of God and the experience of so many mystics, old
and new. The Rosary itself, when it is profoundly understood in the
biblical and christocentric form which I recommended in the Apostolic
Letter *[Rosarium Virginis
Mariae](/content/john-paul-ii/en/apost_letters/documents/hf_jp-ii_apl_20021016_rosarium-virginis-mariae.html)*,
will prove a particularly fitting introduction to Eucharistic
contemplation, a contemplation carried out with Mary as our companion
and guide.[^17]

This year let us also celebrate with particular devotion the Solemnity
of *Corpus Christi*, with its traditional procession. Our faith in the
God who took flesh in order to become our companion along the way needs
to be everywhere proclaimed, especially in our streets and homes, as an
expression of our grateful love and as an inexhaustible source of
blessings.

 
 
{{< pagebreak >}}



# III -- THE EUCHARIST SOURCE AND MANIFESTATION OF COMMUNION


*"Abide in me, and I in you"* (*Jn* 15:4)

19\. When the disciples on the way to Emmaus asked Jesus to stay "with"
them, he responded by giving them a much greater gift: through the
Sacrament of the Eucharist he found a way to stay "in" them. Receiving
the Eucharist means entering into a profound communion with Jesus.
"Abide in me, and I in you" (*Jn* 15:4). This relationship of profound
and mutual "abiding" *enables us to have a certain foretaste of heaven
on earth*. Is this not the greatest of human yearnings? Is this not what
God had in mind when he brought about in history his plan of salvation?
God has placed in human hearts a "hunger" for his word (cf. *Am* 8:11),
a hunger which will be satisfied only by full union with him.
Eucharistic communion was given so that we might be "sated" with God
here on earth, in expectation of our complete fulfilment in heaven.

*One bread, one body*

20\. This special closeness which comes about in Eucharistic "communion"
cannot be adequately understood or fully experienced apart from
ecclesial communion. I emphasized this repeatedly in my Encyclical
*[Ecclesia de
Eucharistia](http://www.vatican.va/edocs/ENG0821/_INDEX.HTM)*. The
Church is the Body of Christ: we walk "with Christ" to the extent that
we are in relationship "with his body". Christ provided for the creation
and growth of this unity by the outpouring of his Holy Spirit. And he
himself constantly builds it up by his Eucharistic presence. It is the
one Eucharistic bread which makes us one body. As the Apostle Paul
states: "Because there is one bread, we who are many are one body, for
we all partake of the one bread" (*1Cor* 10:17). In the mystery of the
Eucharist Jesus builds up the Church as a communion, in accordance with
the supreme model evoked in his *priestly prayer:* "Even as you, Father,
are in me, and I in you, that they may also be in us, so that the world
may believe that you have sent me" (*Jn* 17:21).

21\. The Eucharist is both the *source* of ecclesial unity and its
greatest *manifestation*. The Eucharist is an *epiphany of communion*.
For this reason the Church sets conditions for full participation in the
celebration of the Eucharist.[^18] These various limitations ought to
make us ever more conscious of *the demands made by the communion which
Jesus asks of us*. It is a *hierarchical* communion, based on the
awareness of a variety of roles and ministries, as is seen by the
reference to the Pope and the Diocesan Bishop in the Eucharistic Prayer.
It is a *fraternal* communion, cultivated by a "spirituality of
communion" which fosters reciprocal openness, affection, understanding
and forgiveness.[^19]

*"\... of one heart and soul"* (*Acts* 4:32)

22\. At each Holy Mass we are called to measure ourselves against the
ideal of communion which the *Acts of the Apostles* paints as a model
for the Church in every age. It is the Church gathered around the
Apostles, called by the word of God, capable of sharing in spiritual
goods but in material goods as well (cf. *Acts* 2:42-47; 4:32-35). In
this *Year of the Eucharist* the Lord invites us to draw as closely as
possible to this ideal. Every effort should be made to experience fully
those occasions mentioned in the liturgy for the Bishop\'s "Stational
Mass", which he celebrates in the cathedral together with his presbyters
and deacons, with the participation of the whole People of God. Here we
see the principal "manifestation" of the Church.[^20] It would be
praiseworthy to specify *other significant occasions*, also on the
parochial level, which would increase a sense of communion and find in
the Eucharistic celebration a source of renewed fervour.

*The Lord\'s Day*

23\. In a particular way I ask that every effort be made this year to
experience Sunday as the day of the Lord and the day of the Church. I
would be happy if everyone would reflect once more on my words in the
Apostolic Letter *[Dies
Domini](/content/john-paul-ii/en/apost_letters/documents/hf_jp-ii_apl_05071998_dies-domini.html)*.
"At Sunday Mass, Christians relive with particular intensity the
experience of the Apostles on the evening of Easter, when the Risen Lord
appeared to them as they were gathered together (cf. *Jn* 20:19). In a
sense, the People of God of all times were present in that small nucleus
of disciples, the first-fruits of the Church".[^21] During this year of
grace, priests in their pastoral ministry should *be even more attentive
to Sunday Mass* as the celebration which brings together the entire
parish community, with the participation of different groups, movements
and associations.

 
 
{{< pagebreak >}}



# IV -- THE EUCHARIST, PRINCIPLE AND PLAN OF "MISSION"

*"They set out immediately"* (cf. *Lk* 24:33)

24\. The two disciples of Emmaus, upon recognizing the Lord, "set out
immediately" (cf. *Lk* 24:33), in order to report what they had seen and
heard. Once we have truly met the Risen One by partaking of his body and
blood, we cannot keep to ourselves the joy we have experienced. The
encounter with Christ, constantly intensified and deepened in the
Eucharist, issues in the Church and in every Christian *an urgent
summons to testimony and evangelization*. I wished to emphasize this in
my homily announcing the *Year of the Eucharist*, based on the words of
Saint Paul: "As often as you eat this bread and drink the cup, you
proclaim the Lord\'s death until he comes" (*1 Cor* 11:26). The Apostle
closely relates meal and proclamation: entering into communion with
Christ in the memorial of his Pasch also means sensing the duty to be a
missionary of the event made present in that rite.[^22] The dismissal at
the end of each Mass is *a charge* given to Christians, inviting them to
work for the spread of the Gospel and the imbuing of society with
Christian values.

25\. The Eucharist not only provides the interior strength needed for
this mission, but is also ---in some sense---*its plan*. For the
Eucharist is a mode of being, which passes from Jesus into each
Christian, through whose testimony it is meant to spread throughout
society and culture. For this to happen, each member of the faithful
must assimilate, through personal and communal meditation, the values
which the Eucharist expresses, the attitudes it inspires, the
resolutions to which it gives rise. Can we not see here *a special
charge* which could emerge from this *Year of the Eucharist?*

*Giving thanks*

26\. One fundamental element of this *plan* is found in the very meaning
of the word "Eucharist": thanksgiving. In Jesus, in his sacrifice, in
his unconditional "yes" to the will of the Father, is contained the
"yes", the "thank you" and the "amen" of all humanity. The Church is
called to remind men and women of this great truth. This is especially
urgent in the context of our secularized culture, characterized as it is
by a forgetfulness of God and a vain pursuit of human self-sufficiency.
Incarnating the Eucharistic "plan" in daily life, wherever people live
and work---in families, schools, the workplace, in all of life\'s
settings---means bearing witness that *human reality cannot be justified
without reference to the Creator:* "Without the Creator the creature
would disappear".[^23] This transcendent point of reference, which
commits us constantly to give thanks for all that we have and are---in
other words, to a "Eucharistic" attitude---in no way detracts from the
legitimate autonomy of earthly realities,[^24] but grounds that autonomy
more firmly by setting it within its proper limits.

In this *Year of the Eucharist* Christians ought to be committed to
bearing more forceful witness to God\'s presence in the world. We should
not be afraid to speak about God and to bear proud witness to our faith.
The "culture of the Eucharist" promotes a culture of dialogue, which
here finds strength and nourishment. It is a mistake to think that any
public reference to faith will somehow undermine the rightful autonomy
of the State and civil institutions, or that it can even encourage
attitudes of intolerance. If history demonstrates that mistakes have
also been made in this area by believers, as I acknowledged on the
occasion of the Jubilee, this must be attributed not to "Christian
roots", but to the failure of Christians to be faithful to those roots.
One who learns to say "thank you" in the manner of the crucified Christ
might end up as a martyr, but never as a persecutor.

*The way of solidarity*

27\. The Eucharist is not merely an expression of communion in the
Church\'s life; it is also a *project of solidarity* for all of
humanity. In the celebration of the Eucharist the Church constantly
renews her awareness of being a "sign and instrument" not only of
intimate union with God but also of the unity of the whole human
race.[^25] Each Mass, even when celebrated in obscurity or in isolation,
always has a universal character. The Christian who takes part in the
Eucharist learns to become a *promotor of communion, peace and
solidarity* in every situation. More than ever, our troubled world,
which began the new Millennium with the spectre of terrorism and the
tragedy of war, demands that Christians learn to experience the
Eucharist as *a great school of peace*, forming men and women who, at
various levels of responsibility in social, cultural and political life,
can become promotors of dialogue and communion.

*At the service of the least*

28\. There is one other point which I would like to emphasize, since it
significantly affects the authenticity of our communal sharing in the
Eucharist. It is the impulse which the Eucharist gives to the community
for *a practical commitment to building a more just and fraternal
society*. In the Eucharist our God has shown love in the extreme,
overturning all those criteria of power which too often govern human
relations and radically affirming the criterion of service: "If anyone
would be first, he must be last of all and servant of all" (*Mc* 9:35).
It is not by chance that the Gospel of John contains no account of the
institution of the Eucharist, but instead relates the "washing of feet"
(cf. *Jn* 13:1-20): by bending down to wash the feet of his disciples,
Jesus explains the meaning of the Eucharist unequivocally. Saint Paul
vigorously reaffirms the impropriety of a Eucharistic celebration
lacking charity expressed by practical sharing with the poor (cf.*1Cor*
11:17-22, 27-34).

Can we not make this *Year of the Eucharist* an occasion for diocesan
and parish communities to commit themselves in a particular way to
responding with fraternal solicitude to one of the many forms of poverty
present in our world? I think for example of the tragedy of hunger which
plagues hundreds of millions of human beings, the diseases which afflict
developing countries, the loneliness of the elderly, the hardships faced
by the unemployed, the struggles of immigrants. These are evils which
are present---albeit to a different degree---even in areas of immense
wealth. We cannot delude ourselves: by our mutual love and, in
particular, by our concern for those in need we will be recognized as
true followers of Christ (cf. *Jn* 13:35; *Mt* 25:31-46). This will be
the criterion by which the authenticity of our Eucharistic celebrations
is judged.

 
{{< pagebreak >}}



# CONCLUSION

29\. *O Sacrum Convivium, in quo Christus sumitur!* The *Year of the
Eucharist* has its source in the amazement with which the Church
contemplates this great Mystery. It is an amazement which I myself
constantly experience. It prompted my Encyclical *[Ecclesia de
Eucharistia](http://www.vatican.va/edocs/ENG0821/_INDEX.HTM)*. As I look
forward to the twenty-seventh year of my Petrine ministry, I consider it
a great grace to be able to call the whole Church to contemplate,
praise, and adore in a special way this ineffable Sacrament. May the
*Year of the Eucharist* be for everyone a precious opportunity to grow
in awareness of the incomparable treasure which Christ has entrusted to
his Church. May it encourage a more lively and fervent celebration of
the Eucharist, leading to a Christian life transformed by love.

There is room here for any number of initiatives, according to the
judgement of the Pastors of the particular Churches. The *Congregation
for Divine Worship and the Discipline of the Sacraments* will not fail
to provide some helpful suggestions and proposals. I do not ask,
however, for anything extraordinary, but rather that every initiative be
marked by a profound interiority. If the only result of this Year were
the revival in all Christian communities of the celebration of Sunday
Mass and an increase in Eucharistic worship outside Mass, this Year of
grace would be abundantly successful. At the same time, it is good to
aim high, and not to be content with mediocrity, since we know we can
always count on God\'s help.

30\. To you, dear *Brother Bishops*, I commend this Year, confident that
you will welcome my invitation with full apostolic zeal.

Dear *priests*, who repeat the words of consecration each day, and are
witnesses and heralds of the great miracle of love which takes place at
your hands: be challenged by the grace of this special Year; celebrate
Holy Mass each day with the same joy and fervour with which you
celebrated your first Mass, and willingly spend time in prayer before
the tabernacle.

May this be a Year of grace also for you, *deacons*, who are so closely
engaged in the ministry of the word and the service of the altar. I ask
you, *lectors, acolytes and extraordinary ministers of holy communion*,
to become ever more aware of the gift you have received in the service
entrusted to you for a more worthy celebration of the Eucharist.

In particular I appeal to you, *the priests of the future*. During your
time in the seminary make every effort to experience the beauty not only
of taking part daily in Holy Mass, but also of spending a certain amount
of time in dialogue with the Eucharistic Lord.

*Consecrated men and women*, called by that very consecration to more
prolonged contemplation: never forget that Jesus in the tabernacle wants
you to be at his side, so that he can fill your hearts with the
experience of his friendship, which alone gives meaning and fulfilment
to your lives.

May all of you, *the Christian faithful*, rediscover the gift of the
Eucharist as light and strength for your daily lives in the world, in
the exercise of your respective professions amid so many different
situations. Rediscover this above all in order to experience fully the
beauty and the mission of the *family*.

I have great expectations of you, *young people*, as I look forward to
our meeting at the next *World Youth Day* in Cologne. The theme of our
meeting---*"We have come to worship him"*---suggests how you can best
experience this Eucharistic year. Bring to your encounter with Jesus,
hidden in the Eucharist, all the enthusiasm of your age, all your hopes,
all your desire to love.

31\. We have before us the example of the Saints, who in the Eucharist
found nourishment on their journey towards perfection. How many times
did they shed tears of profound emotion in the presence of this great
mystery, or experience hours of inexpressible "spousal" joy before the
sacrament of the altar! May we be helped above all by the Blessed Virgin
Mary, whose whole life incarnated the meaning of the Eucharist. "The
Church, which looks to Mary as a model, is also called to imitate her in
her relationship with this most holy mystery".[^26] The Eucharistic Bread
which we receive is the spotless flesh of her Son: *Ave verum corpus
natum de Maria Virgine*. In this Year of grace, sustained by Mary, may
the Church discover new enthusiasm for her mission and come to
acknowledge ever more fully that the Eucharist is the source and summit
of her entire life.

To all of you I impart my Blessing as a pledge of grace and joy.

*From the Vatican, on 7 October, the Memorial of Our Lady of the Rosary,
in the year 2004, the twenty-sixth of my Pontificate.*

**IOANNES PAULUS PP.II**

------------------------------------------------------------------------

[^1]: Pastoral Constitution on the Church in the Modern World *Gaudium
et Spes*, 45.

[^2]: Cf. *ibid.*, 22.

[^3]: No. 55: *AAS* 87 (1995), 38.

[^4]: Cf. Nos. 32-34: *AAS* 90 (1998), 732-734.

[^5]: Cf. Nos. 30-32: *AAS* 93 (2001), 287-289.

[^6]: *Ibid.*, 35: *loc. cit*., 290-291.

[^7]: Cf. Apostolic Letter *Rosarium Virginis Mariae* (16 October 2002),
19-21: *AAS* 95 (2003), 18-20.

[^8]: Encyclical Letter *Ecclesia de Eucharistia* (17 April 2003), 53:
*AAS* 95 (2003), 469.

[^9]: Cf. No. 51.

[^10]: *Ibid.*, 7.

[^11]: Cf *ibid.*, 52.

[^12]: Encyclical Letter *Ecclesia de Eucharistia* (17 April 2003), 10:
*AAS* 95 (2003), 439.

[^13]: Cf. John Paul II, Encyclical Letter *Ecclesia de Eucharistia* (17
April 2003), 10: *AAS* 95 (2003), 439. Congregation for Divine Worship
and the Discipline of the Sacraments, Instruction *Redemptionis
Sacramentum* on certain matters to be observed or to be avoided
regarding the Most Holy Eucharist (25 March 2004), 38: *L\'Osservatore
Romano*, Weekly Edition in English, 28 April 2004, Special Insert, p.3.

[^14]: Cf. Encyclical Letter *Mysterium Fidei* (3 September 1965), 39:
*AAS* 57 (1965), 764; Sacred Congregation of Rites, Instruction
*Eucharisticum Mysterium* on the Worship of the Eucharistic Mystery (25
May 1967), 9: *AAS* 59 (1967), 547.

[^15]: Cf. Message *Spiritus et Sponsa*, for the fortieth anniversary of
the Constitution on the Sacred Liturgy *Sacrosanctum Concilium* (4
December 2003), 13: *AAS* 96 (2004), 425.

[^16]: Cf. Congregation for Divine Worship and the Discipline of the
Sacraments, Instruction *Redemptionis Sacramentum* on certain matters to
be observed or to be avoided regarding the Most Holy Eucharist (25 March
2004): *L\'Osservatore Romano*, Weekly Edition in English, 28 April
2004, Special Insert.

[^17]: Cf. *ibid.*, 137, *loc. cit.*, p.11.

[^18]: Cf. John Paul II, Encyclical Letter *Ecclesia de Eucharistia* (17
April 2003), 44: *AAS* 95 (2003), 462; *Code of Canon Law*, canon 908;
*Code of Canons of the Eastern Churches*, canon 702; Pontifical Council
for Promoting Christian Unity, *Directorium Oecumenicum* (25 March
1993), 122-125, 129-131: *AAS* 85 (1993), 1086-1089; Congregation for
the Doctrine of the Faith, Letter *Ad Exsequendam* (18 May 2001): *AAS*
93 (2001), 786.

[^19]: Cf. John Paul II, Apostolic Letter *Novo Millennio Ineunte* (6
January 2001), 43: *AAS* 93 (2001), 297.

[^20]: Cf. Second Vatican Ecumenical Council, Constitution on the Sacred
Liturgy *Sacrosanctum Concilium*, 41.

[^21]: No. 33: *AAS* 90 (1998), 733.

[^22]: Cf. Homily for the Solemnity of the Body and Blood of Christ (10
June 2004): *L\'Osservatore Romano*, 11-12 June 2004, p.6.

[^23]: Second Vatican Ecumenical Council, Pastoral Constitution on the
Church in the Modern World *Gaudium et Spes*, 36.

[^24]: *Ibid.*

[^25]: Cf. Second Vatican Ecumenical Council, Pastoral Constitution on
the Church *Lumen Gentium*, 1.

[^26]: John Paul II, Encyclical Letter *Ecclesia de Eucharistia* (17
April 2003), 53: *AAS* 95 (2003), 469.

 

Copyright © Libreria Editrice Vaticana

