---
title: Redemptionis Sacramentum
subtitle: |
    |
    | CONGREGATION FOR DIVINE WORSHIP
    | AND THE DISCIPLINE OF THE SACRAMENT
    | 
    | INSTRUCTION
    | 
    | ***Redemptionis Sacramentum***
    | 
    | ***On certain matters to be observed or to be avoided***
    | ***regarding the Most Holy Eucharist***
---

 

 

{{< pagebreak >}}

# Preamble

\[1.\] In the Most Holy Eucharist, Mother Church with steadfast faith
acknowledges the Sacrament of redemption,[^1]
joyfully takes it to herself, celebrates it and reveres it in adoration,
proclaiming the death of Christ Jesus and confessing his Resurrection
until he comes in glory[^2] to hand over, as
unconquered Lord and Ruler, eternal Priest and King of the Universe, a
kingdom of truth and life to the immense majesty of the Almighty Father.[^3]

\[2.\] The Church's doctrine regarding the Most Holy Eucharist, in which
the whole spiritual wealth of the Church is contained - namely Christ,
our Paschal Lamb[^4] - the Eucharist which is the
source and summit of the whole of Christian life,[^5] and which lies as a causative force behind
the very origins of the Church,[^6] has been
expounded with thoughtful care and with great authority over the course
of the centuries in the writings of the Councils and the Supreme
Pontiffs. Most recently, in fact, the Supreme Pontiff John Paul II, in
the Encyclical Letter *[Ecclesia de
Eucharistia](/edocs/ENG0821/_INDEX.HTM)*, set forth afresh certain
elements of great importance on this subject in view of the ecclesial
circumstances of our times.[^7]

In order that especially in the celebration of the Sacred Liturgy the
Church might duly safeguard so great a mystery in our own time as well,
the Supreme Pontiff has mandated that this Congregation for Divine
Worship and the Discipline of the Sacraments,[^8]
in collaboration with the Congregation for the Doctrine of the Faith,
should prepare this Instruction treating of certain matters pertaining
to the discipline of the Sacrament of the Eucharist. Those things found
in this Instruction are therefore to be read in the continuity with the
above-mentioned Encyclical Letter, *[Ecclesia de
Eucharistia](/edocs/ENG0821/_INDEX.HTM)*.

It is not at all the intention here to prepare a compendium of the norms
regarding the Most Holy Eucharist, but rather, to take up within this
Instruction some elements of liturgical norms that have been previously
expounded or laid down and even today remain in force in order to assure
a deeper appreciation of the liturgical norms;[^9] to establish certain norms by which those
earlier ones are explained and complemented; and also to set forth for
Bishops, as well as for Priests, Deacons and all the lay Christian
faithful, how each should carry them out in accordance with his own
responsibilities and the means at his disposal.

\[3.\] The norms contained in the present Instruction are to be
understood as pertaining to liturgical matters in the Roman Rite, and,
*mutatis mutandis*, in the other Rites of the Latin Church that are duly
acknowledged by law.

\[4.\] "Certainly the liturgical reform inaugurated by the Council has
greatly contributed to a more conscious, active and fruitful
participation in the Holy Sacrifice of the Altar on the part of the
faithful."[^10] Even so, "shadows are not
lacking".[^11] In this regard it is not
possible to be silent about the abuses, even quite grave ones, against
the nature of the Liturgy and the Sacraments as well as the tradition
and the authority of the Church, which in our day not infrequently
plague liturgical celebrations in one ecclesial environment or another.
In some places the perpetration of liturgical abuses has become almost
habitual, a fact which obviously cannot be allowed and must cease.

\[5.\] The observance of the norms published by the authority of the
Church requires conformity of thought and of word, of external action
and of the application of the heart. A merely external observation of
norms would obviously be contrary to the nature of the Sacred Liturgy,
in which Christ himself wishes to gather his Church, so that together
with himself she will be "one body and one spirit".[^12] For this reason, external action must be
illuminated by faith and charity, which unite us with Christ and with
one another and engender love for the poor and the abandoned. The
liturgical words and rites, moreover, are a faithful expression, matured
over the centuries, of the understanding of Christ, and they teach us to
think as he himself does;[^13] by conforming
our minds to these words, we raise our hearts to the Lord. All that is
said in this Instruction is directed toward such a conformity of our own
understanding with that of Christ, as expressed in the words and the
rites of the Liturgy.

\[6.\] For abuses "contribute to the obscuring of the Catholic faith and
doctrine concerning this wonderful sacrament".[^14] Thus, they also hinder the faithful from
"re-living in a certain way the experience of the two disciples of
Emmaus: 'and their eyes were opened, and they recognized him'".[^15] For in the presence of God's power and
divinity[^16] and the splendour of his
goodness, made manifest especially in the Sacrament of the Eucharist, it
is fitting that all the faithful should have and put into practice that
power of acknowledging God's majesty that they have received through the
saving Passion of the Only-Begotten Son.[^17]

\[7.\] Not infrequently, abuses are rooted in a false understanding of
liberty. Yet God has not granted us in Christ an illusory liberty by
which we may do what we wish, but a liberty by which we may do that
which is fitting and right.[^18] This is true
not only of precepts coming directly from God, but also of laws
promulgated by the Church, with appropriate regard for the nature of
each norm. For this reason, all should conform to the ordinances set
forth by legitimate ecclesiastical authority.

\[8.\] It is therefore to be noted with great sadness that "ecumenical
initiatives which are well-intentioned, nevertheless indulge at times in
Eucharistic practices contrary to the discipline by which the Church
expresses her faith". Yet the Eucharist "is too great a gift to tolerate
ambiguity or depreciation". It is therefore necessary that some things
be corrected or more clearly delineated so that in this respect as well
"the Eucharist will continue to shine forth in all its radiant mystery".[^19]

\[9.\] Finally, abuses are often based on ignorance, in that they
involve a rejection of those elements whose deeper meaning is not
understood and whose antiquity is not recognized. For "the liturgical
prayers, orations and songs are pervaded by the inspiration and impulse"
of the Sacred Scriptures themselves, "and it is from these that the
actions and signs receive their meaning".[^20]
As for the visible signs "which the Sacred Liturgy uses in order to
signify the invisible divine realities, they have been chosen by Christ
or by the Church".[^21] Finally, the structures
and forms of the sacred celebrations according to each of the Rites of
both East and West are in harmony with the practice of the universal
Church also as regards practices received universally from apostolic and
unbroken tradition,[^22] which it is the
Church's task to transmit faithfully and carefully to future
generations. All these things are wisely safeguarded and protected by
the liturgical norms.

\[10.\] The Church herself has no power over those things which were
established by Christ himself and which constitute an unchangeable part
of the Liturgy.[^23] Indeed, if the bond were
to be broken which the Sacraments have with Christ himself who
instituted them, and with the events of the Church's founding,[^24] it would not be beneficial to the faithful
but rather would do them grave harm. For the Sacred Liturgy is quite
intimately connected with principles of doctrine,[^25] so that the use of unapproved texts and
rites necessarily leads either to the attenuation or to the
disappearance of that necessary link between the *lex orandi* and the
*lex credendi.*[^26]


{{< pagebreak >}}


\[11.\] The Mystery of the Eucharist "is too great for anyone to permit
himself to treat it according to his own whim, so that its sacredness
and its universal ordering would be obscured".[^27] On the contrary, anyone who acts thus by
giving free reign to his own inclinations, even if he is a Priest,
injures the substantial unity of the Roman Rite, which ought to be
vigorously preserved,[^28] and becomes
responsible for actions that are in no way consistent with the hunger
and thirst for the living God that is experienced by the people today.
Nor do such actions serve authentic pastoral care or proper liturgical
renewal; instead, they deprive Christ's faithful of their patrimony and
their heritage. For arbitrary actions are not conducive to true renewal,[^29] but are detrimental to the right of
Christ's faithful to a liturgical celebration that is an expression of
the Church's life in accordance with her tradition and discipline. In
the end, they introduce elements of distortion and disharmony into the
very celebration of the Eucharist, which is oriented in its own lofty
way and by its very nature to signifying and wondrously bringing about
the communion of divine life and the unity of the People of God.[^30] The result is uncertainty in matters of
doctrine, perplexity and scandal on the part of the People of God, and,
almost as a necessary consequence, vigorous opposition, all of which
greatly confuse and sadden many of Christ's faithful in this age of ours
when Christian life is often particularly difficult on account of the
inroads of "secularization" as well.[^31]

\[12.\] On the contrary, it is the right of all of Christ's faithful
that the Liturgy, and in particular the celebration of Holy Mass, should
truly be as the Church wishes, according to her stipulations as
prescribed in the liturgical books and in the other laws and norms.
Likewise, the Catholic people have the right that the Sacrifice of the
Holy Mass should be celebrated for them in an integral manner, according
to the entire doctrine of the Church's Magisterium. Finally, it is the
Catholic community's right that the celebration of the Most Holy
Eucharist should be carried out for it in such a manner that it truly
stands out as a sacrament of unity, to the exclusion of all blemishes
and actions that might engender divisions and factions in the Church.[^32]

\[13.\] All of the norms and exhortations set forth in this Instruction
are connected, albeit in various ways, with the mission of the Church,
whose task it is to be vigilant concerning the correct and worthy
celebration of so great a mystery. The last chapter of the present
Instruction will treat of the varying degrees to which the individual
norms are bound up with the supreme norm of all ecclesiastical law,
namely concern for the salvation of souls.[^33]

{{< pagebreak >}}

# Chapter I -- **THE REGULATION OF THE SACRED LITURGY**

\[14.\] "The regulation of the Sacred Liturgy depends solely on the
authority of the Church, which rests specifically with the Apostolic See
and, according to the norms of law, with the Bishop.[^34]

\[15.\] The Roman Pontiff, "the Vicar of Christ and the Pastor of the
universal Church on earth, by virtue of his supreme office enjoys full,
immediate and universal ordinary power, which he may always freely
exercise"[^35] , also by means of communication
with the pastors and with the members of the flock.

\[16.\] "It pertains to the Apostolic See to regulate the Sacred Liturgy
of the universal Church, to publish the liturgical books and to grant
the *recognitio* for their translation into vernacular languages, as
well as to ensure that the liturgical regulations, especially those
governing the celebration of the most exalted celebration of the
Sacrifice of the Mass, are everywhere faithfully observed".[^36]

\[17.\] "The Congregation for Divine Worship and the Discipline of the
Sacraments attends to those matters that pertain to the Apostolic See as
regards the regulation and promotion of the Sacred Liturgy, and
especially the Sacraments, with due regard for the competence of the
Congregation for the Doctrine of the Faith. It fosters and enforces
sacramental discipline, especially as regards their validity and their
licit celebration". Finally, it "carefully seeks to ensure that the
liturgical regulations are observed with precision, and that abuses are
prevented or eliminated whenever they are detected"[^37] . In this regard, according to the
tradition of the universal Church, pre-eminent solicitude is accorded
the celebration of Holy Mass, and also to the worship that is given to
the Holy Eucharist even outside Mass.

\[18.\] Christ's faithful have the right that ecclesiastical authority
should fully and efficaciously regulate the Sacred Liturgy lest it
should ever seem to be "anyone's private property, whether of the
celebrant or of the community in which the mysteries are celebrated"[^38] .

## **1. The Diocesan Bishop, High Priest of his Flock**

\[19.\] The diocesan Bishop, the first steward of the mysteries of God
in the particular Church entrusted to him, is the moderator, promoter
and guardian of her whole liturgical life.[^39]


{{< pagebreak >}}



For "the Bishop, endowed with the fullness of the Sacrament of Order, is
'the steward of the grace of the high Priesthood',[^40] especially in the Eucharist which he
either himself offers or causes to be offered,[^41] by which the Church continually lives and
grows".[^42]

\[20.\] Indeed, the pre-eminent manifestation of the Church is found
whenever the rites of Mass are celebrated, especially in the Cathedral
Church, "with the full and active participation of the entire holy
People of God, joined in one act of prayer, at one altar at which the
Bishop presides", surrounded by his presbyterate with the Deacons and
ministers.[^43] Furthermore, "every lawful
celebration of the Eucharist is directed by the Bishop, to whom is
entrusted the office of presenting the worship of the Christian religion
to the Divine Majesty and ordering it according to the precepts of the
Lord and the laws of the Church, further specified by his own particular
judgement for the Diocese".[^44]

\[21.\] It pertains to the diocesan Bishop, then, "within the limits of
his competence, to set forth liturgical norms in his Diocese, by which
all are bound".[^45] Still, the Bishop must
take care not to allow the removal of that liberty foreseen by the norms
of the liturgical books so that the celebration may be adapted in an
intelligent manner to the Church building, or to the group of the
faithful who are present, or to particular pastoral circumstances in
such a way that the universal sacred rite is truly accommodated to human
understanding.[^46]

\[22.\] The Bishop governs the particular Church entrusted to him,[^47] and it is his task to regulate, to direct,
to encourage, and sometimes also to reprove;[^48] this is a sacred task that he has received
through episcopal Ordination,[^49] which he
fulfills in order to build up his flock in truth and holiness.[^50] He should elucidate the inherent meaning
of the rites and the liturgical texts, and nourish the spirit of the
Liturgy in the Priests, Deacons and lay faithful[^51] so that they are all led to the active and
fruitful celebration of the Eucharist,[^52] and
in like manner he should take care to ensure that the whole body of the
Church is able to grow in the same understanding, in the unity of
charity, in the diocese, in the nation and in the world.[^53]

\[23.\] The faithful "should cling to the Bishop as the Church does to
Jesus Christ, and as Jesus Christ does to the Father, so that all may be
in harmonious unity, and that they may abound to the glory of God".[^54] All, including members of Institutes of
consecrated life and Societies of apostolic life as well as those of all
ecclesial associations and movements of any kind, are subject to the
authority of the diocesan Bishop in all liturgical matters,[^55] apart from rights that have been
legitimately conceded. To the diocesan Bishop therefore falls the right
and duty of overseeing and attending to Churches and oratories in his
territory in regard to liturgical matters, and this is true also of
those which are founded by members of the above-mentioned institutes or
under their direction, provided that the faithful are accustomed to
frequent them.[^56]

\[24.\] It is the right of the Christian people themselves that their
diocesan Bishop should take care to prevent the occurrence of abuses in
ecclesiastical discipline, especially as regards the ministry of the
word, the celebration of the sacraments and sacramentals, the worship of
God and devotion to the Saints.[^57]

\[25.\] Commissions as well as councils or committees established by the
Bishop to handle "the promotion of the Liturgy, sacred music and art in
his diocese" should act in accordance with the intentions and the norms
of the Bishop; they must rely on his authority and his approval so that
they may carry out their office in a suitable manner[^58] and so that the effective governance of
the Bishop in his diocese will be preserved. As regards all these sorts
of bodies and other entities and all undertakings in liturgical matters,
there has long been the need for the Bishops to consider whether their
working has been fruitful thus far,[^59] and to
consider carefully which changes or improvements should be made in their
composition and activity[^60] so that they
might find new vigour. It should be borne in mind that the experts are
to be chosen from among those whose soundness in the Catholic faith and
knowledge of theological and cultural matters are evident.

## **2. The Conference of Bishops**

\[26.\] The same holds for those commissions of this kind which have
been established by the Conference of Bishops in accordance with the
will of the Council,[^61] commissions whose
members consist of Bishops who are clearly distinguished from their
expert helpers. Where the number of members of a Conference of Bishops
is not sufficient for the effective establishment of a liturgical
commission from among their own number, then a council or group of
experts should be named, always under the presidency of a Bishop, which
is to fulfill the same role insofar as possible, albeit without the name
of "liturgical commission".

\[27.\] As early as the year 1970, the Apostolic See announced the
cessation of all experimentation as regards the celebration of Holy Mass[^62] and reiterated the same in 1988.[^63] Accordingly, individual Bishops and their
Conferences do not have the faculty to permit experimentation with
liturgical texts or the other matters that are prescribed in the
liturgical books. In order to carry out experimentation of this kind in
the future, the permission of the Congregation for Divine Worship and
the Discipline of the Sacraments is required. It must be in writing, and
it is to be requested by the Conference of Bishops. In fact, it will not
be granted without serious reason. As regards projects of inculturation
in liturgical matters, the particular norms that have been established
are strictly and comprehensively to be observed.[^64]

\[28.\] All liturgical norms that a Conference of Bishops will have
established for its territory in accordance with the law are to be
submitted to the Congregation for Divine Worship and the Discipline of
the Sacraments for the *recognitio*, without which they lack any binding
force.[^65]

## **3. Priests**

\[29.\] Priests, as capable, prudent and indispensable co-workers of the
order of Bishops,[^66] called to the service of
the People of God, constitute one presbyterate with their Bishop,[^67] though charged with differing offices. "In
each local congregation of the faithful, in a certain way, they make
present the Bishop with whom they are associated in trust and in
generosity of heart; according to their rank, they take upon themselves
his duties and his solicitude, and they carry these out in their daily
work". And "because of this participation in the Priesthood and mission,
Priests should recognize the Bishop as truly their father and obey him
reverently"[^68] . Furthermore, "ever intent
upon the good of God's children, they should seek to contribute to the
pastoral mission of the whole diocese, and indeed of the whole Church".[^69]

\[30.\] The office "that belongs to Priests in particular in the
celebration of the Eucharist" is a great one, "for it is their
responsibility to preside at the Eucharist *in persona Christi* and to
provide a witness to and a service of communion not only for the
community directly taking part in the celebration, but also for the
universal Church, which is always brought into play within the context
of the Eucharist. It must be lamented that, especially in the years
following the post-Conciliar liturgical reform, as a result of a
misguided sense of creativity and adaptation, there have been a number
of abuses which have been a source of suffering for many".[^70]

\[31.\] In keeping with the solemn promises that they have made in the
rite of Sacred Ordination and renewed each year in the Mass of the
Chrism, let Priests celebrate "devoutly and faithfully the mysteries of
Christ for the praise of God and the sanctification of the Christian
people, according to the tradition of the Church, especially in the
Eucharistic Sacrifice and in the Sacrament of Reconciliation".[^71]


{{< pagebreak >}}



They ought not to detract from the
profound meaning of their own ministry by corrupting the liturgical
celebration either through alteration or omission, or through arbitrary
additions.[^72] For as St. Ambrose said, "It is
not in herself . . . but in us that the Church is injured. Let us take
care so that our own failure may not cause injury to the Church".[^73] Let the Church of God not be injured,
then, by Priests who have so solemnly dedicated themselves to the
ministry. Indeed, under the Bishop's authority let them faithfully seek
to prevent others as well from committing this type of distortion.

\[32.\] "Let the Parish Priest strive so that the Most Holy Eucharist
will be the center of the parish congregation of the faithful; let him
work to ensure that Christ's faithful are nourished through the devout
celebration of the Sacraments, and in particular, that they frequently
approach the Most Holy Eucharist and the Sacrament of Penance; let him
strive, furthermore, to ensure that the faithful are encouraged to offer
prayers in their families as well, and to participate consciously and
actively in the Sacred Liturgy, which the Parish Priest, under the
authority of the diocesan Bishop, is bound to regulate and supervise in
his parish lest abuses occur".[^74] Although it
is appropriate that he should be assisted in the effective preparation
of the liturgical celebrations by various members of Christ's faithful,
he nevertheless must not cede to them in any way those things that are
proper to his own office.

\[33.\] Finally, all "Priests should go to the trouble of properly
cultivating their liturgical knowledge and ability, so that through
their liturgical ministry, God the Father, Son and Holy Spirit will be
praised in an ever more excellent manner by the Christian communities
entrusted to them".[^75] Above all, let them be
filled with that wonder and amazement that the Paschal Mystery, in being
celebrated, instills in the hearts of the faithful.[^76]

{{< pagebreak >}}


## **4. Deacons**

\[34.\] Deacons "upon whom hands are imposed not for the Priesthood but
for the ministry",[^77] as men of good repute,[^78] must act in such a way that with the help
of God they may be recognized as the true disciples[^79] of him "who came not to be served but to
serve"[^80] , and who was among his disciples
"as one who serves".[^81] Strengthened by the
gift of the Holy Spirit through the laying on of hands, they are in
service to the People of God, in communion with the Bishop and his
presbyterate.[^82] They should therefore
consider the Bishop as a father, and give assistance to him and to the
Priests "in the ministry of the word, of the altar, and of charity".[^83]

\[35.\] Let them never fail, "as the Apostle says, to hold the mystery
of faith with a clear conscience,[^84] and to
proclaim this faith by word and deed according to the Gospel and the
tradition of the Church",[^85] in wholehearted,
faithful and humble service to the Sacred Liturgy as the source and
summit of ecclesial life, "so that all, made children of God through
faith and Baptism, may come together as one, praising God in the midst
of the Church, to participate in the Sacrifice and to eat the Lord's
Supper".[^86] Let all Deacons, then, do their
part so that the Sacred Liturgy will be celebrated according to the
norms of the duly approved liturgical books.


{{< pagebreak >}}

# Chapter II -- **THE PARTICIPATION OF THE LAY CHRISTIAN FAITHFUL IN THE EUCHARISTIC CELEBRATION**

## **1. Active and Conscious Participation**

\[36.\] The celebration of the Mass, as the action of Christ and of the
Church, is the center of the whole Christian life for the universal as
well as the particular Church, and also for the individual faithful,[^87] who are involved "in differing ways
according to the diversity of orders, ministries, and active
participation.[^88] In this way the Christian
people, "a chosen race, a royal priesthood, a holy people, a people God
has made his own",[^89] manifests its coherent
and hierarchical ordering".[^90] "For the
common priesthood of the faithful and the ministerial or hierarchical
Priesthood, though they differ in essence and not only in degree, are
ordered to one another, for both partake, each in its own way, of the
one Priesthood of Christ".[^91]

\[37.\] All of Christ's faithful, freed from their sins and incorporated
into the Church through Baptism, are deputed by means of a sacramental
character for the worship of the Christian religion,[^92] so that by virtue of their royal
priesthood,[^93] persevering in prayer and
praising God,[^94] they may offer themselves as
a living and holy sacrifice pleasing to God and attested to others by
their works,[^95] giving witness to Christ
throughout the earth and providing an answer to those who ask concerning
their hope of eternal life that is in them.[^96] Thus the participation of the lay faithful
too in the Eucharist and in the other celebrations of the Church's rites
cannot be equated with mere presence, and still less with a passive one,
but is rather to be regarded as a true exercise of faith and of the
baptismal dignity.

\[38.\] The constant teaching of the Church on the nature of the
Eucharist not only as a meal, but also and pre-eminently as a Sacrifice,
is therefore rightly understood to be one of the principal keys to the
full participation of all the faithful in so great a Sacrament.[^97] For when "stripped of its sacrificial
meaning, the mystery is understood as if its meaning and importance were
simply that of a fraternal banquet".[^98]

\[39.\] For promoting and elucidating active participation, the recent
renewal of the liturgical books according to the mind of the Council
fostered acclamations of the people, responses, psalmody, antiphons, and
canticles, as well as actions or movements and gestures, and called for
sacred silence to be maintained at the proper times, while providing
rubrics for the parts of the faithful as well.[^99] In addition, ample flexibility is given
for appropriate creativity aimed at allowing each celebration to be
adapted to the needs of the participants, to their comprehension, their
interior preparation and their gifts, according to the established
liturgical norms. In the songs, the melodies, the choice of prayers and
readings, the giving of the homily, the preparation of the prayer of the
faithful, the occasional explanatory remarks, and the decoration of the
Church building according to the various seasons, there is ample
possibility for introducing into each celebration a certain variety by
which the riches of the liturgical tradition will also be more clearly
evident, and so, in keeping with pastoral requirements, the celebration
will be carefully imbued with those particular features that will foster
the recollection of the participants. Still, it should be remembered
that the power of the liturgical celebrations does not consist in
frequently altering the rites, but in probing more deeply the word of
God and the mystery being celebrated.[^100]

\[40.\] Nevertheless, from the fact that the liturgical celebration
obviously entails activity, it does not follow that everyone must
necessarily have something concrete to do beyond the actions and
gestures, as if a certain specific liturgical ministry must necessarily
be given to the individuals to be carried out by them. Instead,
catechetical instruction should strive diligently to correct those
widespread superficial notions and practices often seen in recent years
in this regard, and ever to instill anew in all of Christ's faithful
that sense of deep wonder before the greatness of the mystery of faith
that is the Eucharist, in whose celebration the Church is forever
passing from what is obsolete into newness of life: "*in novitatem a
vetustate*".[^101] For in the celebration of
the Eucharist, as in the whole Christian life which draws its power from
it and leads toward it, the Church, after the manner of Saint Thomas the
Apostle, prostrates herself in adoration before the Lord who was
crucified, suffered and died, was buried and arose, and perpetually
exclaims to him who is clothed in the fullness of his divine splendour:
"My Lord and my God!"[^102]

\[41.\] For encouraging, promoting and nourishing this interior
understanding of liturgical participation, the continuous and widespread
celebration of the Liturgy of the Hours, the use of the sacramentals and
exercises of Christian popular piety are extremely helpful. These latter
exercises -- which "while not belonging to the Liturgy in the strict
sense, possess nonetheless a particular importance and dignity" -- are
to be regarded as having a certain connection with the liturgical
context, especially when they have been lauded and attested by the
Magisterium itself,[^103] as is the case
especially of the Marian Rosary.[^104]
Furthermore, since these practices of piety lead the Christian people
both to the reception of the sacraments -- especially the Eucharist --
and "to meditation on the mysteries of our Redemption and the imitation
of the excellent heavenly examples of the Saints, they are therefore not
without salutary effects for our participation in liturgical worship ".[^105]

\[42.\] It must be acknowledged that the Church has not come together by
human volition; rather, she has been called together by God in the Holy
Spirit, and she responds through faith to his free calling (thus the
word *ekklesia* is related to *klesis*, or "calling").[^106] Nor is the Eucharistic Sacrifice to be
considered a "concelebration", in the univocal sense, of the Priest
along with the people who are present.[^107]
On the contrary, the Eucharist celebrated by the Priests "is a gift
which radically transcends the power of the community. . . . The
community that gathers for the celebration of the Eucharist absolutely
requires an ordained Priest, who presides over it so that it may truly
be a eucharistic convocation. On the other hand, the community is by
itself incapable of providing an ordained minister".[^108] There is pressing need of a concerted
will to avoid all ambiguity in this matter and to remedy the
difficulties of recent years. Accordingly, terms such as "celebrating
community" or "celebrating assembly" (in other languages "asamblea
celebrante", "assemblée célébrante", assemblea celebrante") and similar
terms should not be used injudiciously.

## **2. The Ministries of the Lay Christian Faithful in the Celebration of Holy Mass**

\[43.\] For the good of the community and of the whole Church of God,
some of the lay faithful according to tradition have rightly and
laudably exercised ministries in the celebration of the Sacred Liturgy.[^109] It is appropriate that a number of
persons distribute among themselves and exercise various ministries or
different parts of the same ministry.[^110]

\[44.\] Apart from the duly instituted ministries of acolyte and lector,[^111] the most important of these ministries
are those of acolyte[^112] and lector[^113] by temporary deputation. In addition to
these are the other functions that are described in the Roman Missal,[^114] as well as the functions of preparing
the hosts, washing the liturgical linens, and the like. All, "whether
ordained ministers or lay faithful, in exercising their own office or
ministry should do exclusively and fully that which pertains to them".[^115] In the liturgical celebration itself as
well as in its preparation, they should do what is necessary so that the
Church's Liturgy will be carried out worthily and appropriately.

{{< pagebreak >}}


\[45.\] To be avoided is the danger of obscuring the complementary
relationship between the action of clerics and that of laypersons, in
such a way that the ministry of laypersons undergoes what might be
called a certain "clericalization", while the sacred ministers
inappropriately assume those things that are proper to the life and
activity of the lay faithful.[^116]

\[46.\] The lay Christian faithful called to give assistance at
liturgical celebrations should be well instructed and must be those
whose Christian life, morals and fidelity to the Church's Magisterium
recommend them. It is fitting that such a one should have received a
liturgical formation in accordance with his or her age, condition, state
of life, and religious culture.[^117] No one
should be selected whose designation could cause consternation for the
faithful.[^118]

\[47.\] It is altogether laudable to maintain the noble custom by which
boys or youths, customarily termed servers, provide service of the altar
after the manner of acolytes, and receive catechesis regarding their
function in accordance with their power of comprehension.[^119] Nor should it be forgotten that a great
number of sacred ministers over the course of the centuries have come
from among boys such as these.[^120]
Associations for them, including also the participation and assistance
of their parents, should be established or promoted, and in such a way
greater pastoral care will be provided for the ministers. Whenever such
associations are international in nature, it pertains to the competence
of the Congregation for Divine Worship and the Discipline of the
Sacraments to establish them or to approve and revise their statutes.[^121] Girls or women may also be admitted to
this service of the altar, at the discretion of the diocesan Bishop and
in observance of the established norms.[^122]\

{{< pagebreak >}}

# Chapter III -- **THE PROPER CELEBRATION OF MASS**

## **1. The Matter of the Most Holy Eucharist**

\[48.\] The bread used in the celebration of the Most Holy Eucharistic
Sacrifice must be unleavened, purely of wheat, and recently made so that
there is no danger of decomposition.[^123] It
follows therefore that bread made from another substance, even if it is
grain, or if it is mixed with another substance different from wheat to
such an extent that it would not commonly be considered wheat bread,
does not constitute valid matter for confecting the Sacrifice and the
Eucharistic Sacrament.[^124] It is a grave
abuse to introduce other substances, such as fruit or sugar or honey,
into the bread for confecting the Eucharist. Hosts should obviously be
made by those who are not only distinguished by their integrity, but
also skilled in making them and furnished with suitable tools.[^125]

\[49.\] By reason of the sign, it is appropriate that at least some
parts of the Eucharistic Bread coming from the fraction should be
distributed to at least some of the faithful in Communion. "Small hosts
are, however, in no way ruled out when the number of those receiving
Holy Communion or other pastoral needs require it",[^126] and indeed small hosts requiring no
further fraction ought customarily to be used for the most part.

\[50.\] The wine that is used in the most sacred celebration of the
Eucharistic Sacrifice must be natural, from the fruit of the grape, pure
and incorrupt, not mixed with other substances.[^127] During the celebration itself, a small
quantity of water is to be mixed with it. Great care should be taken so
that the wine intended for the celebration of the Eucharist is well
conserved and has not soured.[^128] It is
altogether forbidden to use wine of doubtful authenticity or provenance,
for the Church requires certainty regarding the conditions necessary for
the validity of the sacraments. Nor are other drinks of any kind to be
admitted for any reason, as they do not constitute valid matter.

## **2. The Eucharistic Prayer**

\[51.\] Only those Eucharistic Prayers are to be used which are found in
the Roman Missal or are legitimately approved by the Apostolic See, and
according to the manner and the terms set forth by it. "It is not to be
tolerated that some Priests take upon themselves the right to compose
their own Eucharistic Prayers"[^129] or to
change the same texts approved by the Church, or to introduce others
composed by private individuals.[^130]

\[52.\] The proclamation of the Eucharistic Prayer, which by its very
nature is the climax of the whole celebration, is proper to the Priest
by virtue of his Ordination. It is therefore an abuse to proffer it in
such a way that some parts of the Eucharistic Prayer are recited by a
Deacon, a lay minister, or by an individual member of the faithful, or
by all members of the faithful together. The Eucharistic Prayer, then,
is to be recited by the Priest alone in full.[^131]

\[53.\] While the Priest proclaims the Eucharistic Prayer "there should
be no other prayers or singing, and the organ or other musical
instruments should be silent",[^132] except
for the people's acclamations that have been duly approved, as described
below.

\[54.\] The people, however, are always involved actively and never
merely passively: for they "silently join themselves with the Priest in
faith, as well as in their interventions during the course of the
Eucharistic Prayer as prescribed, namely in the responses in the Preface
dialogue, the *Sanctus*, the acclamation after the consecration and the
"*Amen*" after the final doxology, and in other acclamations approved by
the Conference of Bishops with the *recognitio* of the Holy See".[^133]

\[55.\] In some places there has existed an abuse by which the Priest
breaks the host at the time of the consecration in the Holy Mass. This
abuse is contrary to the tradition of the Church. It is reprobated and
is to be corrected with haste.

\[56.\] The mention of the name of the Supreme Pontiff and the diocesan
Bishop in the Eucharistic Prayer is not to be omitted, since this is a
most ancient tradition to be maintained, and a manifestation of
ecclesial communion. For "the coming together of the eucharistic
community is at the same time a joining in union with its own Bishop and
with the Roman Pontiff".[^134]

## **3. The Other Parts of the Mass**

\[57.\] It is the right of the community of Christ's faithful that
especially in the Sunday celebration there should customarily be true
and suitable sacred music, and that there should always be an altar,
vestments and sacred linens that are dignified, proper, and clean, in
accordance with the norms.

\[58.\] All of Christ's faithful likewise have the right to a
celebration of the Eucharist that has been so carefully prepared in all
its parts that the word of God is properly and efficaciously proclaimed
and explained in it; that the faculty for selecting the liturgical texts
and rites is carried out with care according to the norms; and that
their faith is duly safeguarded and nourished by the words that are sung
in the celebration of the Liturgy.

\[59.\] The reprobated practice by which Priests, Deacons or the
faithful here and there alter or vary at will the texts of the Sacred
Liturgy that they are charged to pronounce, must cease. For in doing
thus, they render the celebration of the Sacred Liturgy unstable, and
not infrequently distort the authentic meaning of the Liturgy.

\[60.\] In the celebration of Mass, the Liturgy of the Word and the
Liturgy of the Eucharist are intimately connected to one another, and
form one single act of worship. For this reason it is not licit to
separate one of these parts from the other and celebrate them at
different times or places.[^135] Nor is it
licit to carry out the individual parts of Holy Mass at different times
of the same day.

\[61.\] In selecting the biblical readings for proclamation in the
celebration of Mass, the norms found in the liturgical books are to be
followed,[^136] so that indeed "a richer
table of the word of God will be prepared for the faithful, and the
biblical treasures opened up for them".[^137]

\[62.\] It is also illicit to omit or to substitute the prescribed
biblical readings on one's own initiative, and especially "to substitute
other, non-biblical texts for the readings and responsorial Psalm, which
contain the word of God".[^138]

\[63.\] "Within the celebration of the Sacred Liturgy, the reading of
the Gospel, which is "the high point of the Liturgy of the Word",[^139] is reserved by the Church's tradition
to an ordained minister.[^140] Thus it is not
permitted for a layperson, even a religious, to proclaim the Gospel
reading in the celebration of Holy Mass, nor in other cases in which the
norms do not explicitly permit it.[^141]

\[64.\] The homily, which is given in the course of the celebration of
Holy Mass and is a part of the Liturgy itself,[^142] "should ordinarily be given by the
Priest celebrant himself. He may entrust it to a concelebrating Priest
or occasionally, according to circumstances, to a Deacon, but never to a
layperson.[^143] In particular cases and for
a just cause, the homily may even be given by a Bishop or a Priest who
is present at the celebration but cannot concelebrate".[^144]

\[65.\] It should be borne in mind that any previous norm that may have
admitted non-ordained faithful to give the homily during the eucharistic
celebration is to be considered abrogated by the norm of canon 767 §1.[^145] This practice is reprobated, so that it
cannot be permitted to attain the force of custom.

\[66.\] The prohibition of the admission of laypersons to preach within
the Mass applies also to seminarians, students of theological
disciplines, and those who have assumed the function of those known as
"pastoral assistants"; nor is there to be any exception for any other
kind of layperson, or group, or community, or association.[^146]

\[67.\] Particular care is to be taken so that the homily is firmly
based upon the mysteries of salvation, expounding the mysteries of the
Faith and the norms of Christian life from the biblical readings and
liturgical texts throughout the course of the liturgical year and
providing commentary on the texts of the Ordinary or the Proper of the
Mass, or of some other rite of the Church.[^147] It is clear that all interpretations of
Sacred Scripture are to be referred back to Christ himself as the one
upon whom the entire economy of salvation hinges, though this should be
done in light of the specific context of the liturgical celebration. In
the homily to be given, care is to be taken so that the light of Christ
may shine upon life's events. Even so, this is to be done so as not to
obscure the true and unadulterated word of God: for instance, treating
only of politics or profane subjects, or drawing upon notions derived
from contemporary pseudo-religious currents as a source.[^148]

\[68.\] The diocesan Bishop must diligently oversee the preaching of the
homily,[^149] also publishing norms and
distributing guidelines and auxiliary tools to the sacred ministers, and
promoting meetings and other projects for this purpose so that they may
have the opportunity to consider the nature of the homily more precisely
and find help in its preparation.

\[69.\] In Holy Mass as well as in other celebrations of the Sacred
Liturgy, no Creed or Profession of Faith is to be introduced which is
not found in the duly approved liturgical books.

\[70.\] The offerings that Christ's faithful are accustomed to present
for the Liturgy of the Eucharist in Holy Mass are not necessarily
limited to bread and wine for the eucharistic celebration, but may also
include gifts given by the faithful in the form of money or other things
for the sake of charity toward the poor. Moreover, external gifts must
always be a visible expression of that true gift that God expects from
us: a contrite heart, the love of God and neighbour by which we are
conformed to the sacrifice of Christ, who offered himself for us. For in
the Eucharist, there shines forth most brilliantly that mystery of
charity that Jesus brought forth at the Last Supper by washing the feet
of the disciples. In order to preserve the dignity of the Sacred
Liturgy, in any event, the external offerings should be brought forward
in an appropriate manner. Money, therefore, just as other contributions
for the poor, should be placed in an appropriate place which should be
away from the eucharistic table.[^150] Except
for money and occasionally a minimal symbolic portion of other gifts, it
is preferable that such offerings be made outside the celebration of
Mass.

\[71.\] The practice of the Roman Rite is to be maintained according to
which the peace is extended shortly before Holy Communion. For according
to the tradition of the Roman Rite, this practice does not have the
connotation either of reconciliation or of a remission of sins, but
instead signifies peace, communion and charity before the reception of
the Most Holy Eucharist.[^151] It is rather
the Penitential Act to be carried out at the beginning of Mass
(especially in its first form) which has the character of reconciliation
among brothers and sisters.

\[72.\] It is appropriate "that each one give the sign of peace only to
those who are nearest and in a sober manner". "The Priest may give the
sign of peace to the ministers but always remains within the sanctuary,
so as not to disturb the celebration. He does likewise if for a just
reason he wishes to extend the sign of peace to some few of the
faithful". "As regards the sign to be exchanged, the manner is to be
established by the Conference of Bishops in accordance with the
dispositions and customs of the people", and their acts are subject to
the *recognitio* of the Apostolic See.[^152]

\[73.\] In the celebration of Holy Mass the breaking of the Eucharistic
Bread -- done only by the Priest celebrant, if necessary with the help
of a Deacon or of a concelebrant -- begins after the exchange of peace,
while the *Agnus Dei* is being recited. For the gesture of breaking
bread "carried out by Christ at the Last Supper, which in apostolic
times gave the whole eucharistic action its name, signifies that the
faithful, though they are many, are made one Body in the communion of
the one Bread of Life who is Christ, who died and rose for the world's
salvation" (cf. 1 Cor 10,17).[^153] For this
reason the rite must be carried out with great reverence.[^154] Even so, it should be brief. The abuse
that has prevailed in some places, by which this rite is unnecessarily
prolonged and given undue emphasis, with laypersons also helping in
contradiction to the norms, should be corrected with all haste.[^155]

\[74.\] If the need arises for the gathered faithful to be given
instruction or testimony by a layperson in a Church concerning the
Christian life, it is altogether preferable that this be done outside
Mass. Nevertheless, for serious reasons it is permissible that this type
of instruction or testimony be given after the Priest has proclaimed the
Prayer after Communion. This should not become a regular practice,
however. Furthermore, these instructions and testimony should not be of
such a nature that they could be confused with the homily,[^156] nor is it permissible to dispense with
the homily on their account.

{{< pagebreak >}}


## **4. On the Joining of Various Rites with the Celebration of Mass**

\[75.\] On account of the theological significance inherent in a
particular rite and the Eucharistic Celebration, the liturgical books
sometimes prescribe or permit the celebration of Holy Mass to be joined
with another rite, especially one of those pertaining to the Sacraments.[^157] The Church does not permit such a
conjoining in other cases, however, especially when it is a question of
trivial matters.

\[76.\] Furthermore, according to a most ancient tradition of the Roman
Church, it is not permissible to unite the Sacrament of Penance to the
Mass in such a way that they become a single liturgical celebration.
This does not exclude, however, that Priests other than those
celebrating or concelebrating the Mass might hear the confessions of the
faithful who so desire, even in the same place where Mass is being
celebrated, in order to meet the needs of those faithful.[^158] This should nevertheless be done in an
appropriate manner.

\[77.\] The celebration of Holy Mass is not to be inserted in any way
into the setting of a common meal, nor joined with this kind of banquet.
Mass is not to be celebrated without grave necessity on a dinner table[^159] nor in a dining room or banquet hall,
nor in a room where food is present, nor in a place where the
participants during the celebration itself are seated at tables. If out
of grave necessity Mass must be celebrated in the same place where
eating will later take place, there is to be a clear interval of time
between the conclusion of Mass and the beginning of the meal, and
ordinary food is not to be set before the faithful during the
celebration of Mass.

\[78.\] It is not permissible to link the celebration of Mass to
political or secular events, nor to situations that are not fully
consistent with the Magisterium of the Catholic Church. Furthermore, it
is altogether to be avoided that the celebration of Mass should be
carried out merely out of a desire for show, or in the manner of other
ceremonies including profane ones, lest the Eucharist should be emptied
of its authentic meaning.

\[79.\] Finally, it is strictly to be considered an abuse to introduce
into the celebration of Holy Mass elements that are contrary to the
prescriptions of the liturgical books and taken from the rites of other
religions.

{{< pagebreak >}}

# Chapter IV -- **HOLY COMMUNION**

## **1. Dispositions for the Reception of Holy Communion**

\[80.\] The Eucharist is to be offered to the faithful, among other
reasons, "as an antidote, by which we are freed from daily faults and
preserved from mortal sins",[^160] as is
brought to light in various parts of the Mass. As for the Penitential
Act placed at the beginning of Mass, it has the purpose of preparing all
to be ready to celebrate the sacred mysteries;[^161] even so, "it lacks the efficacy of the
Sacrament of Penance",[^162] and cannot be
regarded as a substitute for the Sacrament of Penance in remission of
graver sins. Pastors of souls should take care to ensure diligent
catechetical instruction, so that Christian doctrine is handed on to
Christ's faithful in this matter.

\[81.\] The Church's custom shows that it is necessary for each person
to examine himself at depth,[^163] and that
anyone who is conscious of grave sin should not celebrate or receive the
Body of the Lord without prior sacramental confession, except for grave
reason when the possibility of confession is lacking; in this case he
will remember that he is bound by the obligation of making an act of
perfect contrition, which includes the intention to confess as soon as
possible".[^164]

\[82.\] Moreover, "the Church has drawn up norms aimed at fostering the
frequent and fruitful access of the faithful to the Eucharistic table
and at determining the objective conditions under which Communion may
not be given".[^165]

\[83.\] It is certainly best that all who are participating in the
celebration of Holy Mass with the necessary dispositions should receive
Communion. Nevertheless, it sometimes happens that Christ's faithful
approach the altar as a group indiscriminately. It pertains to the
Pastors prudently and firmly to correct such an abuse.

\[84.\] Furthermore when Holy Mass is celebrated for a large crowd - for
example, in large cities - care should be taken lest out of ignorance
non-Catholics or even non-Christians come forward for Holy Communion,
without taking into account the Church's Magisterium in matters
pertaining to doctrine and discipline. It is the duty of Pastors at an
opportune moment to inform those present of the authenticity and the
discipline that are strictly to be observed.

\[85.\] Catholic ministers licitly administer the Sacraments only to the
Catholic faithful, who likewise receive them licitly only from Catholic
ministers, except for those situations for which provision is made in
can. 844 §§ 2,3, and 4, and can. 861 § 2.[^166] 

{{< pagebreak >}}

In addition, the conditions comprising
can. 844 § 4, from which no dispensation can be given,[^167] cannot be separated; thus, it is
necessary that all of these conditions be present together.

\[86.\] The faithful should be led insistently to the practice whereby
they approach the Sacrament of Penance outside the celebration of Mass,
especially at the scheduled times, so that the Sacrament may be
administered in a manner that is tranquil and truly beneficial to them,
so as not to be prevented from active participation at Mass. Those who
are accustomed to receiving Communion often or daily should be
instructed that they should approach the Sacrament of Penance at
appropriate intervals, in accordance with the condition of each.[^168]

\[87.\] The First Communion of children must always be preceded by
sacramental confession and absolution.[^169]
Moreover First Communion should always be administered by a Priest and
never outside the celebration of Mass. Apart from exceptional cases, it
is not particularly appropriate for First Communion to be administered
on Holy Thursday of the Lord's Supper. Another day should be chosen
instead, such as a Sunday between the Second and the Sixth Sunday of
Easter, or the Solemnity of the Body and Blood of Christ, or the Sundays
of Ordinary Time, since Sunday is rightly regarded as the day of the
Eucharist.[^170] "Children who have not
attained the age of reason, or those whom" the Parish Priest "has
determined to be insufficiently prepared" should not come forward to
receive the Holy Eucharist.[^171] Where it
happens, however, that a child who is exceptionally mature for his age
is judged to be ready for receiving the Sacrament, the child must not be
denied First Communion provided he has received sufficient instruction.

## **2. The distribution of Holy Communion**

\[88.\] The faithful should normally receive sacramental Communion of
the Eucharist during Mass itself, at the moment laid down by the rite of
celebration, that is to say, just after the Priest celebrant's
Communion.[^172] It is the Priest celebrant's
responsibility to minister Communion, perhaps assisted by other Priests
or Deacons; and he should not resume the Mass until after the Communion
of the faithful is concluded. Only when there is a necessity may
extraordinary ministers assist the Priest celebrant in accordance with
the norm of law.[^173]

\[89.\] "So that even by means of the signs Communion may stand out more
clearly as a participation in the Sacrifice being celebrated",[^174] it
is preferable that the faithful be able to 

{{< pagebreak >}}


receive hosts consecrated in the same Mass.[^175]

\[90.\] "The faithful should receive Communion kneeling or standing, as
the Conference of Bishops will have determined", with its acts having
received the *recognitio* of the Apostolic See. "However, if they
receive Communion standing, it is recommended that they give due
reverence before the reception of the Sacrament, as set forth in the
same norms".[^176]

\[91.\] In distributing Holy Communion it is to be remembered that
"sacred ministers may not deny the sacraments to those who seek them in
a reasonable manner, are rightly disposed, and are not prohibited by law
from receiving them".[^177] Hence any
baptized Catholic who is not prevented by law must be admitted to Holy
Communion. Therefore, it is not licit to deny Holy Communion to any of
Christ's faithful solely on the grounds, for example, that the person
wishes to receive the Eucharist kneeling or standing.

\[92.\] Although each of the faithful always has the right to receive
Holy Communion on the tongue, at his choice,[^178] if any communicant should wish to
receive the Sacrament in the hand, in areas where the Bishops'
Conference with the *recognitio* of the Apostolic See has given
permission, the sacred host is to be administered to him or her.
However, special care should be taken to ensure that the host is
consumed by the communicant in the presence of the minister, so that no
one goes away carrying the Eucharistic species in his hand. If there is
a risk of profanation, then Holy Communion should not be given in the
hand to the faithful.[^179]

\[93.\] The Communion-plate for the Communion of the faithful should be
retained, so as to avoid the danger of the sacred host or some fragment
of it falling.[^180]

\[94.\] It is not licit for the faithful "to take . . . by themselves .
. . and, still less, to hand . . . from one to another" the sacred host
or the sacred chalice.[^181] Moreover, in
this regard, the abuse is to be set aside whereby spouses administer
Holy Communion to each other at a Nuptial Mass.

\[95.\] A lay member of Christ's faithful "who has already received the
Most Holy Eucharist may receive it again on the same day only within a
Eucharistic Celebration in which he or she is participating, with due
regard for the prescriptions of can. 921 § 2."[^182]

\[96.\] The practice is reprobated whereby either unconsecrated hosts or
other edible or inedible things are distributed during the celebration
of Holy Mass or beforehand after the manner of Communion, contrary to
the prescriptions of the liturgical books. For such a practice in no way
accords with the tradition of the Roman Rite, and carries with it the
danger of causing confusion among Christ's faithful concerning the
Eucharistic doctrine of the Church. Where there exists in certain places
by concession a particular custom of blessing bread after Mass for
distribution, proper catechesis should very carefully be given
concerning this action. In fact, no other similar practices should be
introduced, nor should unconsecrated hosts ever be used for this
purpose.

## **3. The Communion of Priests**

\[97.\] A Priest must communicate at the altar at the moment laid down
by the Missal each time he celebrates Holy Mass, and the concelebrants
must communicate before they proceed with the distribution of Holy
Communion. The Priest celebrant or a concelebrant is never to wait until
the people's Communion is concluded before receiving Communion himself.[^183]

\[98.\] The Communion of Priest concelebrants should proceed according
to the norms prescribed in the liturgical books, always using hosts
consecrated at the same Mass[^184] and always
with Communion under both kinds being received by all of the
concelebrants. It is to be noted that if the Priest or Deacon hands the
sacred host or chalice to the concelebrants, he says nothing; that is to
say, he does not pronounce the words "The Body of Christ" or "The Blood
of Christ".

\[99.\] Communion under both kinds is always permitted "to Priests who
are not able to celebrate or concelebrate Mass".[^185]

## **4. Communion under Both Kinds**

\[100.\] So that the fullness of the sign may be made more clearly
evident to the faithful in the course of the Eucharistic banquet, lay
members of Christ's faithful, too, are admitted to Communion under both
kinds, in the cases set forth in the liturgical books, preceded and
continually accompanied by proper catechesis regarding the dogmatic
principles on this matter laid down by the Ecumenical Council of Trent.[^186]

\[101.\] In order for Holy Communion under both kinds to be administered
to the lay members of Christ's faithful, due consideration should be
given to the circumstances, as judged first of all by the diocesan
Bishop. It is to be completely excluded where even a small danger exists
of the sacred species being profaned.[^187]
With a view to wider co-ordination, the Bishops' Conferences should
issue norms, once their decisions have received the *recognitio* of the
Apostolic See through the Congregation for Divine Worship and the
Discipline of the Sacraments, especially as regards "the manner of
distributing Holy Communion to the faithful under both kinds, and the
faculty for its extension".[^188]

{{< pagebreak >}}


\[102.\] The chalice should not be ministered to lay members of Christ's
faithful where there is such a large number of communicants[^189] that it is difficult to gauge the
amount of wine for the Eucharist and there is a danger that "more than a
reasonable quantity of the Blood of Christ remain to be consumed at the
end of the celebration".[^190] The same is
true wherever access to the chalice would be difficult to arrange, or
where such a large amount of wine would be required that its certain
provenance and quality could only be known with difficulty, or wherever
there is not an adequate number of sacred ministers or extraordinary
ministers of Holy Communion with proper formation, or where a notable
part of the people continues to prefer not to approach the chalice for
various reasons, so that the sign of unity would in some sense be
negated.

\[103.\] The norms of the Roman Missal admit the principle that in cases
where Communion is administered under both kinds, "the Blood of the Lord
may be received either by drinking from the chalice directly, or by
intinction, or by means of a tube or a spoon".[^191] As regards the administering of
Communion to lay members of Christ's faithful, the Bishops may exclude
Communion with the tube or the spoon where this is not the local custom,
though the option of administering Communion by intinction always
remains. If this modality is employed, however, hosts should be used
which are neither too thin nor too small, and the communicant should
receive the Sacrament from the Priest only on the tongue.[^192]

\[104.\] The communicant must not be permitted to intinct the host
himself in the chalice, nor to receive the intincted host in the hand.
As for the host to be used for the intinction, it should be made of
valid matter, also consecrated; it is altogether forbidden to use
non-consecrated bread or other matter.

\[105.\] If one chalice is not sufficient for Communion to be
distributed under both kinds to the Priest concelebrants or Christ's
faithful, there is no reason why the Priest celebrant should not use
several chalices.[^193] For it is to be
remembered that all Priests in celebrating Holy Mass are bound to
receive Communion under both kinds. It is praiseworthy, by reason of the
sign value, to use a main chalice of larger dimensions, together with
smaller chalices.

\[106.\] However, the pouring of the Blood of Christ after the
consecration from one vessel to another is completely to be avoided,
lest anything should happen that would be to the detriment of so great a
mystery. Never to be used for containing the Blood of the Lord are
flagons, bowls, or other vessels that are not fully in accord with the
established norms.

\[107.\] In accordance with what is laid down by the canons, "one who
throws away the consecrated species or takes them away or keeps them for
a sacrilegious purpose, incurs a *latae sententiae* excommunication
reserved to the Apostolic See; a cleric, moreover, may be punished by
another penalty, not excluding dismissal from the clerical state".[^194] To be regarded as pertaining to this
case is any action that is voluntarily and gravely disrespectful of the
sacred species. Anyone, therefore, who acts contrary to these norms, for
example casting the sacred species into the sacrarium or in an unworthy
place or on the ground, incurs the penalties laid down.[^195] Furthermore all will remember that once
the distribution of Holy Communion during the celebration of Mass has
been completed, the prescriptions of the Roman Missal are to be
observed, and in particular, whatever may remain of the Blood of Christ
must be entirely and immediately consumed by the Priest or by another
minister, according to the norms, while the consecrated hosts that are
left are to be consumed by the Priest at the altar or carried to the
place for the reservation of the Eucharist.[^196]

{{< pagebreak >}}

# Chapter V -- **CERTAIN OTHER MATTERS CONCERNING THE EUCHARIST**

## **1. The Place for the Celebration of Holy Mass**

\[108.\] "The celebration of the Eucharist is to be carried out in a
sacred place, unless in a particular case necessity requires otherwise.
In this case the celebration must be in a decent place."[^197] The diocesan Bishop shall be the judge
for his diocese concerning this necessity, on a case-by-case basis.

\[109.\] It is never lawful for a Priest to celebrate in a temple or
sacred place of any non-Christian religion.

## **2. Various Circumstances Relating to the Mass**

\[110.\] "Remembering always that in the mystery of the Eucharistic
Sacrifice the work of redemption is constantly being carried out,
Priests should celebrate frequently. Indeed, daily celebration is
earnestly recommended, because, even if it should not be possible to
have the faithful present, the celebration is an act of Christ and of
the Church, and in carrying it out, Priests fulfill their principal
role."[^198]

\[111.\] A Priest is to be permitted to celebrate or concelebrate the
Eucharist "even if he is not known to the rector of the church, provided
he presents commendatory letters" (i.e., a *celebret*) not more than a
year old from the Holy See or his Ordinary or Superior "or unless it can
be prudently judged that he is not impeded from celebrating".[^199] Let the Bishops take measures to put a
stop to any contrary practice.

\[112.\] Mass is celebrated either in Latin or in another language,
provided that liturgical texts are used which have been approved
according to the norm of law. Except in the case of celebrations of the
Mass that are scheduled by the ecclesiastical authorities to take place
in the language of the people, Priests are always and everywhere
permitted to celebrate Mass in Latin.[^200]

\[113.\] When Mass is concelebrated by several Priests, a language known
both to all the concelebrating Priests and to the gathered people should
be used in the recitation of the Eucharist Prayer. Where it happens that
some of the Priests who are present do not know the language of the
celebration and therefore are not capable of pronouncing the parts of
the Eucharistic Prayer proper to them, they should not concelebrate, but
instead should attend the celebration in choral dress in accordance with
the norms.[^201]

\[114.\] "At Sunday Masses in parishes, insofar as parishes are
'Eucharistic communities', it is customary to find different groups,
movements, associations, and even the smaller religious communities
present in the parish."[^202] While it is
permissible that Mass should be celebrated for particular groups
according to the norm of law,[^203] these
groups are nevertheless not exempt from the faithful observance of the
liturgical norms.

\[115.\] The abuse is reprobated by which the celebration of Holy Mass
for the people is suspended in an arbitrary manner contrary to the norms
of the Roman Missal and the healthy tradition of the Roman Rite, on the
pretext of promoting a "fast from the Eucharist".

\[116.\] Masses are not to be multiplied contrary to the norm of law,
and as regards Mass stipends, all those things are to be observed which
are otherwise laid down by law.[^204]

## **3. Sacred Vessels**

\[117.\] Sacred vessels for containing the Body and Blood of the Lord
must be made in strict conformity with the norms of tradition and of the
liturgical books.[^205] The Bishops'
Conferences have the faculty to decide whether it is appropriate, once
their decisions have been given the *recognitio* by the Apostolic See,
for sacred vessels to be made of other solid materials as well. It is
strictly required, however, that such materials be truly noble in the
common estimation within a given region,[^206] so that honour will be given to the
Lord by their use, and all risk of diminishing the doctrine of the Real
Presence of Christ in the Eucharistic species in the eyes of the
faithful will be avoided. Reprobated, therefore, is any practice of
using for the celebration of Mass common vessels, or others lacking in
quality, or devoid of all artistic merit or which are mere containers,
as also other vessels made from glass, earthenware, clay, or other
materials that break easily. This norm is to be applied even as regards
metals and other materials that easily rust or deteriorate.[^207]

\[118.\] Before they are used, sacred vessels are to be blessed by a
Priest according to the rites laid down in the liturgical books.[^208] It is praiseworthy for the blessing to
be given by the diocesan Bishop, who will judge whether the vessels are
worthy of the use to which they are destined.

\[119.\] The Priest, once he has returned to the altar after the
distribution of Communion, standing at the altar or at the credence
table, purifies the paten or ciborium over the chalice, then purifies
the chalice in accordance with the prescriptions of the Missal and wipes
the chalice with the purificator. Where a Deacon is present, he returns
with the Priest to the altar and purifies the vessels. It is
permissible, however, especially if there are several vessels to be
purified, to leave them, covered as may be appropriate, on a corporal on
the altar or on the credence table, and for them to be purified by the
Priest or Deacon immediately after Mass once the people have been
dismissed. Moreover a duly instituted acolyte assists the Priest or
Deacon in purifying and arranging the sacred vessels either at the altar
or the credence table. In the absence of a Deacon, a duly instituted
acolyte carries the sacred vessels to the credence table and there
purifies, wipes and arranges them in the usual way.[^209]

\[120.\] Let Pastors take care that the linens for the sacred table,
especially those which will receive the sacred species, are always kept
clean and that they are washed in the traditional way. It is
praiseworthy for this to be done by pouring the water from the first
washing, done by hand, into the church's sacrarium or into the ground in
a suitable place. After this a second washing can be done in the usual
way.

## **4. Liturgical Vesture**

\[121.\] "The purpose of a variety of colour of the sacred vestments is
to give effective expression even outwardly to the specific character of
the mysteries of faith being celebrated and to a sense of Christian
life's passage through the course of the liturgical year".[^210] On the other hand, the variety "of
offices in the celebration of the Eucharist is shown outwardly by the
diversity of sacred vestments. In fact, these "sacred vestments should
also contribute to the beauty of the sacred action itself".[^211]

\[122.\] "The alb" is "to be tied at the waist with a cincture unless it
is made so as to fit even without a cincture. Before the alb is put on,
if it does not completely cover the ordinary clothing at the neck, an
amice should be put on".[^212]

\[123.\] "The vestment proper to the Priest celebrant at Mass, and in
other sacred actions directly connected with Mass unless otherwise
indicated, is the chasuble, worn over the alb and stole."[^213] Likewise the Priest, in putting on the
chasuble according to the rubrics, is not to omit the stole. All
Ordinaries should be vigilant in order that all usage to the contrary be
eradicated.

\[124.\] A faculty is given in the Roman Missal for the Priest
concelebrants at Mass other than the principal concelebrant (who should
always put on a chasuble of the prescribed colour), for a just reason
such as a large number of concelebrants or a lack of vestments, to omit
"the chasuble, using the stole over the alb".[^214] Where a need of this kind can be
foreseen, however, provision should be made for it insofar as possible.
Out of necessity the concelebrants other than the principal celebrant
may even put on white chasubles. For the rest, the norms of the
liturgical books are to be observed.

\[125.\] The proper vestment of the Deacon is the dalmatic, to be worn
over an alb and stole. In order that the beautiful tradition of the
Church may be preserved, it is praiseworthy to refrain from exercising
the option of omitting the dalmatic.[^215]

\[126.\] The abuse is reprobated whereby the sacred ministers celebrate
Holy Mass or other rites without sacred vestments or with only a stole
over the monastic cowl or the common habit of religious or ordinary
clothes, contrary to the prescriptions of the liturgical books, even
when there is only one minister participating.[^216] In order that such abuses be corrected
as quickly as possible, Ordinaries should take care that in all churches
and oratories subject to their jurisdiction there is present an adequate
supply of liturgical vestments made in accordance with the norms.

\[127.\] A special faculty is given in the liturgical books for using
sacred vestments that are festive or more noble on more solemn
occasions, even if they are not of the colour of the day.[^217] However, this faculty, which is
specifically intended in reference to vestments made many years ago,
with a view to preserving the Church's patrimony, is improperly extended
to innovations by which forms and colours are adopted according to the
inclination of private individuals, with disregard for traditional
practice, while the real sense of this norm is lost to the detriment of
the tradition. On the occasion of a feastday, sacred vestments of a gold
or silver colour can be substituted as appropriate for others of various
colours, but not for purple or black.

\[128.\] Holy Mass and other liturgical celebrations, which are acts of
Christ and of the people of God hierarchically constituted, are ordered
in such a way that the sacred ministers and the lay faithful manifestly
take part in them each according to his own condition. It is preferable
therefore that "Priests who are present at a Eucharistic Celebration,
unless excused for a good reason, should as a rule exercise the office
proper to their Order and thus take part as concelebrants, wearing the
sacred vestments. Otherwise, they wear their proper choir dress or a
surplice over a cassock."[^218] It is not
fitting, except in rare and exceptional cases and with reasonable cause,
for them to participate at Mass, as regards to externals, in the manner
of the lay faithful.

{{< pagebreak >}}

# Chapter VI -- **THE RESERVATION OF THE MOST HOLY EUCHARIST AND EUCHARISTIC WORSHIP OUTSIDE MASS**

## **1. The Reservation of the Most Holy Eucharist**

\[129.\] "The celebration of the Eucharist in the Sacrifice of the Mass
is truly the origin and end of the worship given to the Eucharist
outside the Mass. Furthermore the sacred species are reserved after Mass
principally so that the faithful who cannot be present at Mass, above
all the sick and those advanced in age, may be united by sacramental
Communion to Christ and his Sacrifice which is offered in the Mass."[^219] In addition, this reservation also
permits the practice of adoring this great Sacrament and offering it the
worship due to God. Accordingly, forms of adoration that are not only
private but also public and communitarian in nature, as established or
approved by the Church herself, must be greatly promoted.[^220]

\[130.\] "According to the structure of each church building and in
accordance with legitimate local customs, the Most Holy Sacrament is to
be reserved in a tabernacle in a part of the church that is noble,
prominent, readily visible, and adorned in a dignified manner" and
furthermore "suitable for prayer" by reason of the quietness of the
location, the space available in front of the tabernacle, and also the
supply of benches or seats and kneelers.[^221] In addition, diligent attention should
be paid to all the prescriptions of the liturgical books and to the norm
of law,[^222] especially as regards the
avoidance of the danger of profanation.[^223]

\[131.\] Apart from the prescriptions of canon 934 § 1, it is forbidden
to reserve the Blessed Sacrament in a place that is not subject in a
secure way to the authority of the diocesan Bishop, or where there is a
danger of profanation. Where such is the case, the diocesan Bishop
should immediately revoke any permission for reservation of the
Euchari­st that may already have been granted.[^224]

\[132.\] No one may carry the Most Holy Eucharist to his or her home, or
to any other place contrary to the norm of law. It should also be borne
in mind that removing or retaining the consecrated species for a
sacrilegious purpose or casting them away are *graviora delicta*, the
absolution of which is reserved to the Congregation for the Doctrine of
the Faith.[^225]

\[133.\] A Priest or Deacon, or an extraordinary minister who takes the
Most Holy Eucharist when an ordained minister is absent or impeded in
order to administer it as Communion for a sick person, should go insofar
as possible directly from the place where the Sacrament is reserved to
the sick person's home, leaving aside any profane business so that any
danger of profanation may be avoided and the greatest reverence for the
Body of Christ may be ensured. Furthermore the Rite for the
administration of Communion to the sick, as prescribed in the Roman
Ritual, is always to be used.[^226]

## **2. Certain Forms of Worship of the Most Holy Eucharist Outside Mass**

\[134.\] "The worship of the Eucharist outside the Sacrifice of the Mass
is a tribute of inestimable value in the life of the Church. Such
worship is closely linked to the celebration of the Eucharistic
Sacrifice."[^227] Therefore both public and
private devotion to the Most Holy Eucharist even outside Mass should be
vigorously promoted, for by means of it the faithful give adoration to
Christ, truly and really present,[^228] the
"High Priest of the good things to come"[^229] and Redeemer of the whole world. "It is
the responsibility of sacred Pastors, even by the witness of their life,
to support the practice of Eucharistic worship and especially exposition
of the Most Holy Sacrament, as well as prayer of adoration before Christ
present under the eucharistic species."[^230]

\[135.\] The faithful "should not omit making visits during the day to
the Most Holy Sacrament, as a proof of gratitude, a pledge of love, and
a debt of the adoration due to Christ the Lord who is present in it."[^231] For the contemplation of Jesus present
in the Most Holy Sacrament, as a communion of desire, powerfully joins
the faithful to Christ, as is splendidly evident in the example of so
many Saints.[^232] 'Unless there is a grave
reason to the contrary, a church in which the Most Holy Eucharist is
reserved should be open to the faithful for at least some hours each
day, so that they can spend time in prayer before the Most Holy
Sacrament."[^233]

\[136.\] The Ordinary should diligently foster Eucharistic adoration,
whether brief or prolonged or almost continuous, with the participation
of the people. For in recent years in so many places "adoration of the
Most Holy Sacrament is also an important daily practice and becomes an
inexhaustible source of holiness", although there are also places "where
there is evident almost a total lack of regard for worship in the form
of eucharistic adoration."[^234]

\[137.\] Exposition of the Most Holy Eucharist must always be carried
out in accordance with the prescriptions of the liturgical books.[^235] Before the Most Holy Sacrament either
reserved or exposed, the praying of the Rosary, which is admirable "in
its simplicity and even its profundity", is not to be excluded either.[^236] Even so, especially if there is
Exposition**,** the character of this kind of prayer as a contemplation
of the mystery of the life of Christ the Redeemer and the Almighty
Father's design of salvation should be emphasized, especially by making
use of readings taken from Sacred Scripture.[^237]

\[138.\] Still, the Most Holy Sacrament, when exposed, must never be
left unattended even for the briefest space of time. It should therefore
be arranged that at least some of the faithful always be present at
fixed times, even if they take alternating turns.

\[139.\] Where the diocesan Bishop has sacred ministers or others whom
he can assign to this purpose, the faithful have a right to visit the
Most Holy Sacrament of the Eucharist frequently for adoration, and to
take part in adoration before the Most Holy Eucharist exposed at least
at some time in the course of any given year.

\[140.\] It is highly recommended that at least in the cities and the
larger towns the diocesan Bishop should designate a church building for
perpetual adoration; in it, however, Holy Mass should be celebrated
frequently, even daily if possible, while the Exposition should
rigorously be interrupted while Mass is being celebrated.[^238] It is fitting that the host to be
exposed for adoration should be consecrated in the Mass immediately
preceding the time of adoration, and that it should be placed in the
monstrance upon the altar after Communion.[^239]

\[141.\] The diocesan Bishop should acknowledge and foster insofar as
possible the right of the various groups of Christ's faithful to form
guilds or associations for the carrying out of adoration, even almost
continuous adoration. Whenever such associations assume an international
character, it pertains to the Congregation for Divine Worship and the
Discipline of the Sacraments to erect them and to approve their
statutes.[^240]

**3. Eucharistic Congresses and Eucharistic Processions**

\[142.\] "It is for the diocesan Bishop to establish regulations about
processions in order to provide for participation in them and for their
being carried out in a dignified way"[^241]
and to promote adoration by the faithful.

\[143.\] "Wherever it is possible in the judgement of the diocesan
Bishop, a procession through the public streets should be held,
especially on the Solemnity of the Body and Blood of Christ as a public
witness of reverence for the Most Holy Sacrament",[^242] for the "devout participation of the
faithful in the eucharistic procession on the Solemnity of the Body and
Blood of Christ is a grace from the Lord which yearly fills with joy
those who take part in it".[^243]

\[144.\] Although this cannot be done in some places, the tradition of
holding eucharistic processions should not be allowed to be lost.
Instead, new ways should be sought of holding them in today's
conditions: for example, at shrines, or in public gardens if the civil
authority agrees.

\[145.\] The pastoral value of Eucharistic Congresses should be highly
esteemed, and they "should be a genuine sign of faith and charity".[^244] Let them be diligently prepared and
carried out in accordance with what has been laid down,[^245] so that Christ's faithful may have the
occasion to worship the sacred mysteries of the Body and Blood of the
Son of God in a worthy manner, and that they may continually experience
within themselves the fruits of the Redemption.[^246]

{{< pagebreak >}}

# Chapter VII -- **EXTRAORDINARY FUNCTIONS OF LAY FAITHFUL**

\[146.\] There can be no substitute whatsoever for the ministerial
Priesthood. For if a Priest is lacking in the community, then the
community lacks the exercise and sacramental function of Christ the Head
and Shepherd, which belongs to the essence of its very life.[^247] For "the only minister who can confect
the sacrament of the Eucharist *in persona Christi* is a validly
ordained Priest".[^248]

\[147.\] When the Church's needs require it, however, if sacred
ministers are lacking, lay members of Christ's faithful may supply for
certain liturgical offices according to the norm of law.[^249] Such faithful are called and appointed
to carry out certain functions, whether of greater or lesser weight,
sustained by the Lord's grace. Many of the lay Christian faithful have
already contributed eagerly to this service and still do so, especially
in missionary areas where the Church is still of small dimensions or is
experiencing conditions of persecution,[^250]
but also in areas affected by a shortage of Priests and Deacons.

\[148.\] Particular importance is to be attached to the training of
catechists, who by means of great labours have given and still give
outstanding and altogether necessary help in the spreading of the faith
and of the Church.[^251]

\[149.\] More recently, in some dioceses long since evangelized, members
of Christ's lay faithful have been appointed as "pastoral assistants",
and among them many have undoubtedly served the good of the Church by
providing assistance to the Bishop, Priests and Deacons in the carrying
out of their pastoral activity. Let care be taken, however, lest the
delineation of this function be assimilated too closely to the form of
pastoral ministry that belongs to clerics. That is to say, attention
should be paid to ensuring that "pastoral assistants" do not take upon
themselves what is proper to the ministry of the sacred ministers.

\[150.\] The activity of a pastoral assistant should be directed to
facilitating the ministry of Priests and Deacons, to ensuring that
vocations to the Priesthood and Diaconate are awakened and that lay
members of Christ's faithful in each community are carefully trained for
the various liturgical functions, in keeping with the variety of
charisms and in accordance with the norm of law.

\[151.\] Only out of true necessity is there to be recourse to the
assistance of extraordinary ministers in the celebration of the Liturgy.
Such recourse is not intended for the sake of a fuller participation of
the laity but rather, by its very nature, is supplementary and
provisional.[^252] Furthermore, when recourse
is had out of necessity to the functions of extraordinary ministers,
special urgent prayers of intercession should be multiplied that the
Lord may soon send a Priest for the service of the community and raise
up an abundance of vocations to sacred Orders.[^253]

\[152.\] These purely supplementary functions must not be an occasion
for disfiguring the very ministry of Priests, in such a way that the
latter neglect the celebration of Holy Mass for the people for whom they
are responsible, or their personal care of the sick, or the baptism of
children, or assistance at weddings or the celebration of Christian
funerals, matters which pertain in the first place to Priests assisted
by Deacons. It must therefore never be the case that in parishes Priests
alternate indiscriminately in shifts of pastoral service with Deacons or
laypersons, thus confusing what is specific to each.

\[153.\] Furthermore, it is never licit for laypersons to assume the
role or the vesture of a Priest or a Deacon or other clothing similar to
such vesture.

## **1. The Extraordinary Minister of Holy Communion**

\[154.\] As has already been recalled, "the only minister who can
confect the Sacrament of the Eucharist *in persona Christi* is a validly
ordained Priest".[^254] Hence the name
"minister of the Eucharist" belongs properly to the Priest alone.
Moreover, also by reason of their sacred Ordination, the ordinary
ministers of Holy Communion are the Bishop, the Priest and the Deacon,[^255] to whom it belongs therefore to
administer Holy Communion to the lay members of Christ's faithful during
the celebration of Mass. In this way their ministerial office in the
Church is fully and accurately brought to light, and the sign value of
the Sacrament is made complete.

\[155.\] In addition to the ordinary ministers there is the formally
instituted acolyte, who by virtue of his institution is an extraordinary
minister of Holy Communion even outside the celebration of Mass. If,
moreover, reasons of real necessity prompt it, another lay member of
Christ's faithful may also be delegated by the diocesan Bishop, in
accordance with the norm of law,[^256] for
one occasion or for a specified time, and an appropriate formula of
blessing may be used for the occasion. This act of appointment, however,
does not necessarily take a liturgical form, nor, if it does take a
liturgical form, should it resemble sacred Ordination in any way.
Finally, in special cases of an unforeseen nature, permission can be
given for a single occasion by the Priest who presides at the
celebration of the Eucharist.[^257]

\[156.\] This function is to be understood strictly according to the
name by which it is known, that is to say, that of extraordinary
minister of Holy Communion, and not "special minister of Holy Communion"
nor "extraordinary minister of the Eucharist" nor "special minister of
the Eucharist", by which names the meaning of this function is
unnecessarily and improperly broadened.

\[157.\] If there is usually present a sufficient number of sacred
ministers for the distribution of Holy Communion, extraordinary
ministers of Holy Communion may not be appointed. Indeed, in such
circumstances, those who may have already been appointed to this
ministry should not exercise it. The practice of those Priests is
reprobated who, even though present at the celebration, abstain from
distributing Communion and hand this function over to laypersons.[^258]

\[158.\] Indeed, the extraordinary minister of Holy Communion may
administer Communion only when the Priest and Deacon are lacking, when
the Priest is prevented by weakness or advanced age or some other
genuine reason, or when the number of faithful coming to Communion is so
great that the very celebration of Mass would be unduly prolonged.[^259] This, however, is to be understood in
such a way that a brief prolongation, considering the circumstances and
culture of the place, is not at all a sufficient reason.

\[159.\] It is never allowed for the extraordinary minister of Holy
Communion to delegate anyone else to administer the Eucharist, as for
example a parent or spouse or child of the sick person who is the
communicant.

\[160.\] Let the diocesan Bishop give renewed consideration to the
practice in recent years regarding this matter, and if circumstances
call for it, let him correct it or define it more precisely. Where such
extraordinary ministers are appointed in a widespread manner out of true
necessity, the diocesan Bishop should issue special norms by which he
determines the manner in which this function is to be carried out in
accordance with the law, bearing in mind the tradition of the Church.

## **2. Preaching**

\[161.\] As was already noted above, the homily on account of its
importance and its nature is reserved to the Priest or Deacon during
Mass.[^260] As regards other forms of
preaching, if necessity demands it in particular circumstances, or if
usefulness suggests it in special cases, lay members of Christ's
faithful may be allowed to preach in a church or in an oratory outside
Mass in accordance with the norm of law.[^261] This may be done only on account of a
scarcity of sacred ministers in certain places, in order to meet the
need, and it may not be transformed from an exceptional measure into an
ordinary practice, nor may it be understood as an authentic form of the
advancement of the laity.[^262] All must
remember besides that the faculty for giving such permission belongs to
the local Ordinary, and this as regards individual instances; this
permission is not the competence of anyone else, even if they are
Priests or Deacons.

## **3. Particular Celebrations carried out in the Absence of a Priest**

\[162.\] On the day known as the Lord's Day, the Church faithful gathers
together to commemorate the Lord's Resurrection and the whole Paschal
Mystery, especially by the celebration of Mass.[^263] For "no Christian community is built up
unless it is rooted in and hinges upon the celebration of the Most Holy
Eucharist".[^264] Hence it is the Christian
people's right to have the Eucharist celebrated for them on Sunday, and
whenever holydays of obligation or other major feasts occur, and even
daily insofar as this is possible. Therefore when it is difficult to
have the celebration of Mass on a Sunday in a parish church or in
another community of Christ's faithful, the diocesan Bishop together
with his Priests should consider appropriate remedies.[^265] Among such solutions will be that other
Priests be called upon for this purpose, or that the faithful transfer
to a church in a nearby place so as to participate in the Eucharistic
mystery there.[^266]

\[163.\] All Priests, to whom the Priesthood and the Eucharist are
entrusted *for the sake of* others,[^267]
should remember that they are enjoined to provide the faithful with the
opportunity to satisfy the obligation of participating at Mass on
Sundays.[^268] For their part, the lay
faithful have the right, barring a case of real impossibility, that no
Priest should ever refuse either to celebrate Mass for the people or to
have it celebrated by another Priest if the people otherwise would not
be able to satisfy the obligation of participating at Mass on Sunday or
the other days of precept.

\[164.\] "If participation at the celebration of the Eucharist is
impossible on account of the absence of a sacred minister or for some
other grave cause,"[^269] then it is the
Christian people's right that the diocesan Bishop should provide as far
as he is able for some celebration to be held on Sundays for that
community under his authority and according to the Church's norms.
Sunday celebrations of this specific kind, however, are to be considered
altogether extraordinary. All Deacons or lay members of Christ's
faithful who are assigned a part in such celebrations by the diocesan
Bishop should strive "to keep alive in the community a genuine 'hunger'
for the Eucharist, so that no opportunity for the celebration of Mass
will ever be missed, also taking advantage of the occasional presence of
a Priest who is not impeded by Church law from celebrating Mass".[^270]

\[165.\] It is necessary to avoid any sort of confusion between this
type of gathering and the celebration of the Eucharist.[^271] The diocesan Bishops, therefore, should
prudently discern whether Holy Communion ought to be distributed in
these gatherings. The matter would appropriately be determined in view
of a more ample co-ordination in the Bishops' Conference, to be put into
effect after the *recognitio* of the acts by the Apostolic See through
the Congregation for Divine Worship and the Discipline of the
Sacraments. It will be preferable, moreover, when both a Priest and a
Deacon are absent, that the various parts be distributed among several
faithful rather than having a single lay member of the faithful direct
the whole celebration alone. Nor is it ever appropriate to refer to any
member of the lay faithful as "presiding" over the celebration.

\[166.\] Likewise, especially if Holy Communion is distributed during
such celebrations, the diocesan Bishop, to whose exclusive competence
this matter pertains, must not easily grant permission for such
celebrations to be held on weekdays, especially in places where it was
possible or would be possible to have the celebration of Mass on the
preceding or the following Sunday. Priests are therefore earnestly
requested to celebrate Mass daily for the people in one of the churches
entrusted to their care.

\[167.\] "Similarly, it is unthinkable on the Lord's Day to substitute
for Holy Mass either ecumenical celebrations of the word or services of
common prayer with Christians from the . . . Ecclesial Communities, or
even participation in these Communities' liturgical services."[^272] Should the diocesan Bishop out of
necessity authorize the participation of Catholics for a single
occasion, let pastors take care lest confusion arise among the Catholic
faithful concerning the necessity of taking part at Mass at another hour
of the day even in such circumstances, on account of the obligation.[^273]

## **4. Those Who Have Left the Clerical State**

\[168.\] "A cleric who loses the clerical state in accordance with the
law . . . is prohibited from exercising the power of order".[^274] It is therefore not licit for him to
celebrate the sacraments under any pretext whatsoever save in the
exceptional case set forth by law,[^275] nor
is it licit for Christ's faithful to have recourse to him for the
celebration, since there is no reason which would permit this according
to canon 1335.[^276] Moreover, these men
should neither give the homily[^277] nor ever
undertake any office or duty in the celebration of the sacred Liturgy,
lest confusion arise among Christ's faithful and the truth be obscured.

{{< pagebreak >}}

# Chapter VIII -- **REMEDIES**

\[169.\] Whenever an abuse is committed in the celebration of the sacred
Liturgy, it is to be seen as a real falsification of Catholic Liturgy.
St Thomas wrote, "the vice of falsehood is perpetrated by anyone who
offers worship to God on behalf of the Church in a manner contrary to
that which is established by the Church with divine authority, and to
which the Church is accustomed".[^278]

\[170.\] In order that a remedy may be applied to such abuses, "there is
a pressing need for the biblical and liturgical formation of the people
of God, both pastors and faithful",[^279] so
that the Church's faith and discipline concerning the sacred Liturgy may
be accurately presented and understood. Where abuses persist, however,
proceedings should be undertaken for safeguarding the spiritual
patrimony and rights of the Church in accordance with the law, employing
all legitimate means.

\[171.\] Among the various abuses there are some which are objectively
*graviora delicta* or otherwise constitute grave matters, as well as
others which are nonetheless to be carefully avoided and corrected.
Bearing in mind everything that is treated especially in Chapter I of
this Instruction, attention should be paid to what follows.

## **1. *Graviora delicta***

\[172.\] *Graviora delicta* against the sanctity of the Most August
Sacrifice and Sacrament of the Eucharist are to be handled in accordance
with the 'Norms concerning *graviora delicta* reserved to the
Congregation for the Doctrine of the Faith',[^280] namely:


{{< pagebreak >}}



a\) taking away or retaining the consecrated species for sacrilegious
ends, or the throwing them away;[^281]

b\) the attempted celebration of the liturgical action of the
Eucharistic Sacrifice or the simulation of the same;[^282]

c\) the forbidden concelebration of the Eucharistic Sacrifice with
ministers of Ecclesial Communities that do not have the apostolic
succession nor acknowledge the sacramental dignity of priestly
Ordination;[^283]

d\) the consecration for sacrilegious ends of one matter without the
other in the celebration of the Eucharist or even of both outside the
celebration of the Eucharist.[^284]

## **2. Grave Matters**

\[173.\] Although the gravity of a matter is to be judged in accordance
with the common teaching of the Church and the norms established by her,
objectively to be considered among grave matters is anything that puts
at risk the validity and dignity of the Most Holy Eucharist: namely,
anything that contravenes what is set out above in nn. 48-52, 56, 76-77,
79, 91-92, 94, 96, 101-102, 104, 106, 109, 111, 115, 117, 126, 131-133,
138, 153 and 168. Moreover, attention should be given to the other
prescriptions of the Code of Canon Law, and especially what is laid down
by canons 1364, 1369, 1373, 1376, 1380, 1384, 1385, 1386, and 1398.

## **3. Other Abuses**

\[174.\] Furthermore, those actions that are brought about which are
contrary to the other matters treated elsewhere in this Instruction or
in the norms established by law are not to be considered of little
account, but are to be numbered among the other abuses to be carefully
avoided and corrected.

\[175.\] The things set forth in this Instruction obviously do not
encompass all the violations against the Church and its discipline that
are defined in the canons, in the liturgical laws and in other norms of
the Church for the sake of the teaching of the Magisterium or sound
tradition. Where something wrong has been committed, it is to be
corrected according to the norm of law.

## **4. The Diocesan Bishop**

\[176.\] The diocesan Bishop, "since he is the principal dispenser of
the mysteries of God, is to strive constantly so that Christ's faithful
entrusted to his care may grow in grace through the celebration of the
sacraments, and that they may know and live the Paschal Mystery".[^285] It is his responsibility, "within the
limits of his competence, to issue norms on liturgical matters by which
all are bound".[^286]

\[177.\] "Since he must safeguard the unity of the universal Church, the
Bishop is bound to promote the discipline common to the entire Church
and therefore to insist upon the observance of all ecclesiastical laws.
He is to be watchful lest abuses encroach upon ecclesiastical
discipline, especially as regards the ministry of the Word, the
celebration of the Sacraments and sacramentals, the worship of God and
the veneration of the Saints".[^287]

\[178.\] Hence whenever a local Ordinary or the Ordinary of a religious
Institute or of a Society of apostolic life receives at least a
plausible notice of a delict or abuse concerning the Most Holy
Eucharist, let him carefully investigate, either personally or by means
of another worthy cleric, concerning the facts and the circumstances as
well as the imputability.

\[179.\] Delicts against the faith as well as *graviora delicta*
committed in the celebration of the Eucharist and the other Sacraments
are to be referred without delay to the Congregation for the Doctrine of
the Faith, which "examines \[them\] and, if necessary, proceeds to the
declaration or imposition of canonical sanctions according to the norm
of common or proper law".[^288]

\[180.\] Otherwise the Ordinary should proceed according the norms of
the sacred canons, imposing canonical penalties if necessary, and
bearing in mind in particular that which is laid down by canon 1326. If
the matter is serious, let him inform the Congregation for Divine
Worship and the Discipline of the Sacraments.

## **5. The Apostolic See**

\[181.\] Whenever the Congregation for Divine Worship and the Discipline
of the Sacraments receives at least a plausible notice of a delict or an
abuse concerning the Most Holy Eucharist, it informs the Ordinary so
that he may investigate the matter. When the matter turns out to be
serious, the Ordinary should send to the same Dicastery as quickly as
possible a copy of the acts of the inquiry that has been undertaken, and
where necessary, the penalty imposed.

\[182.\] In more difficult cases the Ordinary, for the sake of the good
of the universal Church in the care for which he too has a part by
virtue of his sacred Ordination, should not fail to handle the matter,
having previously taken advice from the Congregation for Divine Worship
and the Discipline of the Sacraments. For its part, this Congregation,
on the strength of the faculties given to it by the Roman Pontiff,
according to the nature of the case, will assist the Ordinary, granting
him the necessarydispensations[^289] or
giving him instructions or prescriptions, which he is to follow
diligently.

## **6. Complaints Regarding Abuses in Liturgical Matters**

\[183.\] In an altogether particular manner, let everyone do all that is
in their power to ensure that the Most Holy Sacrament of the Eucharist
will be protected from any and every irreverence or distortion and that
all abuses be thoroughly corrected. This is a most serious duty
incumbent upon each and every one, and all are bound to carry it out
without any favouritism.

\[184.\] Any Catholic, whether Priest or Deacon or lay member of
Christ's faithful, has the right to lodge a complaint regarding a
liturgical abuse to the diocesan Bishop or the competent Ordinary
equivalent to him in law, or to the Apostolic See on account of the
primacy of the Roman Pontiff.[^290] It is
fitting, however, insofar as possible, that the report or complaint be
submitted first to the diocesan Bishop. This is naturally to be done in
truth and charity.

{{< pagebreak >}}

# CONCLUSION

\[185.\] "Against the seeds of discord which daily experience shows to
be so deeply ingrained in human nature as a result of sin, there stands
the creative power of the unity of Christ's body. For it is precisely by
building up the Church that the Eucharist establishes fellowship among
men."[^291] It is therefore the hope of this
Congregation for Divine Worship and the Discipline of the Sacraments
that also, by the diligent application of those things that are recalled
in this Instruction, human weakness may come to pose less of an obstacle
to the action of the Most Holy Sacrament of the Eucharist, and that with
all distortion set aside and every reprobated practice removed,[^292] through the intercession of the Blessed
Virgin Mary, "Woman of the Eucharist", the saving presence of Christ in
the Sacrament of his Body and Blood may shine brightly upon all people.

\[186.\] Let all Christ's faithful participate in the Most Holy
Eucharist as fully, consciously and actively as they can,[^293] honouring it lovingly by their devotion
and the manner of their life. Let Bishops, Priests and Deacons, in the
exercise of the sacred ministry, examine their consciences as regards
the authenticity and fidelity of the actions they have performed in the
name of Christ and the Church in the celebration of the Sacred Liturgy.
Let each one of the sacred ministers ask himself, even with severity,
whether he has respected the rights of the lay members of Christ's
faithful, who confidently entrust themselves and their children to him,
relying on him to fulfill for the faithful those sacred functions that
the Church intends to carry out in celebrating the sacred Liturgy at
Christ's command.[^294] For each one should
always remember that he is a servant of the Sacred Liturgy.[^295]

All things to the contrary notwithstanding.

This Instruction, prepared by the Congregation for Divine Worship and
the Discipline of the Sacraments by mandate of the Supreme Pontiff John
Paul II in collaboration with the Congregation for the Doctrine of the
Faith, was approved by the same Pontiff on the Solemnity of St. Joseph,
19 March 2004, and he ordered it to be published and to be observed
immediately by all concerned.

From the offices of the Congregation for Divine Worship and the
Discipline of the Sacraments, Rome, on the Solemnity of the Annunciation
of the Lord, 25 March 2004.

**Francis Card. Arinze***\
Prefect*

**Domenico Sorrentino*****\
**Archbishop Secretary*


[^1]: Cf. Missale Romanum, ex decreto sacrosancti
Oecumenici Concilii Vaticani II instauratum, auctoritate Pauli Pp. VI
promulgatum, Ioannis Pauli Pp. II cura recognitum, editio typica tertia,
diei 20 aprilis 2000, Typis Vaticanis, 2002, Missa votiva de Dei
misericordia, oratio super oblata, p. 1159.

[^2]: Cf. *1 Cor* 11, 26; Missale Romanum*,* Prex
Eucharistica, acclamatio post consecrationem, p. 576; Pope John Paul II,
Encyclical Letter, *Ecclesia de Eucharistia*, 17 April 2003, nn. 5, 11,
14, 18: AAS 95 (2003) pp. 436, 440-441, 442, 445.

[^3]: Cf. *Is* 10: 33; 51, 22; Missale Romanum*,*
In sollemnitate Domini nostri Iesu Christi, universorum Regis,
Praefatio, p. 499.

[^4]: Cf.*1 Cor* 5: 7; Second Vatican Ecumenical
Council, Decree on the Ministry and Life of Priests, *Presbyterorum
ordinis,* 7 December 1965, n. 5; John Paul II, Apostolic Exhortation.,
*Ecclesia in Europa*, n. 75: AAS 95 (2003) pp. 649-719, here p. 693.

[^5]: Cf. Second Vatican Ecumenical Council,
Dogmatic Constitution on the Church, *Lumen gentium*, 21 November 1964,
n. 11.

[^6]: Cf. Pope John Paul II, Encyclical Letter
*Ecclesia de Eucharistia*, 17 April 2003, n. 21: AAS 95 (2003) p. 447.

[^7]: *Ibidem*: AAS 95 (2003) pp. 433-475.

[^8]: *Ibidem,* n. 52: AAS 95 (2003) p. 468.

[^9]: *Ibidem*.

[^10]: *Ibidem*, n. 10: AAS 95 (2003) p. 439.

[^11]: *Ibidem;* cf. Pope John Paul II, Apostolic
Letter, *Vicesimus quintus annus,* 4 December 1988, nn. 12-13: AAS 81
(1989)pp. 909-910; cf. also Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium,* 4 December
1963 n. 48.

[^12]: Missale Romanum, Prex Eucharistica III, p.
588; cf. *1 Cor* 12: 12-13; *Eph* 4: 4.

[^13]: Cf. Phil 2,5.

[^14]: Pope John Paul II, Encyclical Letter
*Ecclesia de Eucharistia*, n. 10: AAS 95 (2003), p. 439.

[^15]: *Ibidem*, n. 6: AAS 95 (2003) p. 437; cf.
*Lk* 24: 31.

[^16]: Cf. *Rom* 1: 20.

[^17]: Cf. Missale Romanum, Praefatio I de
Passione Domini, p. 528.

[^18]: Cf. Pope John Paul II, Encyclical Letter
*Veritatis splendor*, 6 August 1993, n. 35: AAS 85 (1993) pp. 1161-1162;
Homily given at Camden Yards, 9 October 1995, n. 7: *Insegnamenti di
Giovanni Paolo II, XVII, 2 (1995),* Libreria Editrice Vaticana, 1998, p.
788.

[^19]: Cf. Pope John Paul II, Encyclical Letter
*Ecclesia de Eucharistia*, n. 10: AAS 95 (2003) p. 439.

[^20]: Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 24; cf.
Congregation for Divine Worship and the Discipline of the Sacraments,
Instruction *Varietates legitimae*, 25 January 1994, nn. 19 and 23: AAS
87 (1995) pp. 295-296, 297.

[^21]: Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 33.

[^22]: Cf. St Irenaeus, *Adversus Haereses*, III,
2: SCh.*.*, 211, 24-31; St Augustine, *Epistula ad Ianuarium*: 54,I: PL
33,200: «Illa autem quae non scripta, sed tradita custodimus, quae
quidem toto terrarum orbe servantur, datur intellegi vel ab ipsis
Apostolis, vel plenariis conciliis, quorum est Ecclesia saluberrima
auctoritas, commendata atque statuta retineri.»; Pope John Paul II,
Encyclical Letter *Redemptoris missio*, 7 December 1990, nn. 53-54: AAS
83 (1991) pp. 300-302; Congregation for the Doctrine of the Faith,
Letter to the Bishops of the Catholic Church on Certain Aspects of the
Church as Communion, *Communionis notio*, 28 May 1992, nn. 7-10: AAS 85
(1993) pp. 842-844; Congregation for Divine Worship and the Discipline
of the Sacraments, Instruction *Varietates legitimae*, n. 26: AAS 87
(1995) pp. 298-299.

[^23]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 21.

[^24]: Cf. Pope Pius XII, Apostolic Constitution
*Sacramentum Ordinis*, 30 November 1947: AAS 40 (1948) p. 5;
Congregation for the Doctrine of the Faith, Declaration *Inter
insigniores*, 15 October 1976, part IV: AAS 69 (1977) pp. 107-108;
Congregation for Divine Worship and the Discipline of the Sacraments,
Instruction *Varietates legitimae*, n. 25: AAS 87 (1995) p. 298.

[^25]: Cf. Pope Pius XII, Encyclical Letter
*Mediator Dei*, 20 November 1947: AAS 39 (1947) p. 540.

[^26]: Cf. S. Congregation for the Sacraments and
Divine Worship, Instruction *Inaestimabile donum*, 3 April 1980: AAS 72
(1980) p. 333.

[^27]: Pope John Paul II, Encyclical Letter
*Ecclesia de Eucharistia*, n. 52: AAS 95 (2003), p. 468.

[^28]: Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, nn. 4,38;
Decree on the Catholic Eastern Churches, *Orientalium Ecclesiarum*, 21
November 1964, nn. 1,2,6; Pope Paul VI, Apostolic Constitution *Missale
Romanum*: AAS 61 (1969) pp. 217-222; Missale Romanum, Institutio
Generalis, n. 399; Congregation for Divine Worship and the Discipline of
the Sacraments, Instruction *Liturgiam authenticam*, 28 March 2001, n.
4: AAS 93 (2001) pp. 685-726, here p. 686.

[^29]: Cf. Pope John Paul II, Apostolic
Exhortation *Ecclesia in Europa*, n. 72: AAS 95 (2003) p. 000.

[^30]: Cf. Pope John Paul II, Encyclical Letter
*Ecclesia de Eucharistia*, n. 23: AAS 95 (2003) pp. 448-449; S.
Congregation of Rites, Instruction *Eucharisticum mysterium*, 25 May
1967, n. 6: AAS 59 (1967) p. 545.

[^31]: S. Congregation for the Sacraments and
Divine Worship, Instruction *Inaestimabile donum*: AAS 72 (1980) pp.
332-333.

[^32]: Cf. 1 Cor 11,17-34; Pope John Paul II,
Encyclical Letter, *Ecclesia de Eucharistia*, n. 52: AAS 95 (2003) pp.
467-468.

[^33]: Cf. *Code of C anon Law*, 25 January 1983,
can. 1752.

[^34]: Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 22 §1;
cf. *Code of Canon Law*, can. 838 §1.

[^35]: *Code of Canon Law*, can. 331; cf. Second
Vatican Ecumenical Council, Dogmatic Constitution on the Church, *Lumen
gentium*, n. 22.

[^36]: *Code of Canon Law*, can. 838 §2.

[^37]: Cf. Pope John Paul II, Apostolic
Constitution, *Pastor bonus*, 28 June 1988: AAS 80 (1988) pp. 841-924,
here artt. 62, 63, and 66, pp. 876-877.

[^38]: Cf. Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia*, n. 52: AAS 95 (2003) p. 468.

[^39]: Cf. Second Vatican Ecumenical Council,
Decree on the Pastoral Office of Bishops, *Christus Dominus*, 28 October
1965, n. 15; cf. also the Constitution on the Sacred Liturgy,
*Sacrosanctum Concilium*, n. 41; *Code of Canon Law*, can. 387.

[^40]: Prayer for the Consecration of a Bishop in
the Byzantine Rite: *Euchologion to mega*, Rome, 1873, p. 139.

[^41]: Cf. St. Ignatius of Antioch, *Ad Smyrn.*
8,1: ed. F.X. Funk, I, p. 282.

[^42]: Second Vatican Ecumenical Council,
Dogmatic Constitution on the Church, *Lumen gentium*, n. 26; cf. S.
Congregation of Rites, Instruction, *Eucharisticum mysterium*, n. 7: AAS
59 (1967) p. 545; cf. also Pope John Paul II, Apostolic Exhortation,
*Pastores gregis*, 16 October 2003, nn. 32-41: *L'Osservatore Romano*,
17 October 2003, pp. 6-8.

[^43]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 41; cf.
St. Ignatius of Antioch, *Ad Magn. 7*, *Ad Philad.* 4, *Ad Smyrn*. 8:
ed. F.X. Funk, I, pp. 236, 266, 281; Missale Romanum, Institutio
Generalis, n. 22; cf. also *Code of Canon Law*, can. 389.

[^44]: Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Lumen gentium*, n. 26.

[^45]: *Code of Canon Law*, can. 838 §4.

[^46]: Cf. Consilium for Implementing the
Constitution on the Liturgy, Dubium: *Notitiae* 1 (1965) p. 254.

[^47]: Cf. Acts 20,28; Second Vatican Ecumenical
Council, Dogmatic Constitution on the Church, *Lumen gentium*, nn. 21
and 27; Decree on the Pastoral Office of Bishops in the Church,
*Christus Dominus*, n. 3.

[^48]: Cf. S. Congregation for Divine Worship,
Instruction, *Liturgicae instaurationes*, 5 September 1970: AAS 62
(1970) p. 694.

[^49]: Cf. Second Vatican Ecumenical Council,
Dogmatic Constitution on the Church, *Lumen gentium*, n. 21; Decree on
the Pastoral Office of Bishops in the Church, *Christus Dominus*, n. 3.

[^50]: Cf. Caeremoniale Episcoporum ex decreto
sacrosancti Oecumenici Concilii Vaticani II instauratum, auctoritate
Ioannis Pauli Pp. II promulgatum, editio typica, 14 September 1984,
Vatican Polyglot Press, 1985, n. 10

[^51]: Cf. Missale Romanum, Institutio Generalis,
n. 387.

[^52]: Cf. *ibidem*, n. 22.

[^53]: Cf. S. Congregation for Divine Worship,
Instruction, *Liturgicae instaurationes*: AAS 62 (1970) p. 694.

[^54]: Second Vatican Ecumenical Council,
Dogmatic Constitution on the Church, *Lumen gentium*, n. 27; cf*. 2 Cor*
4,15.

[^55]: Cf. *Code of Canon Law*, canons 397 §1;
678 §1.

[^56]: Cf. *ibidem*, canon 683 §1.

[^57]: *Ibidem*, canon 392.

[^58]: Cf. Pope John Paul II, Apostolic Letter
*Vicesimus quintus annus*, n. 21: AAS 81 (1989) p. 917; Second Vatican
Ecumenical Council, Constitution on the Sacred Liturgy, *Sacrosanctum
Concilium*, nn. 45-46; Pope Pius XII, Encyclical Letter *Mediator Dei*:
AAS 39 (1947) p. 562.

[^59]: Cf. Pope John Paul II, Apostolic Letter
*Vicesimus quintus annus*, n. 20: AAS 81 (1989) p. 916.

[^60]: Cf. *ibidem*.

[^61]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 44;
Congregation for Bishops, Letter sent to the Presidents of the
Conferences of Bishops together with the Congregation for the
Evangelization of Peoples, 21 June 1999, n. 9: AAS 91 (1999) p. 999.

[^62]: Cf. Congregation for Divine Worship,
Instruction *Liturgicae instaurationis*, n. 12: AAS 62 (1970) pp.
692-704; cf., here p. 703.

[^63]: Cf. Congregation For Divine Worship,
*Declaration on Eucharistic Prayers and liturgical experimentation*, 21
March 1988: *Notitiae* 24 (1988) pp. 234-236.

[^64]: Cf. Congregation for Divine Worship and
the Discipline of the Sacraments, Instruction *Varietates legitimae*:
AAS 87 (1995) pp. 288-314.

[^65]: Cf. *Code of Canon Law*, can. 838 § 3; S.
Congregation of Rites, Instruction *Inter Oecumenici*, 26 September
1964, n. 31: AAS 56 (1964) p. 883; Congregation for Divine Worship and
the Discipline of the Sacraments, Instruction *Liturgiam authenticam*,
nn. 79-80: AAS 93 (2001) pp. 711-713.

[^66]: Cf. Second Vatican Ecumenical Council,
Decree on the Ministry and Life of Priests, *Presbyterorum ordinis*, 7
December 1965, n. 7; Pontificale Romanum, ed. 1962: Ordo consecrationis
sacerdotalis, in Praefatione; Pontificale Romanum *ex decreto
sacrosancti Oecumenici Concilii Vaticani II renovatum, auctoritate Pauli
Pp. VI editum, Ioannis Pauli Pp. II cura recognitum*: De Ordinatione
Episcopi, presbyterorum et diaconorum, editio typica altera, 29 June
1989, Typis Polyglottis Vaticanis, 1990, cap. II: De Ordin.
presbyterorum, Praenotanda, n. 101.

[^67]: St. Ignatius of Antioch, *Ad Philad.*, 4:
ed. F.X. Funk, I, p. 266; Pope St. Cornelius I, cited by St. Cyprian,
Letter 48,2: ed. G. Hartel, III,2, p. 610.

[^68]: Second Vatican Ecumenical Council,
Dogmatic Constitution on the Church, *Lumen gentium*, n. 28.

[^69]: Cf. *ibidem*.

[^70]: John Paul II, Encyclical Letter *Ecclesia
de Eucharistia*, n. 52; cf. n. 29: AAS 95 (2003) pp. 467-468; 452-435.

[^71]: Pontificale Romanum, De Ordinatione
Episcopi, presbyterorum et diaconorum, editio typica altera: *De
Ordinatione Presbyterorum*, n. 124; cf. Missale Romanum, Feria V in
Hebdomada Sancta: Ad Missam chrismatis, Renovatio promissionum
sacerdotalium, p. 292.

[^72]: Cf. Ecumenical Council of Trent, Session
VII, 3 March 1547, Decree on the Sacraments, canon 13, DS 1613; Second
Vatican Ecumenical Council, Constitution on the Sacred Liturgy,
*Sacrosanctum Concilium*, n. 22; Pope Pius XII, Encyclical Letter
*Mediator Dei*: AAS 39 (1947) pp. 544, 546-547, 562; *Codex Iuris
Canonici*, can 846, § 1; Missale Romanum, Institutio Generalis, n. 24.

[^73]: St. Ambrose, *De Virginitate*, n. 48: PL
16, 278.

[^74]: *Code of Canon Law*, can. 528 § 2.

[^75]: Second Vatican Ecumenical Council, Decree
on the Ministry and Life of Priests, *Presbyterorum Ordinis*, n. 5.

[^76]: Cf. Pope John Paul II, Encyclical Letter
*Ecclesia de Eucharistia*, n. 5: AAS 95 (2003) p. 436.

[^77]: Second Vatican Ecumenical Council,
Dogmatic Constitution on the Church, *Lumen gentium,* n. 29; cf.
*Constitutiones Ecclesiae Aegypticae,* III, 2: ed. F.X. Funk,
*Didascalia*, II, p. 103; *Statuta Ecclesiae Ant*., 37-41: ed. D. Mansi
3, 954.

[^78]: Cf. *Acts* 6,3.

[^79]: *Jn* 13,35.

[^80]: *Matt* 20,28.

[^81]: Cf. Luke 22,27.

[^82]: Cf. Caeremoniale Episcoporum, nn. 9, 23.
Cf. Second Vatican Ecumenical Council, Dogmatic Constitution on the
Church, *Lumen gentium*, n. 29.

[^83]: Cf. Pontificale Romanum, De Ordinatione
Episcopi, presbyterorum et diaconorum, editio typica altera, cap. III,
*De Ordin. diaconorum*, n. 199.

[^84]: Cf. *1 Tim* 3,9.

[^85]: Cf. Pontificale Romanum, De Ordinatione
Episcopi, presbyterorum et diaconorum, editio typica altera, cap. III,
*De Ordin. diaconorum*, n. 200.

[^86]: Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 10.

[^87]: Cf. *ibidem*, n. 41; Second Vatican
Ecumenical Council, Dogmatic Constitution on the Church, *Lumen
gentium*, n. 11; Decree on the Ministry and Life of Priests,
*Presbyterorum ordinis*, nn. 2,5,6; Decree on the Pastoral Office of
Bishops, *Christus Dominus*, n. 30, Decree on Ecumenism, *Unitatis
redintegratio*, 21 November 1964, n. 15; S. Congregation of Rites,
Instruction *Eucharisticum mysterium*, nn. 3e, 6: AAS 59 (1967) pp. 542,
544-545; Missale Romanum, Institutio Generalis, n. 16.

[^88]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 26;
Missale Romanum, Institutio Generalis, n. 91.

[^89]: *1 Pet* 2,9; cf. 2,4-5.

[^90]: Missale Romanum, Institutio Generalis, n.
91; cf. Second Vatican Ecumenical Council, Constitution on the Sacred
Liturgy, *Sacrosanctum Concilium*, n. 41.

[^91]: Second Vatican Ecumenical Council,
Dogmatic Constitution on the Church, *Lumen gentium*, n. 10.

[^92]: Cf. St. Thomas Aquinas, *Summa
Theologica*, III, q. 63, a. 2.

[^93]: Second Vatican Ecumenical Council,
Dogmatic Constitution on the Church, *Lumen gentium*, n. 10; cf. Pope
John Paul II, Encyclical Letter *Ecclesia de Eucharistia*, n. 28: AAS 95
(2003) p. 452.

[^94]: Cf. *Acts* 2,42-47.

[^95]: Cf. *Rom* 12,1.

[^96]: Cf. *1 Pet* 3,15; 2,4-10.

[^97]: Cf. Pope John Paul II, Encyclical Letter
*Ecclesia de Eucharistia*, nn. 12-18: AAS 95 (2003) p. 441-445; Letter
*Dominicae Cenae*, 24 February 1980, n. 9: AAS 72 (1980) pp. 129-133.

[^98]: Pope John Paul II, Encyclical Letter
*Ecclesia de Eucharistia*, n. 10: AAS 95 (2003) p. 439.

[^99]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, nn. 30-31.

[^100]: Cf. S. Congregation for Divine Worship,
Instruction *Liturgicae instaurationes*, n. 1: AAS 62 (1970) p. 695.

[^101]: Cf. Missale Romanum, Feria secunda post
Dominica V in Quadragesima, Collecta, p. 258.

[^102]: Cf. Pope John Paul II, Apostolic Letter
*Novo Millennio ineunte*, 6 January 2001, n. 21: AAS 93 (2001) p. 280;
cf. *Jn* 20,28.

[^103]: Cf. Pope Pius XII, Encyclical Letter
*Mediator Dei*: AAS 39 (1947) p. 586; cf. also Second Vatican Ecumenical
Council, Dogmatic Constitution on the Church, *Lumen gentium*, n. 67;
Pope Paul VI, Apostolic Exhortation *Marialis cultus*, 11 February 1974,
n. 24: AAS 66 (1974) pp. 113-168, here p. 134; Congregation for Divine
Worship and the Discipline of the Sacraments, *Direttorio su pietà
popolare e Liturgia*, 17 December 2001.

[^104]: Pope John Paul II, Apostolic Letter,
*Rosarium Virginis Mariae*, 16 October 2002: AAS 95 (2003) pp. 5-36.

[^105]: Cf. Pope Pius XII, Encyclical Letter
*Mediator Dei*: AAS 39 (1947) p. 586-587.

[^106]: Cf. Congregation for Divine Worship and
the Discipline of the Sacraments, Instruction, *Varietates legitimae*,
n. 22: AAS 87 (1995) p. 297.

[^107]: Cf. Pope Pius XII, Encyclical Letter,
*Mediator Dei*: AAS 39 (1947) p. 553.

[^108]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia*, n. 29: AAS 95 (2003) p. 453; cf. Fourth
Lateran Ecumenical Council, 11-30 November 1215, Chapter I: DS 802;
Ecumenical Council of Trent, Session XXIII, 15 July 1563, Doctrine and
Canons on Sacred Order, Chapter 4: DS 1767-1770; Pope Pius XII,
Encyclical Letter, *Mediator Dei*: AAS 39 (1947) p. 553.

[^109]: Cf. *Code of Canon Law*, can. 230 § 2;
cf. also the Missale Romanum, Institutio Generalis, n. 97.

[^110]: Cf. Missale Romanum, General
Instruction, n. 109.

[^111]: Cf. Pope Paul VI, Apostolic Letter
(Motu Proprio) *Ministeria quaedam*, 15 August 1972, nn. VI-XII;
Pontificale Romanum *ex decreto sacrosancti oecumenici Concilii Vaticani
II instauratum, auctoritate Pauli Pp. VI promulgatum*, De institutione
lectorum et acolythorum, de admissione inter candidatos ad diaconatum et
presbyteratum, de sacro caelibatu amplectendo, editio typica, 3 December
1972, Typis Polyglottis Vaticanis, 1973, p. 10: AAS 64 (1972) pp.
529-534, here pp. 532-533; *Code of Canon Law*, can. 230 §1; Missale
Romanum, Institutio Generalis, nn. 98-99, 187-193.

[^112]: Cf. Missale Romanum, Institutio
Generalis, nn. 187-190, 193; *Code of Canon Law*, can. 230 §2-3.

[^113]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 24; S.
Congregation for the Sacraments and Divine Worship, Instruction,
*Inaestimabile donum*, nn. 2 and 18: AAS 72 (1980) pp. 334, 338; Missale
Romanum, Institutio Generalis, nn. 101, 194-198; *Code of Canon Law*,
can 230 §2-3.

[^114]: Cf. Missale Romanum, Institutio
Generalis, nn. 100-107.

[^115]: *Ibidem*, n. 91; cf. Second Vatican
Ecumenical Council, Constitution on the Sacred Liturgy, *Sacrosanctum
Concilium*, n. 28.

[^116]: Cf. Pope John Paul II, Allocution to
the Conference of Bishops of the Antilles, 7 May 2002, n. 2: AAS 94
(2002) pp. 575-577; Post-Synodal Apostolic Exhortation, *Christifideles
laici*, 30 December 1988, n. 23: AAS 81 (1989) pp. 393-521, here pp.
429-431; Congregation for the Clergy et al., Instruction, *Ecclesiae de
mysterio*, 15 August 1997, Theological Principles, n. 4: AAS 89 (1997)
pp. 860-861.

[^117]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 19.

[^118]: S. Congregation for Divine Worship,
Instruction, *Immensae caritatis*, 29 January 1973: AAS 65 (1973) p.
266.

[^119]: Cf. S. Congregation of Rites,
Instruction, *De Musica sacra*, 3 September 1958, n. 93c: AAS 50 (1958)
p. 656.

[^120]: Cf. Pontifical Council for the
Interpretation of Legislative Texts, Response to dubium, 11 July 1992:
AAS 86 (1994) pp. 541-542; Congregation for Divine Worship and the
Discipline of the Sacraments, Letter to the Presidents of Conferences of
Bishops on the liturgical service of laypersons, 15 March 1994:
*Notitiae* 30 (1994) pp. 333-335, 347-348.

[^121]: Cf. Pope John Paul II, Apostolic
Constitution, *Pastor Bonus*, art. 65: AAS 80 (1988) p. 877.

[^122]: Cf. Pontifical Council for the
Interpretation of Legislative Texts, Response to dubium, 11 July 1992:
AAS 86 (1994) pp. 541-542; Congregation for Divine Worship and the
Discipline of the Sacraments, Letter to the Presidents of the
Conferences of Bishops concerning the liturgical service of laypersons,
15 March 1994: *Notitiae* 30 (1994) pp. 333-335, 347-348; Letter to a
Bishop, 27 July 2001: *Notitiae* 38 (2002) 46-54.

[^123]: Cf. *Code of Canon Law*, can. 924 §2;
Missale Romanum, Institutio Generalis, n. 320.

[^124]: Cf. S. Congregation for the Discipline
of the Sacraments, Instruction, *Dominus Salvator noster*, 26 March
1929, n. 1: AAS 21 (1929) pp. 631-642, here p. 632.

[^125]: Cf. *ibidem*, n. II: AAS 21 (1929) p.
635.

[^126]: Cf. Missale Romanum, Institutio
Generalis, n. 321.

[^127]: Cf. Lk 22,18; *Code of Canon Law*, can.
924 §§ 1, 3; Missale Romanum, Institutio Generalis, n. 322.

[^128]: Cf. Missale Romanum, Institutio
Generalis, n. 323.

[^129]: Pope John Paul II, Apostolic Letter,
*Vicesimus quintus annus*, n. 13, AAS 81 (1989)

[^130]: S. Congregation for the Sacraments and
Divine Worship, Instruction, *Inaestimabile donum*, n. 5: AAS 72 (1980)
pp. 335.

[^131]: Cf. Pope John Paul II, Encyclical
Letter, *Ecclesia de Eucharistia*, n. 28: AAS 95 (2003) p. 452; Missale
Romanum, Institutio Generalis, n. 147; S. Congregation for Divine
Worship, Instruction, *Liturgicae instaurationes*, n. 4: AAS 62 (1970)
p. 698; S. Congregation for the Sacraments and Divine Worship,
Instruction, *Inaestimabile donum*, n. 4: AAS 72 (1980) p. 334.

[^132]: Missale Romanum, Institutio Generalis,
n. 32.

[^133]: *Ibidem*, n. 147; cf. Pope John Paul
II, Encyclical Letter, *Ecclesia de Eucharistia*, n. 28: AAS 95 (2003)
p. 452; cf. also Congregation for the Sacraments and Divine Worship,
Instruction, *Inaestimabile donum*, n. 4: AAS 72 (1980) pp. 334-335.

[^134]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia*, n. 39: AAS 95 (2003) p. 459.

[^135]: Cf. S. Congregation for Divine Worship,
Instruction, *Liturgicae instaurationes*, n. 2b: AAS 62 (1970) p. 696.

[^136]: Cf. Missale Romanum, Institutio
Generalis, nn. 356-362.

[^137]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium*, n. 51.

[^138]: Missale Romanum, Institutio Generalis,
n. 57; cf. Pope John Paul II, Apostolic Letter, *Vicesimus quintus
annus*, n. 13: AAS 81 (1989) p. 910; Congregation for the Doctrine of
the Faith, Declaration, *Dominus Iesus*, on the unicity and salvific
universality of Jesus Christ and the Church, 6 August 2000: AAS 92
(2000) pp. 742-765.

[^139]: Missale Romanum, General Instruction,
n. 60.

[^140]: Cf. *ibidem*, nn. 59-60.

[^141]: Cf., e.g., Rituale Romanum, *ex decreto
sacrosancti Oecumenici Concilii Vaticani II renovatum, auctoritate Pauli
Pp. VI editum Ioannis Pauli Pp. II cura recognitum*: Ordo celebrandi
Matrimonium, editio typica altera, 19 March 1990, Typis Polyglottis
Vaticanis 1991, n. 125; Roman Ritual, renewed by decree of the Second
Vatican Ecumenical Council and promulgated by authority of Pope Paul VI:
Order for Anointing of the Sick and for their Pastoral Care, *editio
typica*, 7 December 1972, Vatican Polyglot Press, 1972, n. 72.

[^142]: Cf. *Code of Canon Law*, can 767 §1.

[^143]: Cf. Missale Romanum, Institutio
Generalis, n. 66; cf. also the *Code of Canon Law*, can. 6, §1, 2; also
can. 767 §1, regarding which other noteworthy prescriptions may be found
in Congregation for the Clergy et al., Instruction, *Ecclesiae de
mysterio*, Practical Provisions, art. 3 § 1: AAS 89 (1997) p. 865.

[^144]: Missale Romanum, Institutio Generalis,
n. 66; cf. also the *Code of Canon Law*, can 767 §1.

[^145]: Cf. Congregation for the Clergy et al.,
Instruction, *Ecclesiae de mysterio*, Practical Provisions, art. 3 §1:
AAS 89 (1997) p. 865; cf. also the *Code of Canon Law*, can. 6 §1, 2;
Pontifical Commission for the Authentic Interpretation of the Code of
Canon Law, Response to dubium, 20 June 1987: AAS 79 (1987) p. 1249.

[^146]: Cf. Congregation for the Clergy et al.,
Instruction, *Ecclesiae de mysterio*, Practical Provisions, art. 3 § 1:
AAS 89 (1997) pp. 864-865.

[^147]: Cf. Ecumenical Council of Trent,
Session XXII, 17 September 1562, on the Most Holy Sacrifice of the Mass,
Chapter 8: DS 1749; Missale Romanum, Institutio Generalis, n. 65.

[^148]: Cf. Pope John Paul II, Allocution to a
number of Bishops from the United States of America who had come to Rome
for a visit "ad Limina Apostolorum", 28 May 1993, n. 2: AAS 86 (1994) p.
330.

[^149]: Cf. *Code of Canon Law*, can. 386 §1.

[^150]: Cf. Missale Romanum, Institutio
Generalis, n. 73.

[^151]: Cf. *ibidem*, n. 154.

[^152]: Cf. *ibidem*, nn. 82, 154.

[^153]: Cf. *ibidem*, n. 83.

[^154]: Cf. S. Congregation for Divine Worship,
Instruction, *Liturgicae instaurationes*, n. 5: AAS 62 (1970) p. 699.

[^155]: Cf. Missale Romanum, Institutio
Generalis, nn. 83, 240, 321.

[^156]: Cf. Congregation For the Clergy et al.,
Instruction, *Ecclesiae de mysterio*, Practical Provisions, art. 3 §2:
AAS 89 (1997) p. 865.

[^157]: Cf. especially the General Instruction
of the Liturgy of the Hours, nn. 93-98; Roman Ritual, revised by decree
of the Second Vatican Ecumenical Council and published by authority of
Pope John Paul II: Book of Blessings, editio typica, 31 May 1984,
General Introduction, n. 28; Order of Crowning an Image of the Blessed
Virgin Mary, editio typica, 25 March 1981, nn. 10 and 14; S.
Congregation for Divine Worship, Instruction, on Masses with Particular
Groups, *Actio pastoralis*, 15 May 1969: AAS 61 (1969) pp. 806-811;
Directory for Masses with Children, Pueros baptizatos, 1 November
1973:AAS 66 (1974) pp. 30-46; Missale Romanum, Institutio Generalis, n.
21.

[^158]: Cf. Pope John Paul II, Apostolic Letter
(Motu Proprio), *Misericordia Dei*, 7 April 2002, n. 2: AAS 94 (2002) p.
455; Cf. Congregation for Divine Worship and the Discipline of the
Sacraments, Response to Dubium: *Notitiae* 37 (2001) pp. 259-260.

[^159]: Cf. S. Congregation for Divine Worship,
Instruction, *Liturgicae instaurationes*, n. 9: AAS 62 (1970) p. 702.

[^160]: Ecumenical Council of Trent, Session
XIII, 11 October 1551, Decree on the Most Holy Eucharist, Chapter 2: DS
1638; cf. Session XXII, 17 September 1562, On the Most Holy Sacrifice of
the Mass, Chapters 1-2: DS 1740, 1743; S. Congregation of Rites,
Instruction, *Eucharisticum mysterium,* n. 35: AAS 59 (1967) p. 560.

[^161]: Cf. Missale Romanum, Ordo Missae, n. 4,
p. 505.

[^162]: Missale Romanum, Institutio Generalis,
n. 51.

[^163]: Cf. *1 Cor* 11: 28.

[^164]: Cf. *Code of Canon Law,* can. 916; cf.
Ecumenical Council of Trent, Session XIII, 11 October 1551, Decree on
the Most Holy Eucharist, Chapter 7: DS 1646-1647; Pope John Paul II,
Encyclical Letter, *Ecclesia de Eucharistia,* n. 36: AAS 95 (2003) pp.
457-458; S. Congregation of Rites, Instruction, *Eucharisticum
mysterium,* n. 35: AAS 59 (1967) p. 561.

[^165]: Cf. Pope John Paul II, Encyclical
Letter, *Ecclesia de Eucharistia,* n. 42: AAS 95 (2003) p. 461.

[^166]: Cf. *Code of Canon Law*, n. 844 § 1;
Pope John Paul II, Encyclical Letter *Ecclesia de Eucharistia*, nn.
45-46: AAS 95 (2003) pp. 463-464; cf. also Pontifical Council for the
Promotion of Christian Unity, Directory for the application of the
principles and norms on ecumenism, *La recherche de l'unité*, nn.
130-131: AAS 85 (1993) 1039-1119, here p. 1089.

[^167]: Cf. Pope John Paul II, Encyclical
Letter *Ecclesia de Eucharistia*, n. 46: AAS 95 (2003) pp. 463-464.

[^168]: Cf. S. Congregation of Rites,
Instruction, *Eucharisticum mysterium,* n. 35: AAS 59 (1967) p. 561.

[^169]: Cf. *Code of Canon Law,* can. 914; S.
Congregation for the Discipline of the Sacraments, Declaration, *Sanctus
Pontifex*, diei 24 maii 1973: AAS 65 (1973) p. 410; S. Congregation for
the Sacraments and Divine Worship and S. Congregation for the Clergy,
Letter to the Presidents of the Bishops' Conferences. Episcoporum, *In
quibusdam*, 31 March 1977*: Enchiridion Documentorum Instaurationis
Liturgicae*, II, pp. 142-144; S. Congregation for the Sacraments and
Divine Worship and S. Congregation for the Clergy, Response to dubium,
20 May 1977: AAS 69 (1977) p. 427.

[^170]: Cf. Pope John Paul II, Apostolic
Letter, *Dies Domini*, 31 May 1998, nn. 31-34: AAS 90 (1998) pp.
713-766, here pp. 731-734.

[^171]: Cf. *Code of Canon Law*,can. 914.

[^172]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium,* n. 55.

[^173]: Cf. S. Congregation of Rites,
Instruction, *Eucharisticum mysterium,* n. 31: AAS 59 (1967) p. 558;
Pontifical Commission for the Authentic Interpretation of the Code of
Canon Law, Response to dubium, 1 June 1988: AAS 80 (1988) p. 1373.

[^174]: Missale Romanum, Institutio Generalis,
n. 85.

[^175]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium,* n. 55; S.
Congregation of Rites, Instruction, *Eucharisticum mysterium,* n. 31:
AAS 59 (1967) p. 558; Missale Romanum, Institutio Generalis, nn. 85,
157, 243.

[^176]: Cf. Missale Romanum, Institutio
Generalis, n. 160.

[^177]: *Code of Canon Law*, can. 843 § 1; cf.
can. 915.

[^178]: Cf. Missale Romanum, Institutio
Generalis, n. 161.

[^179]: Congregation for Divine Worship and the
Discipline of the Sacraments, Dubium: *Notitiae* 35 (1999) pp. 160-161.

[^180]: Cf. Missale Romanum, Institutio
Generalis, n. 118.

[^181]: *Ibidem*, n. 160.

[^182]: Cf. *Code of Canon Law,* can. 917;
Pontifical Commission for the Authentic Interpretation of the Code of
Canon Law, Response to Dubium, 11 July 1984: AAS 76 (1984) p. 746.

[^183]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium,* n. 55;
Missale Romanum, General Instruction, nn. 158-160, 243-244, 246.

[^184]: Cf. Missale Romanum, Institutio
Generalis, nn. 237-249; cf. also nn. 85, 157.

[^185]: Cf. *ibidem*, n. 283a.

[^186]: Cf. Ecumenical Council of Trent,
Session XXI, 16 July 1562, Decree on Eucharistic Communion, Chapters
1-3: DS 1725-1729; Second Vatican Ecumenical Council, Constitution on
the Sacred Liturgy, *Sacrosanctum Concilium,* n. 55; Missale Romanum,
Institutio Generalis, nn. 282-283.

[^187]: Cf. Missale Romanum, Institutio
Generalis, n. 283.

[^188]: Cf. *ibidem*.

[^189]: Cf. S. Congregation for Divine
Worship,Instruction, *Sacramentali Communione,* 29 June 1970: AAS 62
(1970) p. 665;Instruction, *Liturgicae instaurationes,* n. 6a: AAS 62
(1970) p. 699.

[^190]: Missale Romanum, Institutio Generalis,
n. 285a.

[^191]: *Ibidem*, n. 245.

[^192]: Cf. *ibidem*, nn. 285b and 287.

[^193]: Cf. *ibidem*, nn. 207 and 285a.

[^194]: Cf. *Code of Canon Law*, can. 1367.

[^195]: Cf. Pontifical Council for the
Interpretation of Legislative Texts, Response to dubium, 3 July 1999:
AAS 91 (1999) p. 918.

[^196]: Cf. Missale Romanum, Institutio
Generalis, nn. 163, 284.

[^197]: *Code of Canon Law,* can. 932 § 1; S.
Congregation for Divine Worship, Instruction, *Liturgicae
instaurationes,* n. 9: AAS 62 (1970) p. 701.

[^198]: *Code of Canon Law,* can. 904; cf.
Second Vatican Ecumenical Council, Dogmatic Constitution on the Church,
*Lumen gentium*, n. 3; Decree on the Ministry and Life of Priests,
*Presbyterorum ordinis,* n. 13; cf. also Ecumenical Council of Trent,
Session XXII, 17 September 1562, On the Most Holy Sacrifice of the Mass,
Chapter6: DS 1747; Pope Paul Pp. VI, Encyclical Letter *Mysterium
fidei,* 3 September 1965: AAS 57 (1965) pp. 753-774, here pp. 761-762;
cf. Pope John Paul II, Encyclical Letter, *Ecclesia de Eucharistia,* n.
11: AAS 95 (2003) pp. 440-441; S. Congregation of Rites, Instruction,
*Eucharisticum mysterium,* n. 44: AAS 59 (1967) p. 564; Missale Romanum,
Institutio Generalis, n. 19.

[^199]: Cf. *Code of Canon Law,* can. 903;
Missale Romanum, Institutio Generalis, n. 200.

[^200]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium,* n. 36 § 1;
*Code of Canon Law,* can. 928.

[^201]: Cf.Missale Romanum, Institutio
Generalis, n. 114.

[^202]: Pope John Paul II, Apostolic Letter
*Dies Domini*, n. 36: AAS 90 (1998) p. 735; cf. also S. Congregation of
Rites, Instruction *Eucharisticum mysterium*, n. 27: AAS 59 (1967) p.
556.

[^203]: Cf. Pope John Paul II, Apostolic Letter
*Dies Domini*, esp. n. 36: AAS 90 (1998) pp. 713-766, here pp. 735-736;
S. Congregation for Divine Worship, Instruction *Actio pastoralis*: AAS
61 (1969) pp. 806-811.

[^204]: Cf. *Code of Canon Law,* cann. 905,
945-958; cf. Congregation for the Clergy, Decree, *Mos iugiter*, 22
February 1991: AAS 83 (1991), pp. 443-446.

[^205]: Cf. Missale Romanum, Institutio
Generalis, nn. 327-333.

[^206]: Cf. *ibidem*, n. 332.

[^207]: Cf. *ibidem*, n. 332; Congregation for
Divine Worship and the Discipline of the Sacraments,, Instruction,
*Inaestimabile donum,* n. 16: AAS 72 (1980) p. 338.

[^208]: Cf. Missale Romanum, Institutio
Generalis, n. 333; Appendix IV. *Ordo benedictionis calicis et patenae
intra Missam adhibendus*, pp. 1255-1257; Pontificale Romanum *ex decreto
sacrosancti Oecumenici Concilii Vaticani II instauratum, auctoritate
Pauli P*p*. VI promulgatum,* Ordo Dedicationis ecclesiae et altaris,
editio typica, diei 29 maii 1977, Typis Polyglottis Vaticanis, 1977,
cap. VII, pp. 125-132.

[^209]: Cf. Missale Romanum*,* Institutio
Generalis, nn. 163, 183, 192.

[^210]: *Ibidem,* n. 345.

[^211]: *Ibidem,* n. 335.

[^212]: Cf. *ibidem,* n. 336.

[^213]: Cf. *ibidem,* n. 337.

[^214]: Cf. *ibidem,* n. 209.

[^215]: Cf. *ibidem,* n. 338.

[^216]: Cf. S. Congregation for Divine Worship,
Instruction, *Liturgicae Instaurationes,* n. 8c: AAS 62 (1970) p. 701.

[^217]: Cf. Missale Romanum, Institutio
Generalis, n. 346g.

[^218]: *Ibidem,* n. 114 cf. nn. 16-17.

[^219]: S. Congregation for Divine Worship,
Decree, *Eucharistiae sacramentum,* 21 June 1973: AAS 65 (1973) 610.

[^220]: Cf. *ibidem*.

[^221]: Cf. S. Congregation of Rites,
Instruction, *Eucharisticum mysterium,* n. 54: AAS 59 (1967) p. 568;
Instruction, *Inter Oecumenici,* 26 September 1964, n. 95: AAS 56 (1964)
pp. 877-900, here p. 898; Missale Romanum, Institutio Generalis,n. 314.

[^222]: Cf. Pope John Paul II, Letter,
*Dominicae Cenae,* n. 3: AAS 72 (1980) pp. 117-119; S. Congregation of
Rites, Instruction, *Eucharisticum mysterium,* n. 53: AAS 59 (1967) p.
568; *Code of Canon Law,* can. 938 § 2; Roman Ritual, Holy Communion and
Worship of the Eucharist Outside Mass, *Introduction*, n. 9; Missale
Romanum, Institutio Generalis, nn. 314-317.

[^223]: Cf. *Code of Canon Law*, can. 938 §§
3-5.

[^224]: S. Congregation for the Discipline of
the Sacraments, Instruction, *Nullo unquam*, diei 26 maii 1938, n. 10d:
AAS 30 (1938), pp. 198-207, here p. 206.

[^225]: Cf. Pope John Paul II, Apostolic Letter
(Motu Proprio), *Sacramentorum sanctitatis tutela,* 30 April 2001: AAS
93 (2001) pp. 737-739; Congregation for the Doctrine of the Faith, Ep.
ad totius Catholicae Ecclesiae Episcopos aliosque Ordinarios et
Hierarchas quorum interest: de delictis gravioribus eidem Congregationi
pro Doctrina Fidei reservatis: AAS 93 (2001) p. 786.

[^226]: Cf. Roman Ritual, Holy Communion and
Worship of the Eucharist Outside Mass, nn. 26-78.

[^227]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia,* n. 25: AAS 95 (2003) pp. 449-450.

[^228]: Cf. Ecumenical Council of Trent,,
Sessio XIII, 11 October 1551, Decree on the Most Holy Eucharist, Chapter
5: DS 1643; Pius Pp. XII, Encyclical Letter *Mediator Dei*: AAS 39
(1947) p. 569; Pope Paul Pp. VI, Encyclical Letter *Mysterium Fidei*, 3
September 1965: AAS 57 (1965) pp. 751-774, here 769-770; S. Congregation
of Rites, Instruction, *Eucharisticum mysterium,* n. 3f: AAS 59 (1967)
p. 543; S. Congregation for the Sacraments and Divine Worship,
Instruction, *Inaestimabile donum,* n. 20: AAS 72 (1980) p. 339; Pope
John Paul II, Encyclical Letter, *Ecclesia de Eucharistia,* n. 25: AAS
95 (2003) pp. 449-450.

[^229]: Cf. *Heb* 9,:11; Pope John Paul II,
Encyclical Letter, *Ecclesia de Eucharistia,* n. 3: AAS 95 (2003) p.
435.

[^230]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia,* n. 25: AAS 95 (2003) p. 450.

[^231]: Pope Paul. VI, Encyclical Letter
*Mysterium fidei*: AAS 57 (1965) p. 771.

[^232]: Cf. Pope John Paul II, Encyclical
Letter, *Ecclesia de Eucharistia,* n. 25: AAS 95 (2003) pp. 449-450.

[^233]: *Code of Canon Law*, can. 937.

[^234]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia,* n. 10: AAS 95 (2003) p. 439.

[^235]: Cf. Roman Ritual, Holy Communion and
Worship of the Eucharist Outside Mass, nn. 82-100; Missale Romanum,
Institutio Generalis, n. 317; *Code of Canon Law,* can. 941 § 2.

[^236]: Pope John Paul II, Apostolic Letter,
*Rosarium Virginis Mariae,* diei 16 octobris 2002: AAS 95 (2003) pp.
5-36; here n. 2, p. 6.

[^237]: Cf. Congregation for Divine Worship and
the Discipline of the Sacraments, Letter of the Congregation, 15 January
1997: *Notitiae* 34 (1998) pp. 506-510; Apostolic Penitentiary, Letter
to a Priest, 8 March 1996: Notitiae 34 (1998) p. 511.

[^238]: Cf. S. Congregation of Rites,
Instruction, *Eucharisticum mysterium,* n. 61: AAS 59 (1967) p. 571;
Roman Ritual, Holy Communion and Worship of the Eucharist Outside Mass,
n. 83; Missale Romanum, Institutio Generalis, n. 317; *Code of Canon
Law,* can. 941 § 2.

[^239]: Cf. Roman Ritual, Holy Communion and
Worship of the Eucharist Outside Mass, n. 94.

[^240]: Cf. Pope John Paul II, Apostolic
Constitution, *Pastor bonus,* art. 65: AAS 80 (1988) p. 877.

[^241]: *Code of Canon Law,* can. 944 § 2; cf.
Roman Ritual, Holy Communion and Worship of the Eucharist Outside Mass,
Introduction, n. 102; Missale Romanum, Institutio Generalis, n. 317.

[^242]: *Code of Canon Law,* can. 944 § 1; cf.
Roman Ritual, Holy Communion and Worship of the Eucharist Outside Mass,
Introduction, nn. 101-102; Missale Romanum, Institutio Generalis, n.
317.

[^243]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia,* n. 10: AAS 95 (2003) p. 439

[^244]: Cf. Roman Ritual, Holy Communion and
Worship of the Eucharist Outside Mass, Introduction, n. 109.

[^245]: Cf. *ibidem,* nn. 109-112.

[^246]: Cf. Missale Romanum, In sollemnitate
sanctissimi Corporis et Sanguinis Christi, Collecta, p. 489.

[^247]: Cf. Congregation for the Clergy, and
others, Instruction, *Ecclesiae de mysterio,* Theological Principles, n.
3: AAS 89 (1997) p. 859.

[^248]: Cf. *Code of Canon Law,* can. 900 § 1;
cf. Fourth Lateran Ecumenical Council, 11-30 November 1215, Chapter 1:
DS802; Pope Clement VI, Letter to Mekhitar, Catholicos of the Armenians,
*Super quibusdam,* 29 September 1351: DS 1084; Ecumenical Council of
Trent, Sessio XXIII, 15 July 1563, Doctrine and Canons on Sacred
Orders., Chapter 4: DS 1767-1770; Pope Pius XII, Encyclical Letter,
*Mediator Dei*: AAS 39 (1947) p. 553.

[^249]: Cf. *Code of Canon Law,* can. 230 § 3;
Pope John Paul II, Allocution during a Symposium concerning the
collaboration of laypersons in the pastoral ministry of Priests, 22
April 1994, n. 2: *L'Osservatore Romano,* 23 April 1994; Congregation
for the Clergy et al., Instruction, *Ecclesiae de mysterio,* Prooemium:
AAS 89 (1997) pp. 852-856.

[^250]: Cf. Pope John Paul II, Encyclical
Letter, *Redemptoris missio,* nn. 53-54: *AAS* 83 (1991) pp. 300-302;
Congregation for the Clergy et al., Instruction, *Ecclesiae de
mysterio,* Prooemium: AAS 89 (1997) pp. 852-856.

[^251]: Cf. Second Vatican Ecumenical Council,
Decree on the Missionary Activity of the Church, *Ad gentes*, 7 December
1965, n. 17; Pope John Paul II, Encyclical Letter *Redemptoris missio,*
n. 73: AAS 83 (1991) p. 321.

[^252]: Cf. Congregation for the Clergy et al.,
Instruction, *Ecclesiae de mysterio,* Practical Provisions, art. 8 § 2:
AAS 89 (1997) p. 872.

[^253]: Cf. Pope John Paul II, Encyclical
Letter, *Ecclesia de Eucharistia*, n. 32: AAS 95 (2003) p. 455.

[^254]: Cf. *Code of Canon Law,* can. 900 § 1.

[^255]: Cf. *ibidem,* can. 910 § 1; cf. also
Pope John Paul II, Letter, *Dominicae Cenae*, n. 11: AAS 72 (1980) p.
142; Congregation for the Clergy et al., Instruction, *Ecclesiae de
mysterio,* Practical Provisions, art. 8 § 1: AAS 89 (1997) pp. 870-871.

[^256]: Cf. *Code of Canon Law,* can. 230 § 3.

[^257]: Cf. S. Congregation for the Discipline
of the Sacraments, Instruction, *Immensae caritatis*, prooemium: AAS 65
(1973) p. 264; Pope Paul VI, Apostolic Letter (Motu Proprio),
*Ministeria quaedam*, 15 August 1972: AAS 64 (1972) p. 532; Missale
Romanum, Appendix III: Ritus ad deputandum ministrum sacrae Communionis
ad actum distribuendae, p. 1253; Congregation for the Clergy et al.,
Instruction, *Ecclesiae de mysterio,* Practical Provisions, art. 8 § 1:
AAS 89 (1997) p. 871.

[^258]: S. Congregation for the Sacraments and
Divine Worship, Instruction, *Inaestimabile donum,* n. 10: AAS 72 (1980)
p. 336; Pontifical Commission for the Authentic Interpretation of the
Code of Canon Law, Response to dubium, 11 July 1984: AAS 76 (1984) p.
746.

[^259]: Cf. S. Congregation for the Discipline
of the Sacraments, Instruction, *Immensae caritatis,* n. 1: AAS 65
(1973) pp. 264-271, here pp. 265-266; Pontifical Commission for the
Authentic Interpretation of the Code of Canon Law, Responsio ad
propositum dubium, 1 June 1988: AAS 80 (1988) p. 1373; Congregation for
the Clergy et al., Instruction, *Ecclesiae de mysterio,* Practical
Provisions, art. 8 § 2: AAS 89 (1997) p. 871.

[^260]: Cf. *Code of Canon Law,* can. 767 § 1.

[^261]: Cf. *ibidem,* can. 766.

[^262]: Cf. Congregation for the Clergy et al.,
Instruction, *Ecclesiae de mysterio,* Practical Provisions, art. 2 §§
3-4: AAS 89 (1997) p. 865.

[^263]: Cf. Pope John Paul II, Apostolic
Letter, *Dies Domini*, esp. nn. 31-51: AAS 90 (1998) pp. 713-766, here
pp. 731-746; Pope John Paul II, Apostolic Letter, *Novo Millennio
ineunte,* diei 6 ianuarii 2001, nn. 35-36: AAS 93 (2001) pp. 290-292;
Pope John Paul II, Encyclical Letter, *Ecclesia de Eucharistia*, n. 41:
AAS 95 (2003) pp. 460-461.

[^264]: Second Vatican Ecumenical Council,
Decree on the Ministry and Life of Priests, *Presbyterorum ordinis,* n.
6; cf. Pope John Paul II, Encyclical Letter, *Ecclesia de Eucharistia*,
nn. 22, 33: AAS 95 (2003) pp. 448, 455-456.

[^265]: Cf. S. Congregation of Rites,
Instruction, *Eucharisticum mysterium*, n. 26: AAS 59 (1967) pp.
555-556; Congregation for Divine Worship, Directory for Sunday
Celebrations in the Absence of a Priest, *Christi Ecclesia,* 2 June
1988, nn. 5 and 25: *Notitiae* 24 (1988) pp. 366-378, here pp. 367, 372.

[^266]: Cf. Congregation for Divine Worship,
Directory for Sunday Celebrations in the Absence of a Priest, *Christi
Ecclesia,* n. 18: *Notitiae* 24 (1988) p. 370.

[^267]: Cf. Pope John Paul II, Letter,
*Dominicae Cenae,* n. 2: AAS 72 (1980) p. 116.

[^268]: Cf. Pope John Paul II, Apostolic
Letter, *Dies Domini*, n. 49: AAS 90 (1998) p. 744; Encyclical Letter,
*Ecclesia de Eucharistia*, n. 41: AAS 95 (2003) pp. 460-461; *Code of
Canon Law,* cann. 1246-1247.

[^269]: Cf. *Code of Canon Law,* can. 1248 § 2;
Congregation for Divine Worship, Directory for Sunday Celebrations in
the Absence of a Priest, *Christi Ecclesia,* nn. 1-2: *Notitiae* 24
(1988) p. 366.

[^270]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia*, n. 33: AAS 95 (2003) pp. 455-456.

[^271]: Cf. Congregation for Divine Worship,
Directory for Sunday Celebrations in the Absence of a Priest, *Christi
Ecclesia,* n. 22: *Notitiae* 24 (1988) p. 371.

[^272]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia,* n. 30: AAS 95 (2003) pp. 453-454; cf. also
Pontifical Council for the Promotion of Christian Unity, Directory for
the application of the principles and norms on ecumenism, *La recherche
de l'unité*, 25 March 1993, n. 115: AAS 85 (1993) pp. 1039-1119, here p.
1085.

[^273]: Cf. Pontifical Council for the
Promotion of Christian Unity*,* Directory for the application of the
principles and norms on ecumenism, *La recherche de l'unité*, n. 115:
AAS 85 (1993) p. 1085.

[^274]: Cf. *Code of Canon Law,* can. 292;
Pontifical Council for the Interpretation of Legislative Texts,
Declaration de recta interpretatione can. 1335, secundae partis, C.I.C.,
15 May 1997, n. 3: AAS 90 (1998) p. 64.

[^275]: Cf. *Code of Canon Law,* cann. 976; 986
§ 2.

[^276]: Cf. Pontifical Council for the
Interpretation of Legislative Texts, Declaratio de recta interpretatione
can. 1335, secundae partis, C.I.C., 15 May 1997, nn. 1-2: AAS 90 (1998)
pp. 63-64.

[^277]: As regards Priests who have obtained
the dispensation from celibacy, cf. S. Congregation for the Doctrine of
the Faith, Normae de dispensatione a sacerdotali caelibatu ad instantiam
partis, *Normae substantiales*, 14 October 1980, art. 5; cf. also
Congregation for the Clergy et al., Instruction, *Ecclesiae de
mysterio,* Practical Provisions, art. 3 § 5: AAS 89 (1997) p. 865.

[^278]: St Thomas Aquinas, *Summa Theol.,* II,
2, q. 93, a. 1.

[^279]: Cf. Pope John Paul II, Apostolic
Letter, *Vicesimus quintus annus*, n. 15: AAS 81 (1989) p. 911; cf. also
Second Vatican Ecumenical Council, Constitution on the Sacred Liturgy,
*Sacrosanctum Concilium,* nn. 15-19.

[^280]: Cf. Pope John Paul II, Apostolic Letter
(Motu Proprio), *Sacramentorum sanctitatis tutela*: AAS 93 (2001) pp.
737-739; Congregation for the Doctrine of the Faith, Ep. ad totius
Catholicae Ecclesiae Episcopos aliosque Ordinarios et Hierarchas quorum
interest: de delictis gravioribus eidem Congregationi pro Doctrina Fidei
reservatis: AAS 93 (2001) p. 786.

[^281]: Cf. *Code of Canon Law,* can. 1367;
Pontifical Council for the Interpretation of Legislative Texts,
Responsio ad propositum dubium, 3 July 1999: AAS 91 (1999) p. 918;
Congregation for the Doctrine of the Faith, Ep. ad totius Catholicae
Ecclesiae Episcopos aliosque Ordinarios et Hierarchas quorum interest:
de delictis gravioribus eidem Congregationi pro Doctrina Fidei
reservatis: AAS 93 (2001) p. 786.

[^282]: Cf. *Code of Canon Law,* can. 1378 § 2
n. 1 et 1379; Congregation for the Doctrine of the Faith, Ep. ad totius
Catholicae Ecclesiae Episcopos aliosque Ordinarios et Hierarchas quorum
interest: de delictis gravioribus eidem Congregationi pro Doctrina Fidei
reservatis: AAS 93 (2001) p. 786.

[^283]: Cf. *Code of Canon Law,* can. 908 et
1365; Congregation for the Doctrine of the Faith, Ep. ad totius
Catholicae Ecclesiae Episcopos aliosque Ordinarios et Hierarchas quorum
interest: de delictis gravioribus eidem Congregationi pro Doctrina Fidei
reservatis: AAS 93 (2001) p. 786.

[^284]: Cf. *Code of Canon Law,* can. 927;
Congregation for the Doctrine of the Faith, Ep. ad totius Catholicae
Ecclesiae Episcopos aliosque Ordinarios et Hierarchas quorum interest:
de delictis gravioribus eidem Congregationi pro Doctrina Fidei
reservatis: AAS 93 (2001) p. 786.

[^285]: *Code of Canon Law*, can. 387.

[^286]: *Ibidem,* can. 838 § 4.

[^287]: *Ibidem,*can. 392.

[^288]: Cf. Pope John Paul II, Apostolic
Constitution, *Pastor bonus,* art. 52: AAS 80 (1988) p. 874.

[^289]: Cf. *ibidem,* n. 63: AAS 80 (1988) p.
876.

[^290]: Cf. *ibidem,* can. 1417 § 1.

[^291]: Pope John Paul II, Encyclical Letter,
*Ecclesia de Eucharistia,* n. 24: AAS 95 (2003) p. 449.

[^292]: Cf. *ibidem,* nn. 53-58: AAS 95 (2003)
pp. 469-472.

[^293]: Cf. Second Vatican Ecumenical Council,
Constitution on the Sacred Liturgy, *Sacrosanctum Concilium,* n. 14; cf.
also nn. 11, 41, et 48.

[^294]: Cf. S. Thomas Aquinas, *Summa Theol.*,
III, q. 64, a. 9 ad 1.

[^295]: Cf. Missale Romanum, Institutio
Generalis, n. 24.

