---
title: SACROSANCTUM CONCILIUM
subtitle: |
    | CONSTITUTION
    | ON THE SACRED LITURGY
    | ***SACROSANCTUM CONCILIUM***
    | SOLEMNLY PROMULGATED BY
    | HIS HOLINESS
    | POPE PAUL VI
    | ON DECEMBER 4, 1963
---
 

# **INTRODUCTION**

1\. This sacred Council has several aims in view: it desires to impart
an ever increasing vigor to the Christian life of the faithful; to adapt
more suitably to the needs of our own times those institutions which are
subject to change; to foster whatever can promote union among all who
believe in Christ; to strengthen whatever can help to call the whole of
mankind into the household of the Church. The Council therefore sees
particularly cogent reasons for undertaking the reform and promotion of
the liturgy.

2\. For the liturgy, \"through which the work of our redemption is
accomplished,\"[^1] most of all in the divine
sacrifice of the Eucharist, is the outstanding means whereby the
faithful may express in their lives, and manifest to others, the mystery
of Christ and the real nature of the true Church. It is of the essence
of the Church that she be both human and divine, visible and yet
invisibly equipped, eager to act and yet intent on contemplation,
present in this world and yet not at home in it; and she is all these
things in such wise that in her the human is directed and subordinated
to the divine, the visible likewise to the invisible, action to
contemplation, and this present world to that city yet to come, which we
seek[^2]. While the liturgy daily builds up those
who are within into a holy temple of the Lord, into a dwelling place for
God in the Spirit[^3], to the mature measure of
the fullness of Christ[^4], at the same time it
marvelously strengthens their power to preach Christ, and thus shows
forth the Church to those who are outside as a sign lifted up among the
nations[^5] under which the scattered children of
God may be gathered together[^6], until there is
one sheepfold and one shepherd[^7].

3\. Wherefore the sacred Council judges that the following principles
concerning the promotion and reform of the liturgy should be called to
mind, and that practical norms should be established.

Among these principles and norms there are some which can and should be
applied both to the Roman rite and also to all the other rites. The
practical norms which follow, however, should be taken as applying only
to the Roman rite, except for those which, in the very nature of things,
affect other rites as well.

4\. Lastly, in faithful obedience to tradition, the sacred Council
declares that holy Mother Church holds all lawfully acknowledged rites
to be of equal right and dignity; that she wishes to preserve them in
the future and to foster them in every way. The Council also desires
that, where necessary, the rites be revised carefully in the light of
sound tradition, and that they be given new vigor to meet the
circumstances and needs of modern times.

{{< pagebreak >}}

# CHAPTER I -- GENERAL PRINCIPLES FOR THE RESTORATION AND PROMOTION OF THE SACRED LITURGY

## 1. The Nature of the Sacred Liturgy and Its Importance in the Church\'s Life

[5]{#5}. God who \"wills that all men be saved and come to the knowledge
of the truth\" (1 Tim. 2:4), \"who in many and various ways spoke in
times past to the fathers by the prophets\" (Heb. 1:1), when the
fullness of time had come sent His Son, the Word made flesh, anointed by
the Holy Spirit, to preach the the gospel to the poor, to heal the
contrite of heart[^8], to be a \"bodily and
spiritual medicine\"[^9], the Mediator between
God and man[^10]. For His humanity, united with
the person of the Word, was the instrument of our salvation. Therefore
in Christ \"the perfect achievement of our reconciliation came forth,
and the fullness of divine worship was given to us\"
[^11].

The wonderful works of God among the people of the Old Testament were
but a prelude to the work of Christ the Lord in redeeming mankind and
giving perfect glory to God. He achieved His task principally by the
paschal mystery of His blessed passion, resurrection from the dead, and
the glorious ascension, whereby \"dying, he destroyed our death and,
rising, he restored our life\"[^12]. For it was
from the side of Christ as He slept the sleep of death upon the cross
that there came forth \"the wondrous sacrament of the whole Church\"
[^13].

6\. Just as Christ was sent by the Father, so also He sent the apostles,
filled with the Holy Spirit. This He did that, by preaching the gospel
to every creature[^14], they might proclaim
that the Son of God, by His death and resurrection, had freed us from
the power of Satan[^15] and from death, and
brought us into the kingdom of His Father. His purpose also was that
they might accomplish the work of salvation which they had proclaimed,
by means of sacrifice and sacraments, around which the entire liturgical
life revolves. Thus by baptism men are plunged into the paschal mystery
of Christ: they die with Him, are buried with Him, and rise with Him
[^16]; they receive the spirit of adoption as
sons \"in which we cry: Abba, Father\" ( Rom. 8 :15), and thus become
true adorers whom the Father seeks[^17]. In
like manner, as often as they eat the supper of the Lord they proclaim
the death of the Lord until He comes[^18]. For
that reason, on the very day of Pentecost, when the Church appeared
before the world, \"those who received the word\" of Peter \"were
baptized.\" And \"they continued steadfastly in the teaching of the
apostles and in the communion of the breaking of bread and in prayers .
. . praising God and being in favor with all the people\" (Acts
2:41-47). From that time onwards the Church has never failed to come
together to celebrate the paschal mystery: reading those things \"which
were in all the scriptures concerning him\" (Luke 24:27), celebrating
the eucharist in which \"the victory and triumph of his death are again
made present\"[^19], and at the same time
giving thanks \"to God for his unspeakable gift\" (2 Cor. 9:15) in
Christ Jesus, \"in praise of his glory\" (Eph. 1:12), through the power
of the Holy Spirit.

[7]{#7}. To accomplish so great a work, Christ is always present in His
Church, especially in her liturgical celebrations. He is present in the
sacrifice of the Mass, not only in the person of His minister, \"the
same now offering, through the ministry of priests, who formerly offered
himself on the cross\"[^20], but especially
under the Eucharistic species. By His power He is present in the
sacraments, so that when a man baptizes it is really Christ Himself who
baptizes[^21]. He is present in His word, since
it is He Himself who speaks when the holy scriptures are read in the
Church. He is present, lastly, when the Church prays and sings, for He
promised: \"Where two or three are gathered together in my name, there
am I in the midst of them\" (Matt. 18:20) .

Christ indeed always associates the Church with Himself in this great
work wherein God is perfectly glorified and men are sanctified. The
Church is His beloved Bride who calls to her Lord, and through Him
offers worship to the Eternal Father.

Rightly, then, the liturgy is considered as an exercise of the priestly
office of Jesus Christ. In the liturgy the sanctification of the man is
signified by signs perceptible to the senses, and is effected in a way
which corresponds with each of these signs; in the liturgy the whole
public worship is performed by the Mystical Body of Jesus Christ, that
is, by the Head and His members.

From this it follows that every liturgical celebration, because it is an
action of Christ the priest and of His Body which is the Church, is a
sacred action surpassing all others; no other action of the Church can
equal its efficacy by the same title and to the same degree.

8\. In the earthly liturgy we take part in a foretaste of that heavenly
liturgy which is celebrated in the holy city of Jerusalem toward which
we journey as pilgrims, where Christ is sitting at the right hand of
God, a minister of the holies and of the true tabernacle
[^22]; we sing a hymn to the Lord\'s glory with
all the warriors of the heavenly army; venerating the memory of the
saints, we hope for some part and fellowship with them; we eagerly await
the Saviour, Our Lord Jesus Christ, until He, our life, shall appear and
we too will appear with Him in glory[^23].

9\. The sacred liturgy does not exhaust the entire activity of the
Church. Before men can come to the liturgy they must be called to faith
and to conversion: \"How then are they to call upon him in whom they
have not yet believed? But how are they to believe him whom they have
not heard? And how are they to hear if no one preaches? And how are men
to preach unless they be sent?\" (Rom. 10:14-15).

Therefore the Church announces the good tidings of salvation to those
who do not believe, so that all men may know the true God and Jesus
Christ whom He has sent, and may be converted from their ways, doing
penance[^24]. To believers also the Church must
ever preach faith and penance, she must prepare them for the sacraments,
teach them to observe all that Christ has commanded
[^25], and invite them to all the works of
charity, piety, and the apostolate. For all these works make it clear
that Christ\'s faithful, though not of this world, are to be the light
of the world and to glorify the Father before men.

[10]{#10}. Nevertheless the liturgy is the summit toward which the
activity of the Church is directed; at the same time it is the font from
which all her power flows. For the aim and object of apostolic works is
that all who are made sons of God by faith and baptism should come
together to praise God in the midst of His Church, to take part in the
sacrifice, and to eat the Lord\'s supper.

The liturgy in its turn moves the faithful, filled with \"the paschal
sacraments,\" to be \"one in holiness\"[^26];
it prays that \"they may hold fast in their lives to what they have
grasped by their faith\"[^27]; the renewal in
the Eucharist of the covenant between the Lord and man draws the
faithful into the compelling love of Christ and sets them on fire. From
the liturgy, therefore, and especially from the Eucharist, as from a
font, grace is poured forth upon us; and the sanctification of men in
Christ and the glorification of God, to which all other activities of
the Church are directed as toward their end, is achieved in the most
efficacious possible way.

[11]{#11}. But in order that the liturgy may be able to produce its full
effects, it is necessary that the faithful come to it with proper
dispositions, that their minds should be attuned to their voices, and
that they should cooperate with divine grace lest they receive it in
vain[^28] . Pastors of souls must therefore
realize that, when the liturgy is celebrated, something more is required
than the mere observation of the laws governing valid and licit
celebration; it is their duty also to ensure that the faithful take part
fully aware of what they are doing, actively engaged in the rite, and
enriched by its effects.

12\. The spiritual life, however, is not limited solely to participation
in the liturgy. The Christian is indeed called to pray with his
brethren, but he must also enter into his chamber to pray to the Father,
in secret[^29]; yet more, according to the
teaching of the Apostle, he should pray without ceasing
[^30]. We learn from the same Apostle that we
must always bear about in our body the dying of Jesus, so that the life
also of Jesus may be made manifest in our bodily frame
[^31]. This is why we ask the Lord in the
sacrifice of the Mass that, \"receiving the offering of the spiritual
victim,\" he may fashion us for himself \"as an eternal gift\"
[^32].

13\. Popular devotions of the Christian people are to be highly
commended, provided they accord with the laws and norms of the Church,
above all when they are ordered by the Apostolic See.

Devotions proper to individual Churches also have a special dignity if
they are undertaken by mandate of the bishops according to customs or
books lawfully approved.

But these devotions should be so drawn up that they harmonize with the
liturgical seasons, accord with the sacred liturgy, are in some fashion
derived from it, and lead the people to it, since, in fact, the liturgy
by its very nature far surpasses any of them.


{{< pagebreak >}}

## II. The Promotion of Liturgical Instruction and Active Participation

[14]{#14}. Mother Church earnestly desires that all the faithful should
be led to that fully conscious, and active participation in liturgical
celebrations which is demanded by the very nature of the liturgy. Such
participation by the Christian people as \"a chosen race, a royal
priesthood, a holy nation, a redeemed people (1 Pet. 2:9; cf. 2:4-5), is
their right and duty by reason of their baptism.

In the restoration and promotion of the sacred liturgy, this full and
active participation by all the people is the aim to be considered
before all else; for it is the primary and indispensable source from
which the faithful are to derive the true Christian spirit; and
therefore pastors of souls must zealously strive to achieve it, by means
of the necessary instruction, in all their pastoral work.

Yet it would be futile to entertain any hopes of realizing this unless
the pastors themselves, in the first place, become thoroughly imbued
with the spirit and power of the liturgy, and undertake to give
instruction about it. A prime need, therefore, is that attention be
directed, first of all, to the liturgical instruction of the clergy.
Wherefore the sacred Council has decided to enact as follows:

15\. Professors who are appointed to teach liturgy in seminaries,
religious houses of study, and theological faculties must be properly
trained for their work in institutes which specialize in this subject.

[16]{#16}. The study of sacred liturgy is to be ranked among the
compulsory and major courses in seminaries and religious houses of
studies; in theological faculties it is to rank among the principal
courses. It is to be taught under its theological, historical,
spiritual, pastoral, and juridical aspects. Moreover, other professors,
while striving to expound the mystery of Christ and the history of
salvation from the angle proper to each of their own subjects, must
nevertheless do so in a way which will clearly bring out the connection
between their subjects and the liturgy, as also the unity which
underlies all priestly training. This consideration is especially
important for professors of dogmatic, spiritual, and pastoral theology
and for those of holy scripture.

17\. In seminaries and houses of religious, clerics shall be given a
liturgical formation in their spiritual life. For this they will need
proper direction, so that they may be able to understand the sacred
rites and take part in them wholeheartedly; and they will also need
personally to celebrate the sacred mysteries, as well as popular
devotions which are imbued with the spirit of the liturgy. In addition
they must learn how to observe the liturgical laws, so that life in
seminaries and houses of religious may be thoroughly influenced by the
spirit of the liturgy.

18\. Priests, both secular and religious, who are already working in the
Lord\'s vineyard are to be helped by every suitable means to understand
ever more fully what it is that they are doing when they perform sacred
rites; they are to be aided to live the liturgical life and to share it
with the faithful entrusted to their care.

19\. With zeal and patience, pastors of souls must promote the
liturgical instruction of the faithful, and also their active
participation in the liturgy both internally and externally, taking into
account their age and condition, their way of life, and standard of
religious culture. By so doing, pastors will be fulfilling one of the
chief duties of a faithful dispenser of the mysteries of God; and in
this matter they must lead their flock not only in word but also by
example.

20\. Transmissions of the sacred rites by radio and television shall be
done with discretion and dignity, under the leadership and direction of
a suitable person appointed for this office by the bishops. This is
especially important when the service to be broadcast is the Mass.


{{< pagebreak >}}

## III. The Reform of the Sacred Liturgy

21\. In order that the Christian people may more certainly derive an
abundance of graces from the sacred liturgy, holy Mother Church desires
to undertake with great care a general restoration of the liturgy
itself. For the liturgy is made up of immutable elements divinely
instituted, and of elements subject to change. These not only may but
ought to be changed with the passage of time if they have suffered from
the intrusion of anything out of harmony with the inner nature of the
liturgy or have become unsuited to it.

In this restoration, both texts and rites should be drawn up so that
they express more clearly the holy things which they signify; the
Christian people, so far as possible, should be enabled to understand
them with ease and to take part in them fully, actively, and as befits a
community.

Wherefore the sacred Council establishes the following general norms:

### A) General norms

22\. 

1. Regulation of the sacred liturgy depends solely on the authority
of the Church, that is, on the Apostolic See and, as laws may determine,
on the bishop.

2. In virtue of power conceded by the law, the regulation of the
liturgy within certain defined limits belongs also to various kinds of
competent territorial bodies of bishops legitimately established.

3. Therefore no other person, even if he be a priest, may add, remove,
or change anything in the liturgy on his own authority.

23\. That sound tradition may be retained, and yet the way remain open
to legitimate progress careful investigation is always to be made into
each part of the liturgy which is to be revised. This investigation
should be theological, historical, and pastoral. Also the general laws
governing the structure and meaning of the liturgy must be studied in
conjunction with the experience derived from recent liturgical reforms
and from the indults conceded to various places. Finally, there must be
no innovations unless the good of the Church genuinely and certainly
requires them; and care must be taken that any new forms adopted should
in some way grow organically from forms already existing.

As far as possible, notable differences between the rites used in
adjacent regions must be carefully avoided.

24\. Sacred scripture is of the greatest importance in the celebration
of the liturgy. For it is from scripture that lessons are read and
explained in the homily, and psalms are sung; the prayers, collects, and
liturgical songs are scriptural in their inspiration and their force,
and it is from the scriptures that actions and signs derive their
meaning. Thus to achieve the restoration, progress, and adaptation of
the sacred liturgy, it is essential to promote that warm and living love
for scripture to which the venerable tradition of both eastern and
western rites gives testimony.

25\. The liturgical books are to be revised as soon as possible; experts
are to be employed on the task, and bishops are to be consulted, from
various parts of the world.

### B) Norms drawn from the hierarchic and communal nature of the Liturgy

26\. Liturgical services are not private functions, but are celebrations
of the Church, which is the \"sacrament of unity,\" namely, the holy
people united and ordered under their bishops
[^33]

Therefore liturgical services pertain to the whole body of the Church;
they manifest it and have effects upon it; but they concern the
individual members of the Church in different ways, according to their
differing rank, office, and actual participation.

27\. It is to be stressed that whenever rites, according to their
specific nature, make provision for communal celebration involving the
presence and active participation of the faithful, this way of
celebrating them is to be preferred, so far as possible, to a
celebration that is individual and quasi-private.

This applies with especial force to the celebration of Mass and the
administration of the sacraments, even though every Mass has of itself a
public and social nature.

28\. In liturgical celebrations each person, minister or layman, who has
an office to perform, should do all of, but only, those parts which
pertain to his office by the nature of the rite and the principles of
liturgy.

29\. Servers, lectors commentators, and members of the choir also
exercise a genuine liturgical function. They ought, therefore, to
discharge their office with the sincere piety and decorum demanded by so
exalted a ministry and rightly expected of them by God\'s people.

Consequently they must all be deeply imbued with the spirit of the
liturgy, each in his own measure, and they must be trained to perform
their functions in a correct and orderly manner.

30\. To promote active participation, the people should be encouraged to
take part by means of acclamations, responses, psalmody, antiphons, and
songs, as well as by actions, gestures, and bodily attitudes. And at the
proper times all should observe a reverent silence.

31\. The revision of the liturgical books must carefully attend to the
provision of rubrics also for the people\'s parts.

32\. The liturgy makes distinctions between persons according to their
liturgical function and sacred Orders, and there are liturgical laws
providing for due honors to be given to civil authorities. Apart from
these instances, no special honors are to be paid in the liturgy to any
private persons or classes of persons, whether in the ceremonies or by
external display.

### C) Norms based upon the didactic and pastoral nature of the Liturgy

[33]{#33}. Although the sacred liturgy is above all things the worship
of the divine Majesty, it likewise contains much instruction for the
faithful[^34]. For in the liturgy God speaks to
His people and Christ is still proclaiming His gospel. And the people
reply to God both by song and prayer.

Moreover, the prayers addressed to God by the priest who presides over
the assembly in the person of Christ are said in the name of the entire
holy people and of all present. And the visible signs used by the
liturgy to signify invisible divine things have been chosen by Christ or
the Church. Thus not only when things are read \"which were written for
our instruction\" (Rom. 15:4), but also when the Church prays or sings
or acts, the faith of those taking part is nourished and their minds are
raised to God, so that they may offer Him their rational service and
more abundantly receive His grace.

Wherefore, in the revision of the liturgy, the following general norms
should be observed:

34\. The rites should be distinguished by a noble simplicity; they
should be short, clear, and unencumbered by useless repetitions; they
should be within the people\'s powers of comprehension, and normally
should not require much explanation.

35\. That the intimate connection between words and rites may be
apparent in the liturgy:

1) In sacred celebrations there is to be more reading from holy
scripture, and it is to be more varied and suitable.

2) Because the sermon is part of the liturgical service, the best place
for it is to be indicated even in the rubrics, as far as the nature of
the rite will allow; the ministry of preaching is to be fulfilled with
exactitude and fidelity. The sermon, moreover, should draw its content
mainly from scriptural and liturgical sources, and its character should
be that of a proclamation of God\'s wonderful works in the history of
salvation, the mystery of Christ, ever made present and active within
us, especially in the celebration of the liturgy.

3) Instruction which is more explicitly liturgical should also be given
in a variety of ways; if necessary, short directives to be spoken by the
priest or proper minister should be provided within the rites
themselves. But they should occur only at the more suitable moments, and
be in prescribed or similar words.

4) Bible services should be encouraged, especially on the vigils of the
more solemn feasts, on some weekdays in Advent and Lent, and on Sundays
and feast days. They are particularly to be commended in places where no
priest is available; when this is so, a deacon or some other person
authorized by the bishop should preside over the celebration.

36\. 

1. Particular law remaining in force, the use of the Latin language
is to be preserved in the Latin rites.

2. But since the use of the mother tongue, whether in the Mass, the
administration of the sacraments, or other parts of the liturgy,
frequently may be of great advantage to the people, the limits of its
employment may be extended. This will apply in the first place to the
readings and directives, and to some of the prayers and chants,
according to the regulations on this matter to be laid down separately
in subsequent chapters.

3. These norms being observed, it is for the competent territorial
ecclesiastical authority mentioned in Art. 22, 2, to decide whether, and
to what extent, the vernacular language is to be used; their decrees are
to be approved, that is, confirmed, by the Apostolic See. And, whenever
it seems to be called for, this authority is to consult with bishops of
neighboring regions which have the same language.

4. Translations from the Latin text into the mother tongue intended for
use in the liturgy must be approved by the competent territorial
ecclesiastical authority mentioned above.

### D) Norms for adapting the Liturgy to the culture and traditions of peoples

37\. Even in the liturgy, the Church has no wish to impose a rigid
uniformity in matters which do not implicate the faith or the good of
the whole community; rather does she respect and foster the genius and
talents of the various races and peoples. Anything in these peoples\'
way of life which is not indissolubly bound up with superstition and
error she studies with sympathy and, if possible, preserves intact.
Sometimes in fact she admits such things into the liturgy itself, so
long as they harmonize with its true and authentic spirit.

38\. Provisions shall also be made, when revising the liturgical books,
for legitimate variations and adaptations to different groups, regions,
and peoples, especially in mission lands, provided that the substantial
unity of the Roman rite is preserved; and this should be borne in mind
when drawing up the rites and devising rubrics.

39\. Within the limits set by the typical editions of the liturgical
books, it shall be for the competent territorial ecclesiastical
authority mentioned in Art. 22, 2, to specify adaptations, especially in
the case of the administration of the sacraments, the sacramentals,
processions, liturgical language, sacred music, and the arts, but
according to the fundamental norms laid down in this Constitution.

40\. In some places and circumstances, however, an even more radical
adaptation of the liturgy is needed, and this entails greater
difficulties. Wherefore:

1) The competent territorial ecclesiastical authority mentioned in Art.
22, 2, must, in this matter, carefully and prudently consider which
elements from the traditions and culture of individual peoples might
appropriately be admitted into divine worship. Adaptations which are
judged to be useful or necessary should then be submitted to the
Apostolic See, by whose consent they may be introduced.

2) To ensure that adaptations may be made with all the circumspection
which they demand, the Apostolic See will grant power to this same
territorial ecclesiastical authority to permit and to direct, as the
case requires, the necessary preliminary experiments over a determined
period of time among certain groups suited for the purpose.

3) Because liturgical laws often involve special difficulties with
respect to adaptation, particularly in mission lands, men who are
experts in these matters must be employed to formulate them.

### E) Promotion of Liturgical Life in Diocese and Parish

41\. The bishop is to be considered as the high priest of his flock,
from whom the life in Christ of his faithful is in some way derived and
dependent.

Therefore all should hold in great esteem the liturgical life of the
diocese centered around the bishop, especially in his cathedral church;
they must be convinced that the pre-eminent manifestation of the Church
consists in the full active participation of all God\'s holy people in
these liturgical celebrations, especially in the same eucharist, in a
single prayer, at one altar, at which there presides the bishop
surrounded by his college of priests and by his ministers
[^35].

42\. But because it is impossible for the bishop always and everywhere
to preside over the whole flock in his Church, he cannot do other than
establish lesser groupings of the faithful. Among these the parishes,
set up locally under a pastor who takes the place of the bishop, are the
most important: for in some manner they represent the visible Church
constituted throughout the world.

And therefore the liturgical life of the parish and its relationship to
the bishop must be fostered theoretically and practically among the
faithful and clergy; efforts also must be made to encourage a sense of
community within the parish, above all in the common celebration of the
Sunday Mass.

### F) The Promotion of Pastoral-Liturgical Action

43\. Zeal for the promotion and restoration of the liturgy is rightly
held to be a sign of the providential dispositions of God in our time,
as a movement of the Holy Spirit in His Church. It is today a
distinguishing mark of the Church\'s life, indeed of the whole tenor of
contemporary religious thought and action.

So that this pastoral-liturgical action may become even more vigorous in
the Church, the sacred Council decrees:

44\. It is desirable that the competent territorial ecclesiastical
authority mentioned in Art. 22, 2, set up a liturgical commission, to be
assisted by experts in liturgical science, sacred music, art and
pastoral practice. So far as possible the commission should be aided by
some kind of Institute for Pastoral Liturgy, consisting of persons who
are eminent in these matters, and including laymen as circumstances
suggest. Under the direction of the above-mentioned territorial
ecclesiastical authority the commission is to regulate
pastoral-liturgical action throughout the territory, and to promote
studies and necessary experiments whenever there is question of
adaptations to be proposed to the Apostolic See.

45\. For the same reason every diocese is to have a commission on the
sacred liturgy under the direction of the bishop, for promoting the
liturgical apostolate.

Sometimes it may be expedient that several dioceses should form between
them one single commission which will be able to promote the liturgy by
common consultation.

46\. Besides the commission on the sacred liturgy, every diocese, as far
as possible, should have commissions for sacred music and sacred art.

These three commissions must work in closest collaboration; indeed it
will often be best to fuse the three of them into one single commission.

{{< pagebreak >}}

# CHAPTER II -- THE MOST SACRED MYSTERY OF THE EUCHARIST

47\. At the Last Supper, on the night when He was betrayed, our Saviour
instituted the eucharistic sacrifice of His Body and Blood. He did this
in order to perpetuate the sacrifice of the Cross throughout the
centuries until He should come again, and so to entrust to His beloved
spouse, the Church, a memorial of His death and resurrection: a
sacrament of love, a sign of unity, a bond of charity
[^36], a paschal banquet in which Christ is
eaten, the mind is filled with grace, and a pledge of future glory is
given to us[^37].

48\. The Church, therefore, earnestly desires that Christ\'s faithful,
when present at this mystery of faith, should not be there as strangers
or silent spectators; on the contrary, through a good understanding of
the rites and prayers they should take part in the sacred action
conscious of what they are doing, with devotion and full collaboration.
They should be instructed by God\'s word and be nourished at the table
of the Lord\'s body; they should give thanks to God; by offering the
Immaculate Victim, not only through the hands of the priest, but also
with him, they should learn also to offer themselves; through Christ the
Mediator[^38], they should be drawn day by day
into ever more perfect union with God and with each other, so that
finally God may be all in all.

49\. For this reason the sacred Council, having in mind those Masses
which are celebrated with the assistance of the faithful, especially on
Sundays and feasts of obligation, has made the following decrees in
order that the sacrifice of the Mass, even in the ritual forms of its
celebration, may become pastorally efficacious to the fullest degree.

50\. The rite of the Mass is to be revised in such a way that the
intrinsic nature and purpose of its several parts, as also the
connection between them, may be more clearly manifested, and that devout
and active participation by the faithful may be more easily achieved.

For this purpose the rites are to be simplified, due care being taken to
preserve their substance; elements which, with the passage of time, came
to be duplicated, or were added with but little advantage, are now to be
discarded; other elements which have suffered injury through accidents
of history are now to be restored to the vigor which they had in the
days of the holy Fathers, as may seem useful or necessary.

51\. The treasures of the bible are to be opened up more lavishly, so
that richer fare may be provided for the faithful at the table of God\'s
word. In this way a more representative portion of the holy scriptures
will be read to the people in the course of a prescribed number of
years.

52\. By means of the homily the mysteries of the faith and the guiding
principles of the Christian life are expounded from the sacred text,
during the course of the liturgical year; the homily, therefore, is to
be highly esteemed as part of the liturgy itself; in fact, at those
Masses which are celebrated with the assistance of the people on Sundays
and feasts of obligation, it should not be omitted except for a serious
reason.

53\. Especially on Sundays and feasts of obligation there is to be
restored, after the Gospel and the homily, \"the common prayer\" or
\"the prayer of the faithful.\" By this prayer, in which the people are
to take part, intercession will be made for holy Church, for the civil
authorities, for those oppressed by various needs, for all mankind, and
for the salvation of the entire world[^39].

54\. In Masses which are celebrated with the people, a suitable place
may be allotted to their mother tongue. This is to apply in the first
place to the readings and \"the common prayer,\" but also, as local
conditions may warrant, to those parts which pertain to the people,
according to the norm laid down in Art. 36 of this Constitution.

Nevertheless steps should be taken so that the faithful may also be able
to say or to sing together in Latin those parts of the Ordinary of the
Mass which pertain to them.

And wherever a more extended use of the mother tongue within the Mass
appears desirable, the regulation laid down in Art. 40 of this
Constitution is to be observed.

55\. That more perfect form of participation in the Mass whereby the
faithful, after the priest\'s communion, receive the Lord\'s body from
the same sacrifice, is strongly commended.

The dogmatic principles which were laid down by the Council of Trent
remaining intact[^40], communion under both
kinds may be granted when the bishops think fit, not only to clerics and
religious, but also to the laity, in cases to be determined by the
Apostolic See, as, for instance, to the newly ordained in the Mass of
their sacred ordination, to the newly professed in the Mass of their
religious profession, and to the newly baptized in the Mass which
follows their baptism.

56\. The two parts which, in a certain sense, go to make up the Mass,
namely, the liturgy of the word and the eucharistic liturgy, are so
closely connected with each other that they form but one single act of
worship. Accordingly this sacred Synod strongly urges pastors of souls
that, when instructing the faithful, they insistently teach them to take
their part in the entire Mass, especially on Sundays and feasts of
obligation.

{{< pagebreak >}} <!-- don't have a pagebreak in this intricate list -->

57\. 

1. Concelebration, whereby the unity of the priesthood is appropriately manifested, has remained in use to this day in the Church both in the east and in the west. For this reason it has seemed good to the Council to extend permission for concelebration to the following cases:
  
    1.
      
        a) on the Thursday of the Lord\'s Supper, not only at the Mass of the Chrism, but also at the evening Mass.
         
        b) at Masses during councils, bishops\' conferences, and synods;
         
        c) at the Mass for the blessing of an abbot.
        
    2. Also, with permission of the ordinary, to whom it belongs to decide whether concelebration is opportune:
      
        a) at conventual Mass, and at the principle Mass in churches when the needs of the faithful do not require that all priests available should celebrate individually;
         
        b) at Masses celebrated at any kind of priests\' meetings, whether the priests be secular clergy or religious.
      
2.  
  
    1. The regulation, however, of the discipline of con-celebration in the diocese pertains to the bishop.
     
    2. Nevertheless, each priest shall always retain his right to celebrate Mass individually, though not at the same time in the same church as a concelebrated Mass, nor on Thursday of the Lord\'s Supper.

58\. A new rite for concelebration is to be drawn up and inserted into
the Pontifical and into the Roman Missal.



{{< pagebreak >}}


# CHAPTER III -- THE OTHER SACRAMENTS AND THE SACRAMENTALS

59\. The purpose of the sacraments is to sanctify men, to build up the
body of Christ, and, finally, to give worship to God; because they are
signs they also instruct. They not only presuppose faith, but by words
and objects they also nourish, strengthen, and express it; that is why
they are called \"sacraments of faith.\" They do indeed impart grace,
but, in addition, the very act of celebrating them most effectively
disposes the faithful to receive this grace in a fruitful manner, to
worship God duly, and to practice charity.

It is therefore of the highest importance that the faithful should
easily understand the sacramental signs, and should frequent with great
eagerness those sacraments which were instituted to nourish the
Christian life.

60\. Holy Mother Church has, moreover, instituted sacramentals. These
are sacred signs which bear a resemblance to the sacraments: they
signify effects, particularly of a spiritual kind, which are obtained
through the Church\'s intercession. By them men are disposed to receive
the chief effect of the sacraments, and various occasions in life are
rendered holy.

61\. Thus, for well-disposed members of the faithful, the liturgy of the
sacraments and sacramentals sanctifies almost every event in their
lives; they are given access to the stream of divine grace which flows
from the paschal mystery of the passion, death, the resurrection of
Christ, the font from which all sacraments and sacramentals draw their
power. There is hardly any proper use of material things which cannot
thus be directed toward the sanctification of men and the praise of God.

62\. With the passage of time, however, there have crept into the rites
of the sacraments and sacramentals certain features which have rendered
their nature and purpose far from clear to the people of today; hence
some changes have become necessary to adapt them to the needs of our own
times. For this reason the sacred Council decrees as follows concerning
their revision.

63\. Because of the use of the mother tongue in the administration of
the sacraments and sacramentals can often be of considerable help to the
people, this use is to be extended according to the following norms:

a) The vernacular language may be used in administering the sacraments
and sacramentals, according to the norm of Art. 36.

b) In harmony with the new edition of the Roman Ritual, particular
rituals shall be prepared without delay by the competent territorial
ecclesiastical authority mentioned in Art. 22, 2, of this Constitution.
These rituals, which are to be adapted, also as regards the language
employed, to the needs of the different regions, are to be reviewed by
the Apostolic See and then introduced into the regions for which they
have been prepared. But in drawing up these rituals or particular
collections of rites, the instructions prefixed to the individual rites
the Roman Ritual, whether they be pastoral and rubrical or whether they
have special social import, shall not be omitted.

64\. The catechumenate for adults, comprising several distinct steps, is
to be restored and to be taken into use at the discretion of the local
ordinary. By this, means the time of the catechumenate, which is
intended as a period of suitable instruction, may be sanctified by
sacred rites to be celebrated at successive intervals of time.

65\. In mission lands it is found that some of the peoples already make
use of initiation rites. Elements from these, when capable of being
adapted to Christian ritual, may be admitted along with those already
found in Christian tradition, according to the norm laid down in Art.
37-40, of this Constitution.

66\. Both the rites for the baptism of adults are to be revised: not
only the simpler rite, but also the more solemn one, which must take
into account the restored catechumenate. A special Mass \"for the
conferring of baptism\" is to be inserted into the Roman Missal.

67\. The rite for the baptism of infants is to be revised, and it should
be adapted to the circumstance that those to be baptized are, in fact,
infants. The roles of parents and godparents, and also their duties,
should be brought out more clearly in the rite itself.

68\. The baptismal rite should contain variants, to be used at the
discretion of the local ordinary, for occasions when a very large number
are to be baptized together. Moreover, a shorter rite is to be drawn up,
especially for mission lands, to be used by catechists, but also by the
faithful in general when there is danger of death, and neither priest
nor deacon is available.

69\. In place of the rite called the \"Order of supplying what was
omitted in the baptism of an infant,\" a new rite is to be drawn up.
This should manifest more fittingly and clearly that the infant,
baptized by the short rite, has already been received into the Church.

And a new rite is to be drawn up for converts who have already been
validly baptized; it should indicate that they are now admitted to
communion with the Church.

70\. Except during Eastertide, baptismal water may be blessed within the
rite of baptism itself by an approved shorter formula.

71\. The rite of confirmation is to be revised and the intimate
connection which this sacrament has with the whole of Christian
initiation is to be more clearly set forth; for this reason it is
fitting for candidates to renew their baptismal promises just before
they are confirmed.

Confirmation may be given within the Mass when convenient; when it is
given outside the Mass, the rite that is used should be introduced by a
formula to be drawn up for this purpose.

72\. The rite and formulas for the sacrament of penance are to be
revised so that they more clearly express both the nature and effect of
the sacrament.

73\. \"Extreme unction,\" which may also and more fittingly be called
\"anointing of the sick,\" is not a sacrament for those only who are at
the point of death. Hence, as soon as any one of the faithful begins to
be in danger of death from sickness or old age, the fitting time for him
to receive this sacrament has certainly already arrived.

74\. In addition to the separate rites for anointing of the sick and for
viaticum, a continuous rite shall be prepared according to which the
sick man is anointed after he has made his confession and before he
receives viaticum.

75\. The number of the anointings is to be adapted to the occasion, and
the prayers which belong to the rite of anointing are to be revised so
as to correspond with the varying conditions of the sick who receive the
sacrament.

76\. Both the ceremonies and texts of the ordination rites are to be
revised. The address given by the bishop at the beginning of each
ordination or consecration may be in the mother tongue.

When a bishop is consecrated, the laying of hands may be done by all the
bishops present.

77\. The marriage rite now found in the Roman Ritual is to be revised
and enriched in such a way that the grace of the sacrament is more
clearly signified and the duties of the spouses are taught.

\"If any regions are wont to use other praiseworthy customs and
ceremonies when celebrating the sacrament of matrimony, the sacred Synod
earnestly desires that these by all means be retained\"
[^41].

Moreover the competent territorial ecclesiastical authority mentioned in
Art. 22, 52, of this Constitution is free to draw up its own rite suited
to the usages of place and people, according to the provision of Art.
63. But the rite must always conform to the law that the priest
assisting at the marriage must ask for and obtain the consent of the
contracting parties.

78\. Matrimony is normally to be celebrated within the Mass, after the
reading of the gospel and the homily, and before \"the prayer of the
faithful.\" The prayer for the bride, duly amended to remind both
spouses of their equal obligation to remain faithful to each other, may
be said in the mother tongue.

But if the sacrament of matrimony is celebrated apart from Mass, the
epistle and gospel from the nuptial Mass are to be read at the beginning
of the rite, and the blessing should always be given to the spouses.

79\. The sacramentals are to undergo a revision which takes into account
the primary principle of enabling the faithful to participate
intelligently, actively, and easily; the circumstances of our own days
must also be considered. When rituals are revised, as laid down in Art.
63, new sacramentals may also be added as the need for these becomes
apparent.

Reserved blessings shall be very few; reservations shall be in favor of
bishops or ordinaries.

Let provision be made that some sacramentals, at least in special
circumstances and at the discretion of the ordinary, may be administered
by qualified lay persons.

80\. The rite for the consecration of virgins at present found in the
Roman Pontifical is to be revised.

Moreover, a rite of religious profession and renewal of vows shall be
drawn up in order to achieve greater unity, sobriety, and dignity. Apart
from exceptions in particular law, this rite should be adopted by those
who make their profession or renewal of vows within the Mass.

Religious profession should preferably be made within the Mass.

81\. The rite for the burial of the dead should express more clearly the
paschal character of Christian death, and should correspond more closely
to the circumstances and traditions found in various regions. This holds
good also for the liturgical color to be used.

82\. The rite for the burial of infants is to be revised, and a special
Mass for the occasion should be provided.


{{< pagebreak >}}

# CHAPTER IV -- THE DIVINE OFFICE

83\. Christ Jesus, high priest of the new and eternal covenant, taking
human nature, introduced into this earthly exile that hymn which is sung
throughout all ages in the halls of heaven. He joins the entire
community of mankind to Himself, associating it with His own singing of
this canticle of divine praise.

For he continues His priestly work through the agency of His Church,
which is ceaselessly engaged in praising the Lord and interceding for
the salvation of the whole world. She does this, not only by celebrating
the eucharist, but also in other ways, especially by praying the divine
office.

84\. By tradition going back to early Christian times, the divine office
is devised so that the whole course of the day and night is made holy by
the praises of God. Therefore, when this wonderful song of praise is
rightly performed by priests and others who are deputed for this purpose
by the Church\'s ordinance, or by the faithful praying together with the
priest in the approved form, then it is truly the voice of the bride
addressed to her bridegroom; It is the very prayer which Christ Himself,
together with His body, addresses to the Father.

85\. Hence all who render this service are not only fulfilling a duty of
the Church, but also are sharing in the greatest honor of Christ\'s
spouse, for by offering these praises to God they are standing before
God\'s throne in the name of the Church their Mother.

86\. Priests who are engaged in the sacred pastoral ministry will offer
the praises of the hours with greater fervor the more vividly they
realize that they must heed St. Paul\'s exhortation: \"Pray without
ceasing\" (1 Thess. 5:11). For the work in which they labor will effect
nothing and bring forth no fruit except by the power of the Lord who
said: \"Without me you can do nothing\" (John 15: 5). That is why the
apostles, instituting deacons, said: \"We will devote ourselves to
prayer and to the ministry of the word\" (Acts 6:4).

81\. In order that the divine office may be better and more perfectly
prayed in existing circumstances, whether by priests or by other members
of the Church, the sacred Council, carrying further the restoration
already so happily begun by the Apostolic See, has seen fit to decree as
follows concerning the office of the Roman rite.

88\. Because the purpose of the office is to sanctify the day, the
traditional sequence of the hours is to be restored so that once again
they may be genuinely related to the time of the day when they are
prayed, as far as this may be possible. Moreover, it will be necessary
to take into account the modern conditions in which daily life has to be
lived, especially by those who are called to labor in apostolic works.

89\. Therefore, when the office is revised, these norms are to be
observed:

a) By the venerable tradition of the universal Church, Lauds as morning
prayer and Vespers as evening prayer are the two hinges on which the
daily office turns; hence they are to be considered as the chief hours
and are to be celebrated as such.

b) Compline is to be drawn up so that it will be a suitable prayer for
the end of the day.

c) The hour known as Matins, although it should retain the character of
nocturnal praise when celebrated in choir, shall be adapted so that it
may be recited at any hour of the day; it shall be made up of fewer
psalms and longer readings.

d) The hour of Prime is to be suppressed.

e) In choir the hours of Terce, Sext, and None are to be observed. But
outside choir it will be lawful to select any one of these three,
according to the respective time of the day.

90\. The divine office, because it is the public prayer of the Church,
is a source of piety, and nourishment for personal prayer. And therefore
priests and all others who take part in the divine office are earnestly
exhorted in the Lord to attune their minds to their voices when praying
it. The better to achieve this, let them take steps to improve their
understanding of the liturgy and of the bible, especially of the psalms.

In revising the Roman office, its ancient and venerable treasures are to
be so adapted that all those to whom they are handed on may more
extensively and easily draw profit from them.

91\. So that it may really be possible in practice to observe the course
of the hours proposed in Art. 89, the psalms are no longer to be
distributed throughout one week, but through some longer period of time.

The work of revising the psalter, already happily begun, is to be
finished as soon as possible, and is to take into account the style of
Christian Latin, the liturgical use of psalms, also when sung, and the
entire tradition of the Latin Church.

92\. As regards the readings, the following shall be observed: 

a) Readings from sacred scripture shall be arranged so that the riches of
God\'s word may be easily accessible in more abundant measure.

b) Readings excerpted from the works of the fathers, doctors, and
ecclesiastical writers shall be better selected.

c) The accounts of martyrdom or the lives of the saints are to accord
with the facts of history.

93\. To whatever extent may seem desirable, the hymns are to be restored
to their original form, and whatever smacks of mythology or ill accords
with Christian piety is to be removed or changed. Also, as occasion may
arise, let other selections from the treasury of hymns be incorporated.

94\. That the day may be truly sanctified, and that the hours themselves
may be recited with spiritual advantage, it is best that each of them be
prayed at a time which most closely corresponds with its true canonical
time.

95\. Communities obliged to choral office are bound to celebrate the
office in choir every day in addition to the conventual Mass. In
particular:

a) Orders of canons, of monks and of nuns, and of other regulars bound
by law or constitutions to choral office must celebrate the entire
office.

b) Cathedral or collegiate chapters are bound to recite those parts of
the office imposed on them by general or particular law.

c) All members of the above communities who are in major orders or who
are solemnly professed, except for lay brothers, are bound to recite
individually those canonical hours which they do not pray in choir.

96\. Clerics not bound to office in choir, if they are in major orders,
are bound to pray the entire office every day, either in common or
individually, as laid down in Art. 89.

97\. Appropriate instances are to be defined by the rubrics in which a
liturgical service may be substituted for the divine office.

In particular cases, and for a just reason, ordinaries can dispense
their subjects wholly or in part from the obligation of reciting the
divine office, or may commute the obligation.

98\. Members of any institute dedicated to acquiring perfection who,
according to their constitutions, are to recite any parts of the divine
office are thereby performing the public prayer of the Church.

They too perform the public prayer of the Church who, in virtue of their
constitutions, recite any short office, provided this is drawn up after
the pattern of the divine office and is duly approved.

99\. Since the divine office is the voice of the Church, that is of the
whole mystical body publicly praising God, those clerics who are not
obliged to office in choir, especially priests who live together or who
assemble for any purpose, are urged to pray at least some part of the
divine office in common.

All who pray the divine office, whether in choir or in common, should
fulfill the task entrusted to them as perfectly as possible: this refers
not only to the internal devotion of their minds but also to their
external manner of celebration.

It is, moreover, fitting that the office, both in choir and in common,
be sung when possible.

100\. Pastors of souls should see to it that the chief hours, especially
Vespers, are celebrated in common in church on Sundays and the more
solemn feasts. And the laity, too, are encouraged to recite the divine
office, either with the priests, or among themselves, or even
individually.

101\. 

1. In accordance with the centuries-old tradition of the Latin
rite, the Latin language is to be retained by clerics in the divine
office. But in individual cases the ordinary has the power of granting
the use of a vernacular translation to those clerics for whom the use of
Latin constitutes a grave obstacle to their praying the office properly.
The vernacular version, however, must be one that is drawn up according
to the provision of Art. 36.

2. The competent superior has the power to grant the use of the
vernacular in the celebration of the divine office, even in choir, to
nuns and to members of institutes dedicated to acquiring perfection,
both men who are not clerics and women. The version, however, must be
one that is approved.

3. Any cleric bound to the divine office fulfills his obligation if he
prays the office in the vernacular together with a group of the faithful
or with those mentioned in 52 above provided that the text of the
translation is approved.


{{< pagebreak >}}

# CHAPTER V -- THE LITURGICAL YEAR

[102]{#102}. Holy Mother Church is conscious that she must celebrate the
saving work of her divine Spouse by devoutly recalling it on certain
days throughout the course of the year. Every week, on the day which she
has called the Lord\'s day, she keeps the memory of the Lord\'s
resurrection, which she also celebrates once in the year, together with
His blessed passion, in the most solemn festival of Easter.

Within the cycle of a year, moreover, she unfolds the whole mystery of
Christ, from the incarnation and birth until the ascension, the day of
Pentecost, and the expectation of blessed hope and of the coming of the
Lord.

Recalling thus the mysteries of redemption, the Church opens to the
faithful the riches of her Lord\'s powers and merits, so that these are
in some way made present for all time, and the faithful are enabled to
lay hold upon them and become filled with saving grace.

103\. In celebrating this annual cycle of Christ\'s mysteries, holy
Church honors with especial love the Blessed Mary, Mother of God, who is
joined by an inseparable bond to the saving work of her Son. In her the
Church holds up and admires the most excellent fruit of the redemption,
and joyfully contemplates, as in a faultless image, that which she
herself desires and hopes wholly to be.

104\. The Church has also included in the annual cycle days devoted to
the memory of the martyrs and the other saints. Raised up to perfection
by the manifold grace of God, and already in possession of eternal
salvation, they sing God\'s perfect praise in heaven and offer prayers
for us. By celebrating the passage of these saints from earth to heaven
the Church proclaims the paschal mystery achieved in the saints who have
suffered and been glorified with Christ; she proposes them to the
faithful as examples drawing all to the Father through Christ, and
through their merits she pleads for God\'s favors.

105\. Finally, in the various seasons of the year and according to her
traditional discipline, the Church completes the formation of the
faithful by means of pious practices for soul and body, by instruction,
prayer, and works of penance and of mercy.

Accordingly the sacred Council has seen fit to decree as follows.

106\. By a tradition handed down from the apostles which took its origin
from the very day of Christ\'s resurrection, the Church celebrates the
paschal mystery every eighth day; with good reason this, then, bears the
name of the Lord\'s day or Sunday. For on this day Christ\'s faithful
are bound to come together into one place so that; by hearing the word
of God and taking part in the eucharist, they may call to mind the
passion, the resurrection and the glorification of the Lord Jesus, and
may thank God who \"has begotten them again, through the resurrection of
Jesus Christ from the dead, unto a living hope\" (1 Pet. 1:3). Hence the
Lord\'s day is the original feast day, and it should be proposed to the
piety of the faithful and taught to them so that it may become in fact a
day of joy and of freedom from work. Other celebrations, unless they be
truly of greatest importance, shall not have precedence over the Sunday
which is the foundation and kernel of the whole liturgical year.

107\. The liturgical year is to be revised so that the traditional
customs and discipline of the sacred seasons shall be preserved or
restored to suit the conditions of modern times; their specific
character is to be retained, so that they duly nourish the piety of the
faithful who celebrate the mysteries of Christian redemption, and above
all the paschal mystery. If certain adaptations are considered necessary
on account of local conditions, they are to be made in accordance with
the provisions of Art. 39 and 40.

108\. The minds of the faithful must be directed primarily toward the
feasts of the Lord whereby the mysteries of salvation are celebrated in
the course of the year. Therefore, the proper of the time shall be given
the preference which is its due over the feasts of the saints, so that
the entire cycle of the mysteries of salvation may be suitably recalled.

109\. The season of Lent has a twofold character: primarily by recalling
or preparing for baptism and by penance, it disposes the faithful, who
more diligently hear the word of God and devote themselves to prayer, to
celebrate the paschal mystery. This twofold character is to be brought
into greater prominence both in the liturgy and by liturgical
catechesis. Hence:

a) More use is to be made of the baptismal features proper to the Lenten liturgy; some of them, which used to flourish in bygone days, are to be restored as may seem good.

b) The same is to apply to the penitential elements. As regards instruction it is important to impress on the minds of the faithful not only a social consequences of sin but also that essence of the virtue of penance which leads to the detestation of sin as an offence against God; the role of the Church in penitential practices is not to be passed over, and the people must be exhorted to pray for sinners.

110\. During Lent penance should not be only internal and individual,
but also external and social. The practice of penance should be fostered
in ways that are possible in our own times and in different regions, and
according to the circumstances of the faithful; it should be encouraged
by the authorities mentioned in Art. 22.

Nevertheless, let the paschal fast be kept sacred. Let it be celebrated
everywhere on Good Friday and, where possible, prolonged throughout Holy
Saturday, so that the joys of the Sunday of the resurrection may be
attained with uplifted and clear mind.

111\. The saints have been traditionally honored in the Church and their
authentic relics and images held in veneration. For the feasts of the
saints proclaim the wonderful works of Christ in His servants, and
display to the faithful fitting examples for their imitation.

Lest the feasts of the saints should take precedence over the feasts
which commemorate the very mysteries of salvation, many of them should
be left to be celebrated by a particular Church or nation or family of
religious; only those should be extended to the universal Church which
commemorate saints who are truly of universal importance.


{{< pagebreak >}}

# CHAPTER -- VI SACRED MUSIC

112\. The musical tradition of the universal Church is a treasure of
inestimable value, greater even than that of any other art. The main
reason for this pre-eminence is that, as sacred song united to the
words, it forms a necessary or integral part of the solemn liturgy.

Holy Scripture, indeed, has bestowed praise upon sacred song
[^42], and the same may be said of the fathers
of the Church and of the Roman pontiffs who in recent times, led by St.
Pius X, have explained more precisely the ministerial function supplied
by sacred music in the service of the Lord.

Therefore sacred music is to be considered the more holy in proportion
as it is more closely connected with the liturgical action, whether it
adds delight to prayer, fosters unity of minds, or confers greater
solemnity upon the sacred rites. But the Church approves of all forms of
true art having the needed qualities, and admits them into divine
worship.

Accordingly, the sacred Council, keeping to the norms and precepts of
ecclesiastical tradition and discipline, and having regard to the
purpose of sacred music, which is the glory of God and the
sanctification of the faithful, decrees as follows.

113\. Liturgical worship is given a more noble form when the divine
offices are celebrated solemnly in song, with the assistance of sacred
ministers and the active participation of the people.

As regards the language to be used, the provisions of Art. 36 are to be
observed; for the Mass, Art. 54; for the sacraments, Art. 63; for the
divine office. Art. 101.

114\. The treasure of sacred music is to be preserved and fostered with
great care. Choirs must be diligently promoted, especially in cathedral
churches; but bishops and other pastors of souls must be at pains to
ensure that, whenever the sacred action is to be celebrated with song,
the whole body of the faithful may be able to contribute that active
participation which is rightly theirs, as laid down in Art. 28 and 30.

115\. Great importance is to be attached to the teaching and practice of
music in seminaries, in the novitiates and houses of study of religious
of both sexes, and also in other Catholic institutions and schools. To
impart this instruction, teachers are to be carefully trained and put in
charge of the teaching of sacred music.

It is desirable also to found higher institutes of sacred music whenever
this can be done.

Composers and singers, especially boys, must also be given a genuine
liturgical training.

116\. The Church acknowledges Gregorian chant as specially suited to the
Roman liturgy: therefore, other things being equal, it should be given
pride of place in liturgical services.

But other kinds of sacred music, especially polyphony, are by no means
excluded from liturgical celebrations, so long as they accord with the
spirit of the liturgical action, as laid down in Art. 30.

117\. The typical edition of the books of Gregorian chant is to be
completed; and a more critical edition is to be prepared of those books
already published since the restoration by St. Pius X.

It is desirable also that an edition be prepared containing simpler
melodies, for use in small churches.

118\. Religious singing by the people is to be intelligently fostered so
that in devotions and sacred exercises, as also during liturgical
services, the voices of the faithful may ring out according to the norms
and requirements of the rubrics.

119\. In certain parts of the world, especially mission lands, there are
peoples who have their own musical traditions, and these play a great
part in their religious and social life. For this reason due importance
is to be attached to their music, and a suitable place is to be given to
it, not only in forming their attitude toward religion, but also in
adapting worship to their native genius, as indicated in Art. 39 and 40.

Therefore, when missionaries are being given training in music, every
effort should be made to see that they become competent in promoting the
traditional music of these peoples, both in schools and in sacred
services, as far as may be practicable.

120\. In the Latin Church the pipe organ is to be held in high esteem,
for it is the traditional musical instrument which adds a wonderful
splendor to the Church\'s ceremonies and powerfully lifts up man\'s mind
to God and to higher things.

But other instruments also may be admitted for use in divine worship,
with the knowledge and consent of the competent territorial authority,
as laid down in Art. 22, 52, 37, and 40. This may be done, however, only
on condition that the instruments are suitable, or can be made suitable,
for sacred use, accord with the dignity of the temple, and truly
contribute to the edification of the faithful.

121\. Composers, filled with the Christian spirit, should feel that
their vocation is to cultivate sacred music and increase its store of
treasures.

Let them produce compositions which have the qualities proper to genuine
sacred music, not confining themselves to works which can be sung only
by large choirs, but providing also for the needs of small choirs and
for the active participation of the entire assembly of the faithful.

The texts intended to be sung must always be in conformity with Catholic
doctrine; indeed they should be drawn chiefly from holy scripture and
from liturgical sources.

{{< pagebreak >}}

# CHAPTER VII -- SACRED ART AND SACRED FURNISHINGS

122\. Very rightly the fine arts are considered to rank among the
noblest activities of man\'s genius, and this applies especially to
religious art and to its highest achievement, which is sacred art. These
arts, by their very nature, are oriented toward the infinite beauty of
God which they attempt in some way to portray by the work of human
hands; they achieve their purpose of redounding to God\'s praise and
glory in proportion as they are directed the more exclusively to the
single aim of turning men\'s minds devoutly toward God.

Holy Mother Church has therefore always been the friend of the fine arts
and has ever sought their noble help, with the special aim that all
things set apart for use in divine worship should be truly worthy,
becoming, and beautiful, signs and symbols of the supernatural world,
and for this purpose she has trained artists. In fact, the Church has,
with good reason, always reserved to herself the right to pass judgment
upon the arts, deciding which of the works of artists are in accordance
with faith, piety, and cherished traditional laws, and thereby fitted
for sacred use.

The Church has been particularly careful to see that sacred furnishings
should worthily and beautifully serve the dignity of worship, and has
admitted changes in materials, style, or ornamentation prompted by the
progress of the technical arts with the passage of time.

Wherefore it has pleased the Fathers to issue the following decrees on
these matters.

123\. The Church has not adopted any particular style of art as her very
own; she has admitted styles from every period according to the natural
talents and circumstances of peoples, and the needs of the various
rites. Thus, in the course of the centuries, she has brought into being
a treasury of art which must be very carefully preserved. The art of our
own days, coming from every race and region, shall also be given free
scope in the Church, provided that it adorns the sacred buildings and
holy rites with due reverence and honor; thereby it is enabled to
contribute its own voice to that wonderful chorus of praise in honor of
the Catholic faith sung by great men in times gone by.

124\. Ordinaries, by the encouragement and favor they show to art which
is truly sacred, should strive after noble beauty rather than mere
sumptuous display. This principle is to apply also in the matter of
sacred vestments and ornaments.

Let bishops carefully remove from the house of God and from other sacred
places those works of artists which are repugnant to faith, morals, and
Christian piety, and which offend true religious sense either by
depraved forms or by lack of artistic worth, mediocrity and pretense.

And when churches are to be built, let great care be taken that they be
suitable for the celebration of liturgical services and for the active
participation of the faithful.

125\. The practice of placing sacred images in churches so that they may
be venerated by the faithful is to be maintained. Nevertheless their
number should be moderate and their relative positions should reflect
right order. For otherwise they may create confusion among the Christian
people and foster devotion of doubtful orthodoxy.

126\. When passing judgment on works of art, local ordinaries shall give
a hearing to the diocesan commission on sacred art and, if needed, also
to others who are especially expert, and to the commissions referred to
in Art. 44, 45, and 46.

Ordinaries must be very careful to see that sacred furnishings and works
of value are not disposed of or dispersed; for they are the ornaments of
the house of God.

127\. Bishops should have a special concern for artists, so as to imbue
them with the spirit of sacred art and of the sacred liturgy. This they
may do in person or through suitable priests who are gifted with a
knowledge and love of art.

It is also desirable that schools or academies of sacred art should be
founded in those parts of the world where they would be useful, so that
artists may be trained.

All artists who, prompted by their talents, desire to serve God\'s glory
in holy Church, should ever bear in mind that they are engaged in a kind
of sacred imitation of God the Creator, and are concerned with works
destined to be used in Catholic worship, to edify the faithful, and to
foster their piety and their religious formation.

128\. Along with the revision of the liturgical books, as laid down in
Art. 25, there is to be an early revision of the canons and
ecclesiastical statutes which govern the provision of material things
involved in sacred worship. These laws refer especially to the worthy
and well planned construction of sacred buildings, the shape and
construction of altars, the nobility, placing, and safety of the
eucharistic tabernacle, the dignity and suitability of the baptistery,
the proper ordering of sacred images, embellishments, and vestments.
Laws which seem less suited to the reformed liturgy are to be brought
into harmony with it, or else abolished; and any which are helpful are
to be retained if already in use, or introduced where they are lacking.

According to the norm of Art. 22 of this Constitution, the territorial
bodies of bishops are empowered to adapt such things to the needs and
customs of their different regions; this applies especially to the
materials and form of sacred furnishings and vestments.

129\. During their philosophical and theological studies, clerics are to
be taught about the history and development of sacred art, and about the
sound principles governing the production of its works. In consequence
they will be able to appreciate and preserve the Church\'s venerable
monuments, and be in a position to aid, by good advice, artists who are
engaged in producing works of art.

130\. It is fitting that the use of pontificals be reserved to those
ecclesiastical persons who have episcopal rank or some particular
jurisdiction.

{{< pagebreak >}}

# APPENDIX -- A DECLARATION OF THE SECOND ECUMENICAL COUNCIL OF THE VATICAN ON REVISION OF THE CALENDAR

The Second Ecumenical Sacred Council of the Vatican, recognizing the
importance of the wishes expressed by many concerning the assignment of
the feast of Easter to a fixed Sunday and concerning an unchanging
calendar, having carefully considered the effects which could result
from the introduction of a new calendar, declares as follows:

1.  The Sacred Council would not object if the feast of Easter were
    assigned to a particular Sunday of the Gregorian Calendar, provided
    that those whom it may concern, especially the brethren who are not
    in communion with the Apostolic See, give their assent.
2.  The sacred Council likewise declares that it does not oppose efforts
    designed to introduce a perpetual calendar into civil society.

But among the various systems which are being suggested to stabilize a
perpetual calendar and to introduce it into civil life, the Church has
no objection only in the case of those systems which retain and
safeguard a seven-day week with Sunday, without the introduction of any
days outside the week, so that the succession of weeks may be left
intact, unless there is question of the most serious reasons. Concerning
these the Apostolic See shall judge.

[^1]: Secret of the ninth Sunday after Pentecost.

[^2]: Cf. *Heb*. 13:14.

[^3]: Cf. *Eph.* 2:21-22.

[^4]: Cf. *Eph*. 4:13.

[^5]: Cf. *Is*. 11:12.

[^6]: Cf. *John* 11:52.

[^7]: Cf. *John* 10:16.

[^8]: Cf. I*s*. 61:1; *Luke* 4:18.

[^9]: St. Ignatius of Antioch, *To the Ephesians*,
7, 2.

[^10]: Cf. 1 *Tim*. 2:5.

[^11]: *Sacramentarium* *Veronese* (ed.
Mohlberg), n. 1265; cf. also n. 1241, 1248.

[^12]: Easter Preface of the Roman Missal.

[^13]: Prayer before the second lesson for Holy
Saturday, as it was in the Roman Missal before the restoration of Holy
Week.

[^14]: Cf. *Mark* 16:15.

[^15]: Cf. *Acts* 26:18.

[^16]: Cf. *Rom*. 6:4; *Eph*. 2:6; *Col*. 3:1; 2
Tim. 2:11.

[^17]: Cf. *John* 4:23.

[^18]: Cf. 1 *Cor*. 11:26.

[^19]: Council of Trent, Session XIII, *Decree on
the Holy Eucharist*, c.5.

[^20]: Council of Trent, Session XXII, *Doctrine
on the Holy Sacrifice of the Mass*, c. 2.

[^21]: Cf. St. Augustine, *Tractatus in Ioannem*,
VI, n. 7.

[^22]: Cf. *Apoc*. 21:2; *Col*. 3:1; *Heb*. 8:2.

[^23]: Cf. *Phil*. 3:20; *Col*. 3:4.

[^24]: Cf. *John* 17:3; *Luke* 24:27; *Acts*
2:38.

[^25]: Cf. *Matt*. 28:20.

[^26]: Postcommunion for both Masses of Easter
Sunday.

[^27]: Collect of the Mass for Tuesday of Easter
Week.

[^28]: Cf. 2 *Cor*. 6:1.

[^29]: Cf. *Matt*. 6:6.

[^30]: Cf . 1 *Thess*. 5:17.

[^31]: Cf . 2 *Cor*. 4:10-11.

[^32]: Secret for Monday of Pentecost Week.

[^33]: St. Cyprian, *On the Unity of the Cathotic
Church*, 7; cf. *Letter 66*, n. 8, 3.

[^34]: Cf. Council of Trent, Session XXII,
*Doctrine on the Holy Sacrifice of the Mass*, c. 8.

[^35]: Cf. St. Ignatius of Antioch, *To the
Smyrnians*, 8; *To the Magnesians*, 7; *To the Philadelphians*, 4.

[^36]: Cf. St. Augustine, *Tractatus in Ioannem*,
VI, n. 13.

[^37]: Roman Breviary, feast of Corpus Christi,
Second Vespers, antiphon to the Magnificat.

[^38]: Cf. St. Cyril of Alexandria, *Commentary
on the Gospel of John*, book XI, chap. XI-XII: Migne, Patrologia Graeca,
74, 557-564.

[^39]: Cf. 1 *Tim*. 2:1-2.

[^40]: Session XXI, July 16, 1562. *Doctrine on
Communion under Both Species*, chap. 1-3: Condlium Tridentinum.
*Diariorum, Actorum, Epistolarum*, Tractatuum nova collectio ed. Soc.
Goerresiana, tome VIII (Freiburg in Br., 1919), 698-699.

[^41]: Council of Trent, Session XXIV, November
11, 1563, *On Reform*, chap. I. Cf. Roman Ritual, title VIII, chap. II,
n. 6.

[^42]: Cf. *Eph*. 5:19; Col. 3:16.

